### ISSUE TITLE
Remove debian/ directory from Released tarball

### ISSUE THREAD

**Issue by kartikm** [scanmem/scanmem#105]
Please remove debian/ directory from release tarball v0.15. It should be handled by Debian packaging and can cause issue in packaging automatically.

Thanks!

**Comment by coolwanglu** [comment]
How about I create a `0.15.1` for the latest commit?

**Comment by kartikm** [comment]
@coolwanglu That's fine too.

**Comment by coolwanglu** [comment]
https://github.com/scanmem/scanmem/releases

It's done. :)
