### ISSUE TITLE
0.15.y stable branch required with setting new versions to configure.ac

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#112]
Distributions picked up version 0.15.1 but from 0.15 to 0.15.1 a new feature has been introduced (--without-readline). Also the version number in configure.ac hasn't been updated. This is **not** how maintaining stable versions works.

In general it works by maintaining a special stable branch. Let's call this "0.15.y" to do it in the way like the Linux kernel does it. Only bug fixes are cherry-picked from the master branch to that branch. Features and performance optimization are left out for not introducing new bugs. The version in configure.ac has to be updated as well when releasing a new bugfix version for the distributions. Only this way it's also visible to the user that the package update worked and that the bug will be fixed. With `git cherry-pick -x -e <commit_id>` it is possible to change the long description of the commit to be cherry-picked and the upstream commit ID is already included. It is very useful to place a line like this on top of the long description:
````
commit 047b93675ae2e50060d2a68edfbb1aff26be26ac upstream.
````
I'm volunteering to do it like this and to maintain the stable branch.

Any comments regarding this?
Any votes showing me that you want this as well?

**Comment by sriemer** [comment]
Please have a look at https://github.com/scanmem/scanmem/commits/0.15.y - I've queued up 4 patches fixing string/bytearray search in GC with Python 3 for v0.15.2.

**Comment by coolwanglu** [comment]
Yes I should have updated configure.ac accordingly. 
I don't think we need to maintain stable branches. As soon as we release a newer version, old versions are deprecated automatically. This just requires more maintenance efforts.

**Comment by sriemer** [comment]
Okay, I'm fine with providing minor releases which provide bug fixes as well as features and leaving the decision to the package maintainers whether to accept these or to apply just the bugfix patches on top of the release. Thanks for clarification!
