### ISSUE TITLE
no python cache files generated/deployed for gameconqueror via make install target

### ISSUE THREAD

**Issue by anthraxx** [scanmem/scanmem#116]
Hey, the issue is more problematic (for packaging) then it sounds, first let me explain it:

after 'make install' the python files will be distributed to 'usr/share/gameconqueror/' without generating .pyc and .pyo files. If the GUI is started with uid=0 then python has write access to that directory and will generate those caching files for all modules that are somewhere imported (via GameConqueror.py). This results in dirty and untracked files laying around in that directory. If the software is then uninstalled, those cache files remain as they are not tracked as packaged files.

example for python3:
>
find /usr/share/gameconqueror/ -name "*.pyc" -o -name "*.pyo"

>
/usr/share/gameconqueror/__pycache__/backend.cpython-34.pyc
/usr/share/gameconqueror/__pycache__/consts.cpython-34.pyc
/usr/share/gameconqueror/__pycache__/misc.cpython-34.pyc
/usr/share/gameconqueror/__pycache__/hexview.cpython-34.pyc

Resolution:
generate those in a Makefile target and deploy them via 'install' target:

Proposal 1:
add those to make target and distribute the .pyc and .pyo files
>
python -m compileall .
python -O -m compileall .

Proposal 2::
better way for python via setuptools setup.py
> python setup.py install -O1 

packages that distribute python files/modules that are imported should always by itself create and deploy the caching files to avoid cluttering the filesystem and having untracked files laying around.

**Comment by sriemer** [comment]
Sounds reasonable to me. Thanks for reporting! Should be fixed ASAP but doesn't require a new upstream release. Package maintainers can apply the patch on top of the release.

Unfortunately, Python is my weak spot. I'm not sure yet how to do that with autotools. Would you be able to provide a patch faster?

**Comment by anthraxx** [comment]
I'm not a big fan of autotools but I can look into this in the following days. Which way do you prefer the solution, should I implement a full setup.py with setuptools or do you only want to issue the python compileall modules?

If you don't mind, I would go the setuptools way and provide a patch that adds setup.py and calls it via autotools.

**Comment by sriemer** [comment]
If that's the common and preferred method, then I also prefer the setuptools way. I have to do some searching on the web.

**Comment by sriemer** [comment]
No progress here? Hmmm, then I think I have to do it myself somehow. In my Python book there are 12 pages about distributing Python projects with `distutils`.

**Comment by anthraxx** [comment]
sorry I'm very busy in the past weeks, no time for additional tasks currently :(
sure distutils should also do it, bigger projects all migrate to setuptools but i guess that makes no difference for that tiny piece... important is just the -O2 switch :D

**Comment by sriemer** [comment]
I'm an expert for C/C++. I don't know why I have to fix all the Python stuff with my beginner level experience,... But I have the solution now. It is described here:
http://www.gnu.org/software/automake/manual/html_node/Python.html

**Comment by sriemer** [comment]
Please test the code from PR #121 as well. And give us some feedback if it fixes the issue for you.

**Comment by anthraxx** [comment]
i can confirm that the referenced commit fixes #116 and creates all caching entries.

**Comment by sriemer** [comment]
Thanks for testing and confirming! I've just added you to `Reported-by` in the commit description like it has to be. Sorry, I was in a hurry - but nothing a forceful push can't fix. ;-) Code is the same.

**Comment by sriemer** [comment]
Merged.
