### ISSUE TITLE
Feature request: core dumps support

### ISSUE THREAD

**Issue by monokhrome** [scanmem/scanmem#117]
How difficult will it be to add core dumps support? Sometimes it's really faster to continuously transfer coredumps to another computer rather than run scanmem locally.

**Comment by sriemer** [comment]
We would have to decode the core dump, read from there and all you could do with it would be an initial scan likely resulting in too many matches. Scanmem is (or should be) quite lighweight. So at the end it should come down to the speed of the memory. Transfering the memory also doesn't mean scanning it.

Have you tried scanmem v0.15.2?

We have major performance optimizations in there resulting in scanning in only half the time than before. On embedded systems the effect is likely even bigger.

**Comment by sriemer** [comment]
Reading several GiB from disk into memory again is also quite slow but we would have to do that then.

For me this doesn't sound reasonable. Having the console output somewhere else rather sounds like a good idea but there is usually ssh for that.

**Comment by sriemer** [comment]
It would be easy to write a small Python script or C tool to read the core dump into heap memory and then to continuously sleep. Then you could use scanmem on this. But good luck with detecting which memory region this was origionally.

**Comment by monokhrome** [comment]
Hm, actually I'm running a quite outdated version of scanmem, should really give a try with a recent one.
In my particular scenario I use scanmem in pair with GDB to identify possible locations of some variables with unknown value in regions of interest (hence, I use snapshot command and relative comparisons - that's quite slow on embedded systems), after getting a more or less narrow list I just add watchpoints one by one in GDB to see if that's what I've been looking for and for further examination. So, basically I'm not that interested in identifying what memory region was that - I already know it.
Thanks for the advice on loading core dumps on the heap - it actually should work for me, I'll just have to malloc() a buffer, put the first dump there, snapshot in scanmem, load next dump, compare, and so on.
