### ISSUE TITLE
Distributions should pick up >= v0.15.2

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#119]
This is just a tracking issue to check where the distributions are at the moment and if they follow our advice to update to >= v0.15.2.

Distribution | Maintainer(s) | Latest Unstable | Link
-------------- | ------------- | ------------------- | ------
Arch | Levente Polyak | 0.15.3-1 | https://www.archlinux.org/packages/community/x86_64/scanmem/
Debian | Kartik Mistry | 0.13-1 (0.15.3 known) | https://tracker.debian.org/pkg/scanmem
Fedora | Igor Gnatenko, Jakub Hrozek | 0.15.3-1 (fc23, fc24) | https://apps.fedoraproject.org/packages/scanmem
Gentoo | random | 0.15.2 | https://packages.gentoo.org/package/dev-util/scanmem
Mageia | Shlomi Fish | 0.15.2 (Cauldron) | https://bugs.mageia.org/show_bug.cgi?id=16261
openSUSE | inofficially built by Javier García Capel | 0.15.2 | https://build.opensuse.org/package/show/home:javilete/Scanmem
Ubuntu | @coolwanglu ??? | 0.13-1 (Xenial) | https://launchpad.net/ubuntu/+source/scanmem/ (depends on Debian version)
Ubuntu PPA | @sriemer | 0.15.3 (Xenial) | https://launchpad.net/~s-parschauer/+archive/ubuntu/game-cheating

**Comment by sriemer** [comment]
There is a lot of 0.13 out there. I'd like to get rid of it - plain can't support it any more. We've increased the development speed quite a lot.

**Comment by sriemer** [comment]
I'm good at Debian and Ubuntu stuff - also got some experience with Gentoo ebuilds. Just tell me if I can help at the distros.

**Comment by sriemer** [comment]
Gentoo bug: https://bugs.gentoo.org/show_bug.cgi?id=553640
openSUSE bug: https://bugzilla.opensuse.org/show_bug.cgi?id=936549

Maintainers contacted via email directly as well.

Still got no idea what to do about Ubuntu.
Bug: https://bugs.launchpad.net/ubuntu/+source/scanmem/+bug/1467326

**Comment by sriemer** [comment]
Found a hacky scanmem 0.13 port for FreeBSD. I'm working on upstream FreeBSD support. Once that's ready, then we could ask them to update as well.

Distribution | Maintainer(s) | Latest Unstable | Link
-------------- | ------------- | ------------------- | ------
FreeBSD | danfe@FreeBSD.org | 0.13 | http://www.freshports.org/sysutils/scanmem

**Comment by coolwanglu** [comment]
If I remember correctly, Ubuntu just follows packages from Debian, not sure if it's still the same now. Usually new packages are provided by PPA. There used to be a scanmem PPA, but I do not maintain it any more.

Generally I think you do not have to pay much attention to the individual downstream distributions, but of course you're welcome to do so if you like :)

**Comment by sriemer** [comment]
All these are potential testers willing to contribute somewhen. I don't want them to test completely outdated stuff and then sending us bug reports for these versions. We also still have to promote our new upstream a bit more (need more stargazers and watchers). ;-)

**Comment by coolwanglu** [comment]
Sure :)

**Comment by sriemer** [comment]
Btw.: If we differentiate between blue, red, green or orange distributions, then we aren't much better than the greedy red distribution which always annoys me at work when they are the upstream for code I find a bug for. "We help you only if you use our distribution or the latest unstable upstream kernel and pay us a shitload of money for support. Otherwise, we just ignore you on our upstream mailing lists,...". Commercial FOSS can really suck!

**Comment by Polynomial-C** [comment]
I can take care of the gentoo ebuild. Currently I'm struggeling with python3 support in the ebuild. I must admit that our (Gentoo's) python framework can be quite confusing.

**Comment by sriemer** [comment]
@Polynomial-C Thank you very much for that offer. I'm sure that would help some people a lot. Looks like a Gentoo maintainer for that package is needed.

**Comment by Polynomial-C** [comment]
Don't worry. As gentoo developer I have commit access ;)

**Comment by sriemer** [comment]
Rather minor compared to the fixes we did before but PR #121 should be also picked up on top of v0.15.2.

**Comment by sriemer** [comment]
PR #124 should be applied. It is an important fix for static memory cheating with PIE.

**Comment by sriemer** [comment]
[**v0.15.3**](https://github.com/scanmem/scanmem/releases/tag/v0.15.3) has been released to address the issues in v0.15.2 and to scan even faster by function inlining.

**Comment by sriemer** [comment]
Ubuntu users can get latest scanmem/GameConqueror from my own PPA built with full hardening: https://launchpad.net/~s-parschauer/+archive/ubuntu/game-cheating. I've waited long enough for @kartikm and @coolwanglu.
