### ISSUE TITLE
Need more shortcuts or completions on the command line

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#123]
I'm going crazy typing:
````
option scan_data_type float32
````
all the time. Most games use a lot of floats. "option" is completed but everything else isn't.
I need at least completion for all three.

What about fast type selection?

I even think about making "number", "int", "float", "int8", "int16", "int32", "int64", "float32", "float64", "bytearray" and "string" top level commands to access them fast and to benefit from completion.

**Anybody else who has a need for this?**

**Comment by sriemer** [comment]
It's unfair that type selection goes faster with the GUI.

**Comment by sriemer** [comment]
@coolwanglu I've got the top level commands with the referenced commit. :-) This is a must have for usability on the command line. Any comments? Should I send a PR?

**Comment by coolwanglu** [comment]
I like shortcuts, but these top level commands look confusing.
It'd be better if we use a symbox prefix, e.g. `?`. But we'll need to make sure that we do not introduce conflicts with existing commands.

**Comment by sriemer** [comment]
Why do they look confusing? They don't conflict with anything else and the type can be set fast with them. I would rather find it confusing and cumbersome using a special symbol prefix. That would be not really intuitive.

**Comment by coolwanglu** [comment]
We always have a verb for the action, except for the actual values that we search for.
If you don't like prefixes, how about the `type` command?

Btw, there's a typo in `bytearray`.

Anyway I'll try to test it myself.

**Comment by sriemer** [comment]
Right, thanks, needs to be fixed. I've just hacked it fast to have something immediately. A `type` command would only work if the actual type would also be completed. But then I would be fine with that.

**Comment by sriemer** [comment]
Nobody else seems to need this. I'm fine with having a custom hack for this at the moment. So I'll fix this somewhen later correctly and close this issue for now.
