### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [scanmem/scanmem#130]
Would you like to add more error handling for return values from functions like the following?
- [fclose](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "Close a stream.") ⇒ [readmaps](https://github.com/scanmem/scanmem/blob/0d47cc2dd84c9557969532b6115cdc79d9b84271/maps.c#L259)
- [fprintf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html "Print formatted output.") ⇒ [printversion](https://github.com/scanmem/scanmem/blob/d89b7b22892995cf11353c64e8e25d08dde35f0c/menu.c#L158)

**Comment by sriemer** [comment]
What do you think should we do in the error cases?

If the fclose() for the maps file would fail, then there is still everything loaded into the regions list. The maps variable is reset upon the next scanmem "reset" command. So there is no need to fail the function. It would be a hardware error or a really stupid programming mistake that fclose() would fail. The only failure case would be that the FILE pointer is invalid - very unlikely.

Now let's assume fprintf() of the version text fails. That would mean that stdout of the terminal has been closed or something like that. Should we reset the terminal now and print it again? Scripts notice that there is no output and also a user would notice. So there is no need to act here.

We have more important issues. There is no need to be pedantic here.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") generally.
How do you think about to make the error reaction configurable?

**Comment by sriemer** [comment]
Should I write `(void)` in front of them to explicitly ignore them to show "yes, we thought about this"?
Making too many things configurable makes things only too complex and too hard to test/review. There is no real security issue here. Static code analyzers would only report false-positives for these.

**Comment by elfring** [comment]
A cast to void will not help to improve exception handling for this software.

**Comment by sriemer** [comment]
Closing unless there is a concrete patch or security issue.
