### ISSUE TITLE
ptrace: checkmatches() is very slow due to ptrace()

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#133]
The issue is that checkmatches() only supports ptrace() but doesn't provide /proc/$pid/mem support in contrast to searchregions().

Let's compare some performance values taken from an Intel Core i5 system scanning in 500 MB of zeroed memory:

| Test | Search Pattern | Function | Time |
| --- | --- | --- | --- |
| nothing matches | 10 | searchregions() | about 10s |
| everything matches | 0 | searchregions() | about 20s |
| find nothing in matches | 10 after 0 | checkmatches() | about 60s |

Real world use case:
- search for bools

Bools are usually `unsigned char` 8-bit types with the only possible values 0 and 1. These values occur at many locations in memory. There are also large consecutive blocks of them - especially for 0.

**Comment by sriemer** [comment]
TODO: Evaluate at which chunks size and which distance between matches which method is faster.

**Comment by sriemer** [comment]
Postponed for now.

**Comment by 12345ieee** [comment]
On this topic: `sm_checkmatches()` wastes a lot of time out of the hot path by calling `truncval()` (inlined), which sets 10 flags one-by-one.

Commit 12345ieee@5f277fa introduces a value to set them all with a single int16 bitwise operation, for a 10% speedup. This could technically act on uninitialized padding bits if the receiving struct is uninitialized, but in any case the bits we're interested in get the right value.

**Comment by 12345ieee** [comment]
I have great news, what I was detailing in https://github.com/scanmem/scanmem/issues/304#issuecomment-367419399 works, and works very well.
Testing on 500 MB of zeroed memory, using `snapshot;update`, I recommend using this combination in memory retrieval tests, as it performs absolutely no matching logic.

`searchregions` alone
```
andreas@trelitri:~/Progetti/scanmem$ time ./scanmem -p `pidof memfake` -c 'snapshot;exit'
[...]
info: we currently have 524615680 matches.
524615680> exit

real	0m5,118s
user	0m4,166s
sys	0m0,908s
```

current master
```
andreas@trelitri:~/Progetti/scanmem$ time ./scanmem -p `pidof memfake` -c 'snapshot;update;exit'
[...]
info: we currently have 524615680 matches.
524615680> exit

real	0m57,418s
user	0m27,082s
sys	0m30,325s
```

this patch, with `READ_CHUNK` at 512 (1024 would shave another 1.5s, 2048 would shave 2.5s)
```
andreas@trelitri:~/Progetti/scanmem$ time ./scanmem -p `pidof memfake` -c 'snapshot;update;exit'
[...]
info: we currently have 524615680 matches.
524615680> exit

real	0m19,777s
user	0m16,195s
sys	0m3,406s
```

The patch is here: [check_matches_pread.txt](https://github.com/scanmem/scanmem/files/1746022/check_matches_pread.txt)

Notice that this patch is terrible in every aspect, the function rebuilds the `proc/pid/mem` filename and reopens it at each call, but nevertheless cuts so many syscalls that it is still much faster.
This also hardcodes `pread()` in, writing proper wrappers will take a bit.
It is also missing a proper handling of partial and partially OOB reads.

Still, it shows that we can implement a good `proc/pid/mem` usage in `checkmatches()`.

I think I'll work on it in the following days, but I'd appreciate suggestions for correctly detecting and handling partial reads (`pread` returning less than `READ_CHUNK` for any reason) and partially OOB reads (aka reading past the end of a region, I suppose this is safe to do and `pread` just returns up to the end).

**Comment by sriemer** [comment]
Sounds good, thanks! This confirms that saving several syscalls saves us a lot of search time in situations of high match density. If `pread` returns less bytes, then we can check if the region end is reached. Otherwise these situations should not occur. We should break then as it looks like we don't have the permission to read in this region then. It should be possible to test this with odd chunk sizes like e.g. 513 bytes. Looking forward to the final patch.

**Comment by sriemer** [comment]
This is fixed. Thanks.
