### ISSUE TITLE
Arch Linux requests releasing v0.15.3

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#135]
@anthraxx requested 2015-10-02 releasing v0.15.3 so that #116 is solved when moving scanmem/GameConqueror to the Arch Linux binary repository.

The problem is that we have almost no new features since v0.15.2 - only bug fixes. But we want to provide a reason for upgrading to get the bug fixes rolled out.

TODO:
* further improve performance to provide an upgrade reason
* intensify testing for the release

**Comment by sriemer** [comment]
Some people might have already noticed that I've worked hard the past days to further improve the scan performance. Good news is: I'm done with the quick performance gains by inlining functions and optimizing struct zeroing. Everything more development intensive is left for v0.16.

I'm impressed by the overall performance gain. In real world examples scanmem feels much faster than before. This thing is really the best memory scanning tool on Linux!

I'm intensifying testing now so that we can release soon.

**Comment by anthraxx** [comment]
:+1: :tada: :balloon: ... sorry for the spam... i'm just excited :smile: great work and lot of contribution from your side... thats really cool :+1:

**Comment by sriemer** [comment]
@anthraxx crediting FOSS maintainers is never spam! :+1: It is done way too rarely. :disappointed: Thanks for bringing latest code to Arch Linux!

**Comment by sriemer** [comment]
Testing scanmem and reviewing the parts where functions have been inlined is finished. There are no more uninitialized structures.
Last TODO: Test GameConqueror one more time.

**Comment by sriemer** [comment]
GameConqueror tests done and all passed - also feels faster. :-) Releasing v0.15.3 today! :-)

**Comment by sriemer** [comment]
Performance data scanning in 500 MB of zeroed memory with scanmem on a Intel Core i5:

Pattern | v0.15.2 | v0.15.3 | Gain
------- | ------- | ------- | ----
0 | 32.8s | 20.2s | 38%
10 | 10.8s | 9.4s | 13%
0\n10 | 96.4s | 76.0s | 21%

So if you call a function several million times in the hot memory scanning path, then it is really worth inlining it! Make :snail: to :rocket:!
