### ISSUE TITLE
gui: Crashes when finding matches with region ID >= 100

### ISSUE THREAD

**Issue by calculuswhiz** [scanmem/scanmem#142]
Bad news, another GameConqueror bug. (Probably Python3 related.)  Here's the Traceback:

    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "/usr/lib/python3.5/threading.py", line 923, in _bootstrap_inner
        self.run()
      File "/usr/lib/python3.5/threading.py", line 871, in run
        self._target(*self._args, **self._kwargs)
      File "/usr/share/gameconqueror/GameConqueror.py", line 893, in scan_thread_func
        self.update_scan_result()
      File "/usr/share/gameconqueror/GameConqueror.py", line 918, in update_scan_result
        o = '%x'%(int(o[5:],16),)
    ValueError: invalid literal for int() with base 16: '+        5d1af'

I'd guess it's a result of having a displayable amount of results on the first search?

**Comment by sriemer** [comment]
It's crashing at converting the match offset from Unicode string to a hex number. This has been introduced by aedf0695b899 ("gui: add match offset and region type support"). That was my first GameConqueror commit. Stripping the first 5 chars here is not correct. So I think Python 2 and 3 are facing an issue with this. Python 2 just ignores the spaces in front and Python 3 has an issue with this it seems. Sorry, I haven't had so much experience with Python at that time.

Thanks for reporting! I'll try to reproduce and fix this.

**Comment by sriemer** [comment]
Hmm, just checked again: Stripping away 5 chars in front is correct if the region ID is less than 100.
Example:
````
[ 0]       601048,  0 +       201048,   exe, 8000000000, [I64 ]
````
Might it be possible that you've found a match in a region with a region ID >= 100?

**Comment by sriemer** [comment]
The error output pretty much looks like that as it starts with '+'. So one char too less gets removed resulting in '+        5d1af'.

**Comment by sriemer** [comment]
The output in scanmem is located in [handlers.c:424](https://github.com/scanmem/scanmem/blob/master/handlers.c#L424). There is a further space printed after the '+' which is not stripped away. So we could **strip away the first 6 chars** and support up to **region ID 999**.

**Comment by sriemer** [comment]
I've implemented it with searching for and splitting with the '+' char. I just grab the second value (array ID 1, the string after the '+'). That is most flexible.
@calculuswhiz, please verify that it's fixed. It's always a pleasure to work with you. :+1:

**Comment by calculuswhiz** [comment]
I think it's working fine, but I'll let you know if there's an issue!
