### ISSUE TITLE
gui: GameConqueror doesn't start from .desktop on some distros

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#148]
On some distros like Fedora 23 or Ubuntu 12.04 Precise, GameConqueror doesn't start from the .desktop file but only from the command line. The authentication window isn't shown and there might be a log entry "Refusing to render service to dead parents." with `journalctl`. This might be related to some kind of security fix. This can't be reproduced on Ubuntu 14.04 Trusty so far.

RedHat bug: https://bugzilla.redhat.com/show_bug.cgi?id=1287934

On Ubuntu 12.04 Precise it helped to remove the superfluous `exec` in front of the `pkexec` call. Calling `pkexec` directly is also what `gparted` does.

The bug has been introduced by: "gui: improve pkexec" b75f1be2768d983097add9c2676396085f97a2c1

**Comment by sriemer** [comment]
Testers welcome. Please try it and report back your distro and if it works.

**Comment by Funmungus** [comment]
I came across it and found a workaround so that it runs from command or .desktop launcher.  I am just trying to remember what it is that I did.

**Comment by sriemer** [comment]
The fix is committed for now.

**Comment by sriemer** [comment]
The reason why pkexec misbehaves is that it checks for the parent pid with getppid() and checks if it is an orphan belonging to init (pid == 1). This is why removing the exec helps. Then the bash is the parent of pkexec instead.

See: https://lists.ubuntu.com/archives/foundations-bugs/2012-July/100103.html

**Comment by sriemer** [comment]
@ignatenkobrain should pick up the fix for Fedora to close the bug there.

**Comment by ignatenkobrain** [comment]
OK, will do ASAP
