### ISSUE TITLE
Debian and Ubuntu ship > 5 years old version 0.13 which is full of bugs

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#149]
Debian and Ubuntu still ship > 5 years old version 0.13 which is full of bugs. Previous maintainer was @coolwanglu for the packaging. She stopped providing packages via her PPA but the Ubuntu source package still belongs to her. So I can't take it over. I've created a team "scanmem maintainers" with me and her included. So the source package should belong to that group instead. I've also created my own "game cheating" PPA from where I provide latest versions.

Ubuntu source package:
https://launchpad.net/ubuntu/+source/scanmem

Scanmem maintainers team:
https://launchpad.net/~scanmem

My "game cheating" PPA:
https://launchpad.net/~s-parschauer/+archive/ubuntu/game-cheating

For Debian @kartikm is the maintainer but ran into unknown trouble updating the package. I'd be glad to support but it seems that @kartikm is too busy to get this done.

Debian source package:
https://tracker.debian.org/pkg/scanmem

The source and RedHat distros had no trouble upgrading the package.

See also: #119 

@12345ieee also offers help.

So how to get this done?

I'd suggest we prepare the packaging together for Debian and Ubuntu, put packages into personal repos and ask the Debian/Ubuntu community to allow us to take over maintaining of the scanmem/GameConqueror package.

**Comment by 12345ieee** [comment]
So, I'm moving here my logbook on the 0.13 -> 0.15.3+... upgrade:

* Launching
    * I lost the ability to launch it directly from the Gnome menu. Cause of this is likely the new exec script, which used to use a simple `gksu` but now needs some fancy thing in python, which I'm sure how is supposed to work. Launching from the command-line is fine.
    * I lost the menu icon, 99% due to some changes in the `GameConqueror.desktop`, but I was not able to get the syntax correct to get the icon back. Minor annoyance, but still, the 0.13 had it working.

* After launch
    * First thing it does is complaining about explicit GTK version:  
    `/usr/share/gameconqueror/GameConqueror.py:35: PyGIWarning: Gtk was imported without specifying a version first.
Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
from gi.repository import Gtk`  
but no real issue
    * Every time you open a modal form, you get: `Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.` Again, harmless but it's there.

* Using it
    * Scanning is much faster than 0.13, props to @sriemer 
    * Resizing is still wildly broken, messing a bit with it is easy to get messages as:
    `(GameConqueror.py:4966): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 5 and height -26`
    * i still have strange issues when I close the game before the program, sometimes all is fine, sometimes it drags the whole system with it, still investigating this.

Outstanding bugs:
* Resizing, as already said
* "Manually add an entry" breaks down if you close it with the "X":
    * Open the "Manually add an entry" menu
    * Close it with the "X"
    * Reopen it
    * Bug triggered
    * Closing it with the "Close" button gives no problem.

**Comment by sriemer** [comment]
@12345ieee I suggest you start watching scanmem on GitHub. There is trouble with pkexec fixed recently.
See: #148
The fix is committed.

**Comment by 12345ieee** [comment]
@sriemer done.
For testing should I wait for you to make a PPA build or it's better I compile it from the source?

**Comment by sriemer** [comment]
Just compile from latest source.

**Comment by 12345ieee** [comment]
I confirm the start fix from #148 worked (I'm aligned to `master`).
I'm looking into why there is no icon.

**Comment by 12345ieee** [comment]
Ok, found the problem: http://askubuntu.com/a/64306/412668 (tried and it works)
On freedesktop they recommend to have a 48x48 icon, too.

@sriemer , do you want a pull request or you'll fix those yourself?

**Comment by sriemer** [comment]
Just checked your git commits. I don't like missing long commit descriptions and the past in the short description. We use the [Linux kernel code style](https://www.kernel.org/doc/Documentation/SubmittingPatches) with the exception that we use four spaces instead of tabs for indentation for the C code.

I guess I would have to rework your Git commit any way. The difference between PR and letting me do the commit is if you will be listed as a contributor or not. If I do the patch, then you can only get a Reported-by. So I prefer that you get mentioned as a contributor as you've done the actual work.

I prefer that you send me your patch via e-mail and I apply it directly after possible rework. PRs should be something for long term contributors and for patch sets.

**Comment by 12345ieee** [comment]
I hope you don't expect me to follow all the guidelines of the kernel guys.
I'll simply ask `git-format-patch` to make me some files and then I'll send them to you.

Commit style and indentation are not a problem, though, consider having a `HACKING` file or something like that so that people can get it at from the source.

To make changes to the .deb `postint` I also need to know how you generate the .deb, because it's not exactly clear (I am missing a `debian` directory, to say one).

**Comment by sriemer** [comment]
Just provide the exported patch and I'll rework it to my needs for now to show how it works. GitHub supports a file `CONTRIBUTING.md`. I've already thought about this. But who reads this at the end?

The source I use for my PPA can be found here:
https://github.com/sriemer/scanmem/tree/ubuntu-ppa

It is the Debian way of not providing the Debian directory together with the upstream source. A different git repo or branch is required for the Debian packaging work as usually other people care for the packaging and not necessarily the upstream maintainers.

**Comment by sriemer** [comment]
I've updated my PPA. Waiting for your patches.

**Comment by 12345ieee** [comment]
I recall already telling you, but I'll repeat it, I've never packaged software before, so it will take a while before I have a decent working environment and learn how this thing works.

I don't mind attribution at all, I just want the programs I use to work, you can make the change yourself if you want it done fast, otherwise here I'll take a couple of days or maybe more.

**Comment by sriemer** [comment]
Fine for me. Got a Xenial VM now running and also see the icon issue.

**Comment by 12345ieee** [comment]
I'm starting to understand what problems the debian maintainer had.
Bear in mind it's the first time I do this sort of thing.

Your `make dist` that builds the exported directory probably doesn't copy some file.
Because of this `make check` runs in the main source dir but refuses to run in the built dir.
Checks are not performed if you don't make a binary package, so you don't have this problem for the PPA. Somehow the PPA build system isn't bothered by this.

When I tell debuild to ignore the checks, it works, I'm currently testing it.

You can track the changes I made from my fork:
https://github.com/12345ieee/scanmem/tree/packaging
but is mostly dumb stuff and the commits badly need a rebase.

**Comment by 12345ieee** [comment]
Ok, definitely reproduced the icon problem.
The 0.14+ installer simply does not copy them at all in the right folders (and doesn't even call the cache updater).
This happens both with my build and your PPA.

**Comment by 12345ieee** [comment]
Ok, if anything else if fine you can grab the fix at
https://github.com/12345ieee/scanmem/tree/fix-icon-not-showing

No particular attention was given to commit messages, as you wanted to rework them anyway.
Most of the commits are stuff needed to build and test the package, built over your ubuntu-ppa branch, upstream needs only commit 555a217.

If you don't want to get the patches from my repo, I'll send them to you by email.

Keep in mind that `make check` fails when run on the packaging directory, sign that something isn't quite right with the tarball building process, but as I don't know automake I cannot point the error.

**Comment by sriemer** [comment]
I'm providing v0.15.5 as version 0.15.5-0sp1.20160307r47fba now in my game cheating PPA. I've fixed the installation of the icons. This time they are actually installed to /usr/share/icons/hicolor and also `gtk-update-icon-cache` is run from a postinst script. But lintian reports errors because of providing the Python cache files within the package. Any ideas how to fix this?

**Comment by 12345ieee** [comment]
@sriemer I've not looked at this in a while, as I had other things to do.
I've seen you included nothing of the changes in my fork, were there some issues with my commits (apart the message)?

The fix for Lintian is in 8cddaffa0cbf0ddd346522d3a34f2d1f710a6736
The full fix for icons is in 555a217febffde2107ae607b8a9f87a2ab5afa65 and 0916d0f3b04609d88bdeb89a0297bfa987acef90 splitted in upstream part and Debian part.
I found out that you don't even need to call `gtk-update-icon-cache` if you install them correctly.

Let me know if you want the patches in another way.

**Comment by sriemer** [comment]
This just became important and is becoming severe soon.
There is the chance to get this into Debian Stretch now. So this has highest priority for me now.
See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822604

**Comment by sriemer** [comment]
I've finished the packaging for 0.15.7-1 for Debian stretch/sid and sent it to Emilio. This release candidate is now also available from my Ubuntu PPA as 0.15.7-0sp1 at https://launchpad.net/~s-parschauer/+archive/ubuntu/game-cheating.

It would be great if others would test this as well.

My changes compared to 5 years old 0.13-1:
https://github.com/sriemer/scanmem-debian/commits/master

My new Ubuntu PPA source location:
https://github.com/sriemer/scanmem-debian/tree/ubuntu-ppa

The Debian unstable source location:
https://github.com/sriemer/scanmem-debian/tree/source

**Comment by 12345ieee** [comment]
I am running debian unstable and I've installed your package from the ubuntu PPA.

I can readily tell you there are issues with Game Conqueror's "loading bar" under gtk 3.20, but a ton of things have problems under gtk 3.20, so don't even waste time on that.
The bar is fine under 3.18.

There are still the issues with the "Manually add an entry" menu and with resizing, I had already reported both here: https://github.com/scanmem/scanmem/issues/149#issuecomment-171916851

**Comment by sriemer** [comment]
@12345ieee Thanks! Most important is Debian stretch (testing) for now. This is why I've set up VMs for amd64 and i386 for that. I haven't seen any progress bar issues there with GTK 3.18.

The issues with the "Manually add an entry" and the resizing are not Debian specific. The resizing bug already has a GitHub issue with #74. Creating a new GitHub issue for the "Manually add an entry" bug would have been the way to go. I can reproduce it now. So I'll create the issue for that.

These two bugs aren't blocking us from releasing 0.15.7-1 on Debian. Otherwise, more people would have complained about these.

**Comment by 12345ieee** [comment]
I actually rolled the GTK back to 3.18 because other programs were bothering me and GC is perfectly fine.
As far as scanmem/GameConqueror is concerned I basically run Debian testing.

I know neither issue I reported is Debian-specific, I'll open/refresh a issue for each of them.

**Comment by sriemer** [comment]
Thank you very much! I'll look at them for v0.16 and hope that I can fix them. For now highest priority is still on getting 0.15.7-1 into Debian testing but now I depend on the release manager Emilio.
If bug priority increases, then I can also ask a different Debian maintainer to do the upload. I know three of them from my former work. I'll be working at SUSE from next week.

**Comment by 12345ieee** [comment]
General remainder:
Debian gave us a "before the end of the year" deadline to get into Stretch, we're getting closer to it.

From the v0.16 milestone we only have #186 which is hard blocking this (together with other minor issues, some of which have a fix in the review pipeline).
@sriemer , how are things going with #186 ?

Sorry for annoying everybody and reviving a months-old issue.

**Comment by sriemer** [comment]
Debian Stretch release schedule and therefore 2017-01-05 is the hard deadline for this bug.

**Comment by sriemer** [comment]
I've released v0.16 and submitted the packaging yesterday to Emilio. I hope to get this finally uploaded and fixed.

**Comment by sriemer** [comment]
Would be nice to get this into Ubuntu 17.04 Zesty Zapus released in April 2017 as well this way.

**Comment by sriemer** [comment]
We are reaching the Debian Stretch deadline 2017-01-05 very soon. I'd be really pissed off if we miss it.

@coolwanglu: You are the Debian package maintainer for scanmem. Please upload my package from https://github.com/sriemer/scanmem-debian ASAP! TIA

**Comment by 12345ieee** [comment]
So, looking at the latest Debian requests (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822604#67), they seem all "cosmetic-only". Hard deadline is also postponed to 05/02/2017.

Considering the is a 10 day transition period now from unstable to testing (I don't know if it compounds with the 7+ days the package is predicted to spend in NEW) we are still in a moderate hurry.

Do you need any help with this, @sriemer ?

**Comment by sriemer** [comment]
Nope, all done. At least somebody finally responded.

**Comment by sriemer** [comment]
Vincent Bernat accepted the new scanmem Debian package `0.16-1` into Debian `unstable`. 🎉 
@12345ieee: Thank you very much for your help! Very much appreciated!
The package will hopefully find its way into `testing` and Ubuntu as well. So closing for now.

**Comment by sriemer** [comment]
Debian package 0.16-1 has been migrated to testing (Stretch). 🎉

**Comment by 12345ieee** [comment]
On this topic, releasing a v0.16.1 (or a Debian 0.16-2 with some patches) before roughly the 20th would get it in Stretch before the freeze.
@sriemer , if you have time, you might want to.

**Comment by sriemer** [comment]
I would need a sponsor who does the upload. Changes are rather minor. I'm not sure if we can really get it there in time and if it's worth the effort now. I'm also busy with something non-SW related right now which limits my leisure time.
