### ISSUE TITLE
autogen.sh  error

### ISSUE THREAD

**Issue by yz254316702** [scanmem/scanmem#151]
An error occurred while running autogen.sh  :
You should update your 'aclocal.m4' by running aclocal.
How to solve this???

**Comment by sriemer** [comment]
I usually ignore it or run aclocal again. But okay, I'll look at it.

**Comment by sriemer** [comment]
It's coming from intltoolize called at the end. It is possible to run libtoolize before aclocal. Also autoconf should be called before automake. There should be more transparency what the script is doing. I know now how to improve the script and will do a patch. Thanks for reporting!

**Comment by sriemer** [comment]
Ignoring the warning has been the correct action until now. The fix is committed. So closing.

**Comment by sriemer** [comment]
%s/intltool/intltoolize/g. I've forcefully pushed to fix the descriptions. Please use `git fetch; git reset --hard origin master` in case you've pulled or cloned already.
