### ISSUE TITLE
Regression in icon install target breaks build

### ISSUE THREAD

**Issue by anthraxx** [scanmem/scanmem#155]
Regression introduced by: a2b1405c209e03e842d49f7c36e9a369b9e55ea9

in fact this is an issue as install target should not update global directories as it can and will be used by non-root accounts for building packages

    make[4]: Entering directory '/build/scanmem/src/scanmem-0.15.5/gui/icons'
    if [ -n "which gtk-update-icon-cache" ]; then \
        gtk-update-icon-cache /usr/share/icons/hicolor; \
    fi
    gtk-update-icon-cache: Failed to open file /usr/share/icons/hicolor/.icon-theme.cache : Permission denied

in fact it should *not* do this on install, its either responsibility of the user to invoke that target manually or the responsibility of a packager to invoke that in a install step that has root access.
It should never be invoked as default on install target as this introduces a regression when packaging with non-root accounts into a DESTDIR

**Comment by sriemer** [comment]
Fixed by 6a5e2e86ebacd87bed132dea354433d722081abf for v0.16 and 16a736a06f650d3aae5f92ec0a114cc0a9522825 on top of v0.15.5.
This would be worth releasing v0.15.6 with the fix immediately. Please confirm that the fix is fine, then I'll release it as v0.15.6.

**Comment by anthraxx** [comment]
==> Finished making: scanmem-git 0.15.5.742.16a736a-1 (Sat Mar 12 13:19:02 CET 2016)

I can confirm 16a736a (stable branch) works fine. Also the master branch seems to be fine 6a5e2e8

**Comment by sriemer** [comment]
Thank you very much for reporting and testing! I've released v0.15.6 as a hotfix so that distros don't have to apply the patch on top.

**Comment by anthraxx** [comment]
thank you very much for your fast and great work, still very much appreciated and noticed! also thx for the hotfix release, not something all upstream does!!! :+1:
