### ISSUE TITLE
Review man pages and documentation e.g. for ranges feature

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#157]
Man pages and documentation have to be reviewed to check if all current features and implementations are described correctly.

**Comment by sriemer** [comment]
The `write` command help in scanmem doesn't show that also data type `string` is possible.

**Comment by sriemer** [comment]
I've cleaned up the source tree, fixed the links to the scanmem project and noticed that deprecated auto-generated files have been checked in. So I removed these.

**Comment by sriemer** [comment]
I'm working on the manpage scanmem.1 right now. It reflects a really old state. So I'm completely reworking/updating it to the current state right now.

**Comment by 12345ieee** [comment]
Once you're done with that you may also want to have a look at the main repo [README](https://github.com/scanmem/scanmem/blob/master/README).

I fixed a typo and made minor improvements in ca8dec549a838fb90f893ef0a6a6667edf27ce81

A warning that scanmem/GC needs root access (unless you do something with ugtrain, I guess) and why it needs it would be appreciated.

**Comment by sriemer** [comment]
Sorry, I needed some tries to get the new README straight. Please review.

**Comment by sriemer** [comment]
I think we're through with this. So closing.
