### ISSUE TITLE
Wextra against the codebase

### ISSUE THREAD

**Issue by 12345ieee** [scanmem/scanmem#162]
I tried compiling scanmem with the `-Wextra` compiler flag, to get all the possible warnings.

There were a huge amount of unused variables and signed-unsigned comparisons, but I don't think these are a problem in any meaningful way.

The only ones that remained are:

```
handlers.c: In function ‘handler__set’:
handlers.c:88:21: warning: variable ‘seconds’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
     unsigned block, seconds = 1;
                     ^
handlers.c:91:10: warning: variable ‘cont’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
     bool cont = false;
          ^


scanmem.c:59:5: warning: missing initializer for field ‘reverse_endianness’ of ‘struct <anonymous>’ [-Wmissing-field-initializers]
     }
     ^
In file included from scanmem.c:35:0:
scanmem.h:99:24: note: ‘reverse_endianness’ declared here
         unsigned short reverse_endianness;
                        ^
```

while I have no clue what the 1st one means, for the second one I'm not familiar with the codebase to tell if `reverse_endianness` is always initialized externally before use, but you may want to check that.

**Comment by sriemer** [comment]
There is no fork. So the 'longjmp', 'vfork' stuff can be ignored.

Thanks for reporting the last one! This might indeed cause a real issue in future. I really spent too much time already with fixing the endianness stuff. I'll do the commit for this.

**Comment by sriemer** [comment]
Sorry for the delay! I just started my new job at SUSE and I had to spend quite some time with traveling and learning new stuff for the job.

**Comment by sriemer** [comment]
Fixed. So closing.
