### ISSUE TITLE
gui: Drop superfluous float rounding ComboBox

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#174]
The [TODO](https://github.com/scanmem/scanmem/blob/master/TODO) mentions the need to add float rounding methods. This might explain the superfluous "Round Type" combo box. We definitely don't need that as we have ranges. So the ComboBox should be dropped.

I'm not doing this now as this might conflict with the work of @12345ieee. But we shouldn't forget about this.

**Comment by 12345ieee** [comment]
I confirm it's easy to remove, but please do not do it.

Talking about my patch series, I've not had time to fix it, but I've opened a PR at #176 so we know what we're talking about.

I guess I'll include this fix, too, when that's ready.
