### ISSUE TITLE
ANNOUNCE: New scanmem Contributors team

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#175]
I'd just like to announce that we have a new team in the scanmem organization.

We already have three owners of scanmem in the Owners team.
Now I've created the "Contributors" team. You don't get committer rights in that team but it makes it easy to be assigned to issues or to assign yourself to issues so that we know who's working on what.

Just let me know if you would like to be invited.

**Comment by sriemer** [comment]
Of cause you also belong to the scanmem organization then and people visiting your profile will see that you belong to us. :smile:

**Comment by 12345ieee** [comment]
I accepted the invitation, thank you.

**Comment by bkazemi** [comment]
I'll go ahead and throw my hat in. I see a lot of potential in this program and I could pull some weight in (maybe) adding native BSD support :-)

**Comment by sriemer** [comment]
Native BSD support sounds great. I started with it some time ago but then I noticed more and more issues to get it done and I didn't have enough time for it any more. Maybe I should have better committed some parts of it first.
See: https://github.com/sriemer/scanmem/commits/freebsd

FreeBSD support won't go into v0.16 but for v0.17 it would be great.
I've sent the invitation.

**Comment by sriemer** [comment]
Watchers informed. So closing.
