### ISSUE TITLE
Distros warn about libscanmem packaging together with scanmem - LGPL required

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#184]
Distributions like Debian or openSUSE warn about the packaging of libscanmem together with scanmem under the same license (GPLv3). Also developing other front-ends than GameConqueror should be possible. So my suggestion is to provide a separate libscanmem1 package under LGPLv3.

Otherwise, there is no chance to get `v0.16` into Debian testing or openSUSE Factory.

@coolwanglu: Are you fine with the license change for libscanmem and the separate package?

**Comment by coolwanglu** [comment]
I'm fine for all the modifications I made. How about other contributors?

**Comment by 12345ieee** [comment]
I have no stakes in this, but I'm curious: why the LGPL?
Do you want to encourage building closed source projects over 'libscanmem'?

**Comment by sriemer** [comment]
LGPL because it's usually used for libraries. It's unlikely that somebody would try to create a proprietary front-end for libscanmem. Other open-source licenses might be incompatible otherwise if libscanmem forces users of it to use GPLv3.

Btw.: I'm intending to create a GameConqueror fork which runs the target process itself by integrating ugtrain as well. That would address the weakness of GC requiring root privileges and not being able to use preloading.

**Comment by 12345ieee** [comment]
> LGPL because it's usually used for libraries. It's unlikely that somebody would try to create a proprietary front-end for libscanmem. Other open-source licenses might be incompatible otherwise if libscanmem forces users of it to use GPLv3.

Makes sense.
 
> Btw.: I'm intending to create a GameConqueror fork which runs the target process itself by integrating ugtrain as well. That would address the weakness of GC requiring root privileges and not being able to use preloading.

I've looked at the ugtrain page, it's desolated. I guess you really need a gui to attract people.

Forking GC in this state might not be the best choice for you (unless ugtrain's gui needs are vastly different from scanmem's), as syncing the improvements back and forth between ugtrain/scanmem will get unreasonable fast.
You'd be probably better off decoupling GC from scanmem (and keeping the new repo as a submodule in both repos) and teaching him to drive both ugtrain and scanmem.
