### ISSUE TITLE
libscanmem needs a clear separation from scanmem

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#186]
The file `scanmem.h` contains all the common and global stuff but not all public interface definitions. This way no other e.g. C/C++ based front-end can be compiled.
`scanmem.h` should only contain the public interfaces of libscanmem so that a `libscanmem-dev` or `scanmem-devel` package can be created. The common and global stuff should be moved to a new header file `common.h`.

**Comment by 12345ieee** [comment]
Talking about the public API, I don't think `void reset_scan_progress()` should exist at all.

`scanmem` already resets the scan progress at the start of every scan and never checks the variable itself, so the function offers absolutely no functionality, apart screwing the scan counter, if called mid-scan.

**Comment by sriemer** [comment]
Some parts done in `v0.16`. Some more work to do for `v0.17`.

**Comment by sriemer** [comment]
`v0.17` should come with a completely cleaned up public API and `libscanmem2` then.
