### ISSUE TITLE
GC displays a maximum of 1000 memory addresses

### ISSUE THREAD

**Issue by davidebeatrici** [scanmem/scanmem#196]
Version: Latest, compiled from sources.
The memory addresses are displayed only if they are less than 1000, this is a big limitation when scanning "large" processes.

**Comment by 12345ieee** [comment]
I know it seems ridiculous, but if you raise the limit (https://github.com/scanmem/scanmem/blob/master/gui/GameConqueror.py#L57) the treeview starts taking time for each operation.

At 10k entries, scanning, sorting or adding to the cheatlist takes seconds on my laptop.

I was considering if displaying the first 1k entries in any case, as getting 1100 matches and seeing nothing is definitely annoying.

**Comment by davidebeatrici** [comment]
I think that the best solution would be to add an option to manually set the limit :wink:

**Comment by korcankaraokcu** [comment]
If it's going to take more than several seconds to update the entire table, being able to manually set the limit won't help since you won't be able to use GUI at all. My suggestion would be same with the Cheat Engine's solution: Update only visible part of the table. With this, you'll be able to store even 1million results in the table

**Comment by davidebeatrici** [comment]
Decreasing the limit would be useful when a user sees that the GUI gets stuck when scanning, he needs to reboot the program indeed.
I tried to do a scan with the limit set to 100.000 and the program was as fast as with the original limit of 1.000.
I agree with the Cheat Engine's solution.

**Comment by sriemer** [comment]
For what do you need that? 1000 matches means you're not even close and can't try them all out.

**Comment by davidebeatrici** [comment]
That's untrue: when you scan to find the player position, it's almost impossible to go under 5000-10000 values in certain games, because a user usually searches by changed and unchanged values. Only a few games let you know your coordinates.

**Comment by korcankaraokcu** [comment]
Most of the time only 1 address is real(used in calculating player's location). So, if scanning again doesn't help, just try to change the addresses by small groups. By this way, you'll eventually find the correct address. I have even written aimbots with CE at past and I don't remember being in a situation where I have to change 10000 addresses at the same time. It'd be very dangerous anyways, I mean, good luck at setting 10000 addresses to same value while not getting segfault or stack corruption :smile:

**Comment by davidebeatrici** [comment]
Well... my objective is just to get the player's coordinates, which for most 3D games are an array of 3 memory addresses with float values (X, Y and Z).
The problem is that usually there are a lot of unrelated values that change when the players moves; by a lot I mean something in a range from 1000 to 10000 or even more. :wink:

**Comment by sriemer** [comment]
Isn't it easier to disassemble the program, to look for API functions requiring 3D coordinates and setting some breakpoints with a debugger like gdb?
There is even the free interactive disassembler [Frida](https://github.com/frida) now.
Games usually use a lot of libraries. Functions to draw something definitely require coordinates. You could also look for usage of a certain texture.

**Comment by davidebeatrici** [comment]
I could disassemble the program, but it is much simpler using Cheat Engine;, as it displays a maximum of 10.000.000 values, which are far more then the needed ones. 1000 is really a too low limit; I understand that it can be changed, but only by editing GameConqueror.py and probably only a few people know about this.
Also, as @12345ieee said: if there are 1010 values, for example, the memory addresses list is empty, while it should show all of the memory addresses except the last ones, to match the limit (like in CT).

**Comment by 12345ieee** [comment]
The slowness is not in grabbing the updated values from memory (because we update only the visible entries, we're not crazy), but it's in the display interface itself.

To be more clear, the Gtk libraries' implementation of displaying a list is slow, at least the default one (TreeView).
You see this when doing operations on the entire list, like displaying the results of a new scan, or sorting the whole list.
I am not a Gtk guru, so I don't know of better ways.

Adding a menu to configure the max number is out of question for v0.16 .
Displaying always at least 1k even if you have more is simple enough that could be added for v0.16

**Comment by davidebeatrici** [comment]
Oh, I didn't know that it was entirely GUI related.
Well... for now I think that displaying at least 1000 memory addresses is enough.

**Comment by 12345ieee** [comment]
After some profiling:

* Displaying the tree costs 0.1 ms -> negligible
* Filling the tree costs 0.1 ms/entry (max 100 ms currently), 95% of which is in `scanresult_liststore.append()`, rest in string magic to parse `libscanmem`
* Getting the lines from libscanmem costs 3 μs/entry (max 3 ms currently)

Conclusion: Gtk's ListStore is slow, but maybe there is some way to speed it up.
Getting results from `libscanmem` is surprisingly slow, too, 3 μs just to copy ~100 bytes around is pretty bad, even for python.

**Comment by sriemer** [comment]
Maybe we could try changing the `libscanmem` interface to transfer binary data in C structures + array. Then we wouldn't have to do string parsing. A GtkTreeStore likely helps here as you can pass an array to it.

**Comment by 12345ieee** [comment]
The `ListStore` can be made faster, by using some obscure Gtk appending method.
I got a complete insertion (string magic + ListStore append) down to 15 μs/entry, with the string parsing taking ~4 μs/entry.

Conclusion: I'll open a PR for my method change and raise GC's displayed limit to 10k for v0.16
For v0.17 we'll try to improve `libscanmem`'s format, to cut both on string magic and data passing.

@sriemer , please state if you have problems with this plan.

**Comment by korcankaraokcu** [comment]
Just wondering, what's wrong with cheat engine's solution: Just updating the visible part? Even with the worst algorithm, user won't notice the difference because only 10-20 entries will get updated.

**Comment by 12345ieee** [comment]
You missed my comment: https://github.com/scanmem/scanmem/issues/196#issuecomment-236627943

**Comment by sriemer** [comment]
@12345ieee: Go for it. I'm awaiting your PR. :smile:

**Comment by 12345ieee** [comment]
OF COURSE, I HAVE PYTHON 2 VS 3 PROBLEMS, GODDAMN LONGS VS INTS.

IMHO I found a pyGI 3 bug with int's treatment in ListStores, I'm waiting for an answer on the bug I opened: https://bugzilla.gnome.org/show_bug.cgi?id=769532

**Comment by 12345ieee** [comment]
My preliminary commit for this is  12345ieee/scanmem@65353bc
7x faster on python2
3x faster on python3, waiting for the gtk guys to answer

Total # of entries has been raised to 10k, as we can afford it.

@sriemer : everything I have is behind #194 , I need that merged first (I know I should make independent branches, but there's so many bugs to fix that it's just unfeasible).

**Comment by 12345ieee** [comment]
The pyGobject guys have answered me.
I have a nice 7x gain on py2 and 5x gain on py3.

Everything is already included in the `gui-next` branch.
