### ISSUE TITLE
handlers: is POINTER_FMT necessary?

### ISSUE THREAD

**Issue by bkazemi** [scanmem/scanmem#199]
There is a macro defined here:
https://github.com/scanmem/scanmem/blob/master/handlers.c#L74-L84
that determines the field width for a pointer. However, C99 has its own format spec `%p` to display pointers. Is there a need for this block?

**Comment by sriemer** [comment]
The whole code should be converted to `intptr_t` or `uintptr_t` like ugtrain uses. I've started with it once but it touches all code locations and needs thorough testing. `%p` requires a `void *` for addresses but you can't do calculations with `void *`. This is why it is the wrong data type for memory addresses.

**Comment by sriemer** [comment]
`POINTER_FMT` also sets the spacing for the memory addresses printed at the `list` or `lregions` command. So yes, it is required.

**Comment by bkazemi** [comment]
Ah, I see. Might be a bit cleaner to check `ULONG_MAX` against a hex number. Anyways, closing.
