### ISSUE TITLE
Feature Request: Keyboard shortcuts

### ISSUE THREAD

**Issue by calculuswhiz** [scanmem/scanmem#202]
GTK3 has the "key_press_event" function, so I figured, why not have all of the buttons on the GUI have a keyboard shortcut assigned to it? (e.g. F1 to select process, F5 to refresh, etc.) For those of us who like to keyboard everything, I think this would be a neat enhancement.

**Comment by 12345ieee** [comment]
Well, here it depends on users' expectations.
E.g. I expect F1 to open some form of help, F5 to 'refresh' something, F11 to fullscreen and so on.

If you have obvious pairings, please say, but I'm not keen on introducing random keygrabbing on the Fn keys.

Having, say, `Ctrl+S` as a shortcut to the save cheat button seems much better to me than, say, F3.

**Comment by calculuswhiz** [comment]
Ah, ok. I see.  I didn't mean that it had to be the function keys. Though I guess it can be a little annoying if it were...  What about with a CTRL modifier using GTK's Accelerator Groups then? E.g. CTRL+F for search, CTRL+R for reset.

**Comment by 12345ieee** [comment]
`CTRL+letter` seems a better choice.

I'm assigning this for v0.17, unless you want to provide a patch yourself.
A list of good hotkey choices (`CTRL+R` for reset is a good idea) would be appreciated.

**Comment by calculuswhiz** [comment]
How about the following for now?
- `ctrl+r` for reset. (Seems that's agreed upon.)
- `ctrl+f` for process selection. Since that's usually associated with finding stuff.
- `ctrl+<enter>` for search? Not sure on this one, considering `<enter>` already does the job if the textbox is highlighted, which you can do easily if the next suggestion works.
- `ctrl+k` to focus on the search box. Like when you want to focus the search box in Firefox or Thunderbird.

Naturally the tooltips will show the keys.

And yes, I'd be willing to make a patch.

**Comment by calculuswhiz** [comment]
Ok. I made a pull request.

**Comment by 12345ieee** [comment]
Let's move the whole discussion to @calculuswhiz 's PR #206 .
Closing this.
