### ISSUE TITLE
[Bug] 'msgid' and 'msgstr' entries do not both end with '\n'

### ISSUE THREAD

**Issue by calculuswhiz** [scanmem/scanmem#205]
When building, I got this error:

    ja.po:66: 'msgid' and 'msgstr' entries do not both end with '\n'
    /usr/bin//msgfmt: found 1 fatal error

**Comment by calculuswhiz** [comment]
To fix this, I changed line 65 in `ja.po` to have a newline after it:

    " For string: enter the string directly\n"

I also did the same with ru.po.

**Comment by calculuswhiz** [comment]
Never mind. I'll just pull request this.

**Comment by ramAdam** [comment]
Thanks @calculuswhiz you saved me time.

**Comment by sriemer** [comment]
Right, commit 9942e3a9bf28e77258261e58e0b10b3402f9b608 from @12345ieee  broke it. This is what happens if someone doesn't care for updating the translations as well.

**Comment by 12345ieee** [comment]
e74a954da29d7f2d120440504af7f962c29b7ebe fixes it, @sriemer .
If you prefer splitting the fix from the general translations update, go for it.

**Comment by sriemer** [comment]
A build failure is a serious issue. I can't review all these commits to that point first. I'll do the fix myself.

**Comment by sriemer** [comment]
I receive too many scanmem notifications recently. For important stuff like this feel free to send me a separate e-mail.
Fixed. So closing.

**Comment by sriemer** [comment]
I'm seeing this bug in our traffic graph from time to time.
For the record: The fix commit is 2309663c788937c1b2fb04af47354b55fcf7d1b3.
