### ISSUE TITLE
gui: Regression: Type in cheatlist treeview not correct when manually adding cheats

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#212]
![cheatlist_type_broken](https://cloud.githubusercontent.com/assets/1803210/18415760/f9e1db86-77fd-11e6-8ae1-016e9d0e9196.png)

Commit 8efffac315f2efcd69fd3290387d9f7d627a2e4a ("gui: Change the ComboBox's to ComboBoxText's") introduced a regression that the data type is not displayed correctly when manually adding a cheat. What should be `i32` is displayed as `i` instead.

When being attached to a process, then also a traceback is triggered.

````
Traceback (most recent call last):
  File "/usr/share/gameconqueror/GameConqueror.py", line 1045, in data_worker
    newvalue = self.read_value(addr, typestr, value)
  File "/usr/share/gameconqueror/GameConqueror.py", line 1070, in read_value
    return self.bytes2value(typestr, self.read_memory(addr, self.get_type_size(typestr, prev_value)))
  File "/usr/share/gameconqueror/GameConqueror.py", line 1079, in read_memory
    self.backend.send_command('dump %s %d %s' % (addr, length, f.name))
TypeError: %d format: a number is required, not NoneType
````

**Comment by 12345ieee** [comment]
Oh my...
This is Ubuntu 14.04, right?

**Comment by sriemer** [comment]
Nope, openSUSE Leap 42.1 with GTK 3.18 on KDE.

**Comment by 12345ieee** [comment]
Ok, the issue is fixed a few commits along the way, which explains why I didn't see it.

I have a couple broken states in that commit and in 61d71f18b43c71e1c5219fc931b2e2559892c7e5 , sure a careless rebase.

I'll push a fixed `gui-next` asap.

**Comment by sriemer** [comment]
Thanks! Please create a fix on top of `master` so that I can push it there.

**Comment by 12345ieee** [comment]
Done.
You want the first commit of `gui-next`.
The issue was fixed in "gui: Add configurable length for string/bytearray" originally, I simply moved the line to the new commit.

Sorry for the dumb problem.

**Comment by sriemer** [comment]
Applied. Thanks!
