### ISSUE TITLE
GUI hangs when adding address to cheat list manually

### ISSUE THREAD

**Issue by avseredyuk** [scanmem/scanmem#213]
1. Select any process.
2. Add any valid address to cheat list manually without any search work.
3. Have frozen GUI.

_Linux Mint 17/KDE
GameConqueror 0.16~pre_

**Comment by 12345ieee** [comment]
Yes, this was reported a couple hours ago by @sriemer in #212 .
It'll be fixed in f4be63825d7467c7a557361664374b916a318300 as soon as it lands on master.

Closing because duplicate.
