### ISSUE TITLE
gui: "Manually add cheat" dialog questions

### ISSUE THREAD

**Issue by avseredyuk** [scanmem/scanmem#215]
Hi.

Why is there TAB_FORWARD reaction while hitting `Enter` at `Address_Input` & `Description_Input`? For this stuff I guess we have a Tab button. I can imagine that there was a point of this thing - navigating through all the fields of the dialog only with Enter. But `Type_ComboBoxText` breaks it, so we have to use Tab.
From my point of view, it would be better to call `ConfirmAddCheat_Button_clicked_cb` handler.

**Comment by 12345ieee** [comment]
UX decision, it's debatable.

Anyone has strong feelings in one way or another?

**Comment by sriemer** [comment]
Both Enter and Tab jump to the next text box. The type is selected with Enter and then you have to use Tab to go to the next field from there, yes. So use Tab right away, yes. But Add shouldn't be the action upon Enter. So implementation is okay like it is right now.
