### ISSUE TITLE
scanmem root warning needs to be adjusted

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#218]
People still get confused by the message:

`error: *** YOU ARE NOT RUNNING scanmem AS ROOT, IT MAY NOT WORK WELL. ***`

My suggestion is to replace it with something less severe like:

`warning: Run scanmem as root if it doesn't find a variable. See "man scanmem" for details.`

**Comment by bkazemi** [comment]
Agreed. It is also more specific.

**Comment by 12345ieee** [comment]
Yes, also, avoid showing it with `--help` or `--version`.
I made some changes on this direction in #177 .

**Comment by sriemer** [comment]
Final message:

`warn: Run scanmem as root if it doesn't find a variable. See scanmem man page.`

I'll put it even further down in the code right before executing the `reset` command.

**Comment by sriemer** [comment]
I've just checked Ubuntu 14.04 again without root privileges. You'll notice that you need root privileges there because of
`error: failed to open maps file /proc/2138/maps`

````
$ ls -l /proc/2138/maps
-r--r--r-- 1 root root 0 Oct 16 13:40 /proc/2138/maps
````

But I also remember some versions where you can access some memory regions but others (the important ones) are hidden from you.
