### ISSUE TITLE
gui: Hexview still doesn't work properly with Python 3

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#220]
Strings in memory can be interpreted by the `u()` function as an escape sequence. This means that e.g. the string "\n" is not interpreted as the byte sequence 5C 6E but 0A instead. The displayed data becomes shorter and this can cause a Python exception like this:

````
Traceback (most recent call last):
  File "/usr/share/gameconqueror/GameConqueror.py", line 610, in scanresult_popup_cb
    self.browse_memory(addr)
  File "/usr/share/gameconqueror/GameConqueror.py", line 849, in browse_memory
    self.memoryeditor_hexview.payload = misc.u(data)
  File "/usr/share/gameconqueror/misc.py", line 206, in u
    return codecs.unicode_escape_decode(x)[0]
UnicodeDecodeError: 'unicodeescape' codec can't decode bytes in position 992-993: truncated \uXXXX escape
````

**Comment by sriemer** [comment]
The byte sequence passed to `u()` is "\\n" but it still gets interpreted as 0xa.

**Comment by 12345ieee** [comment]
I'm looking into this.

**Comment by 12345ieee** [comment]
Fix is at the tip of gui-next.

**Comment by 12345ieee** [comment]
I had to force-push, as I discovered an issue with the previous "fix py3 strings" commit, related to this hexview issue.

Now, @sriemer , you have both commits at the beginning of the branch, ready to be merged.
