### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by 12345ieee** [scanmem/scanmem#221]
@sriemer , do we even use it anymore?
I tried running it, and it crashes horribly, because it's >7 years old and scanmem is radically different now.

**Comment by sriemer** [comment]
We don't use it. Tests are mostly manual. Needs a full rewrite.

**Comment by 12345ieee** [comment]
So, I propose elimination of the whole folder.

git will keep it anyway and I have a particular hate for clutter.
