### ISSUE TITLE
Selector of scaned memory type in PID

### ISSUE THREAD

**Issue by mdziczkowski** [scanmem/scanmem#222]
Would it be possible that you could add into code a selector of type with would be checked the memory of (for example: flash, global, etc.)? 

For now scanmem scans the whole memory of attached process and that why it's giving too many results, with makes it hard to find the interesting part of memory. The selector (or limiter) would be very helpfull in faster operating

**Comment by 12345ieee** [comment]
There is already.
The GUI has a slider and the CLI has the `region_scan_level` option.

**Comment by mdziczkowski** [comment]
> the CLI has the region_scan_level option

I don't think I saw this mentioned in the Linux manual (or I had misseen it somehow @.@ )

**Comment by sriemer** [comment]
Relevant man page part:
````
option name value

Change options at runtime. E.g. the scan data type can be changed.  See `help option` for all
possible names/values.
````

The man page is already quite long. We can't put everything in there and have to reference to the command line help within scanmem.

Scanmem doesn't scan everything by default. The default is "heap, stack executable and bss only". The bss regions can be really big. Check the region type of bss regions. Usually only the bss region with type "exe" is interesting. Experienced users can also use `lregions` command followed by the `dregion` command in a way to scan only in the region where they know that the variable is stored.

Example:
````
0> lregions
...
[ 2]       eab000, 9142272 bytes,  heap,       eab000, rw-, [heap]
...
0> dregion !2
0> lregions 
[ 2]       eab000, 9142272 bytes,  heap,       eab000, rw-, [heap]
````

Now it's possible to only scan on the heap.

**Comment by sriemer** [comment]
lregions example from warzone2100:

````
0> lregions
[ 0]       997000,     102400 bytes,   exe,       400000, rw-, /usr/bin/warzone2100
[ 1]       9b0000,    8777728 bytes,   exe,       400000, rw-, unassociated
[ 2]      1722000,  125984768 bytes,  heap,      1722000, rw-, [heap]
[ 3]     41444000,     655360 bytes,  misc,     41444000, rw-, unassociated
[ 4] 7f2278500000,   19922944 bytes,  misc, 7f2278500000, rw-, unassociated
[ 5] 7f2279830000,   20512768 bytes,  misc, 7f2279830000, rw-, unassociated
[ 6] 7f227abed000,    4259840 bytes,  misc, 7f227abed000, rw-, unassociated
[ 7] 7f227affd000, 2147483648 bytes,  misc, 7f227affd000, rwx, unassociated
...
````

The interesting "power" value is stored as static memory value in region 1 which is the bss region of the executable. Region 7 is 2 GiB in size and doesn't belong to a library. So it has been mmap()ed directly. Must be game graphics. I always have to exclude the 2 GiB region from the search although we've improved scan performance in v0.15.x and v0.16 quite a lot.

**Comment by sriemer** [comment]
We might think of making `region_scan_level` 1 the default. I've already cared in `maps.c` for including the exe bss region there.

Looks like this:
````
0> lregions
[ 0]       997000,   102400 bytes,   exe,       400000, rw-, /usr/bin/warzone2100
[ 1]       9b0000,  8777728 bytes,   exe,       400000, rw-, unassociated
[ 2]      204d000, 98631680 bytes,  heap,      204d000, rw-, [heap]
[ 3] 7ffde5602000,   290816 bytes, stack, 7ffde5602000, rw-, [stack]
````

**Comment by mdziczkowski** [comment]
@sriemer I play flash games thru browser and I meant it more as for example as following steps (example as abstract code):

1. pid 1215 (browser pid)
2. type flash (select to scan the memory region only of the loaded flash file)
...

**Comment by sriemer** [comment]
I have to reject that request. Write your own wrapper tool/script if you need such stuff. scanmem/GC won't know about special browsers or maintain such parts.
