### ISSUE TITLE
Too much memory usage and other effects while scanning

### ISSUE THREAD

**Issue by mdziczkowski** [scanmem/scanmem#223]
After attaching the process and starting to search for a value, scanmem and the attached browser process started to use too much memory and the browser and the system stopped to respond.

Please build in a memory usage limit into scanmem

**Comment by sriemer** [comment]
Please rather provide a test case. Might be possible that your browser process has a memory leak. Too much is relative. Please come up with real numbers.

**Comment by sriemer** [comment]
You should exclude extremely big memory regions from the search as it's unlikely that the variable you're looking for is stored in there. It is rather game graphics or videos mmaped into memory.

**Comment by sriemer** [comment]
Close all other browser windows!

**Comment by mdziczkowski** [comment]
@sriemer 
> Please rather provide a test case. Might be possible that your browser process has a memory leak. Too much is relative. Please come up with real numbers.
that will be hard to do because (as I typed) the system stop to response for the time of the scan

> You should exclude extremely big memory regions from the search as it's unlikely that the variable you're looking for is stored in there. It is rather game graphics or videos mmaped into memory.

I have attached only the pid of the browser, so I don't have any influence on what is scanned by the program

> Close all other browser windows!
I have only one browser window open

**Comment by 12345ieee** [comment]
@mdziczkowski , are you by chance using `snapshot` (or `?` in the GUI)?

**Comment by mdziczkowski** [comment]
@12345ieee I use CLI and unfortunatelly no because while scanning the system becomes inresponsive

**Comment by 12345ieee** [comment]
Can't help you here without precise numbers and a reproducible (**on >=0.15.8**) testcase

**Comment by sriemer** [comment]
I'm closing this as a user error. Scanmem is a tool for advanced users. So users should know about Linux memory management as well as the ELF file format and therefore know in which memory regions they'll likely find what they are looking for.
