### ISSUE TITLE
"loosing" the results by scanemem

### ISSUE THREAD

**Issue by mdziczkowski** [scanmem/scanmem#224]
While long scanning of browser in search of a value, I finally got able to get 2 results with the searched for value (2> ). After the searched value has changed, I typed the new one into scanmem and instead of showing it, scanmem returned : 0>, with shouldn't happen

**Comment by sriemer** [comment]
That means that the value you're looking for moved to a different memory location. Script engines constantly move variables around in memory, move them to different memory locations/regions. This is not the fault of scanmem and would require hooking to code parts of the script engine. So closing.

**Comment by sriemer** [comment]
Come back with a simple test program if you want to verify/debug this with variables where you know how they are stored in memory.

**Comment by 12345ieee** [comment]
This happens often with WebGL games.
Usually the variable stays in the same memory location for a while, then the game "resets" (e.g. you change level, go back to main menu, prestige, etc...) and you lose it.

As @sriemer says, as you don't have specific knowledge about the engine, there's nothing we can do here.
