### ISSUE TITLE
String/bytearray lengths

### ISSUE THREAD

**Issue by 12345ieee** [scanmem/scanmem#227]
* Is it really necessary to keep them inside each `value_t` (aka the "8 bytes in memory" struct) in `match_flags`?
* Is it really necessary to have them as 2 distinct integers? When are we ever using both? Should it be a union or a simple `length`?
* It strikes me as strange that a 'packed' union for extreme memory efficiency is thrown together with these 2 int16 that will never get fully used.

File in question is `value.h`, to rapidly check the definitions.

**Comment by sriemer** [comment]
Yep, only one of the 16-bit integers is used in `match_flags` as it is also a union. `value_t` is a tricky 64-bit value + 16-bit match flags structure. This is why I had to optimize zeroing of that structure in `zero_value()`. `memset()` is much more expensive than setting two integers to 0.

**Comment by 12345ieee** [comment]
Yeah, sorry about the noise, my mind parsed the union/struct thing badly.

Are you working on something? I was trying to fix #204 , progress is slow because I have to understand tons of code as I go along.

**Comment by sriemer** [comment]
I'm not working on anything right now.
