### ISSUE TITLE
scanmem: Differentiate "0 matches because of no scan" from "0 matches because of no matches"

### ISSUE THREAD

**Issue by 12345ieee** [scanmem/scanmem#229]
Title is a mess.

There are currently 2 meanings of the `0>` prompt in scanmem:
- No scan was performed, so we have 0 matches (`reset` dumps us back here)
- A scan was performed and found 0 matches

I would like the prompt to read differently in the 2 cases, what about `->` or `'space'>` for the first case?

**Comment by sriemer** [comment]
Sounds good. My vote is for ` >` in this case.

**Comment by 12345ieee** [comment]
`'space'>` it is then. I should be able to do this.

Now a public API question, should `vars->num_matches` be 0 in both cases or it's better to set it to an exceptional value (e.g. -1) in the first case?

**Comment by bkazemi** [comment]
Now that you mention it, I see no reason why `num_matches` should be signed. I say make it `unsigned long` and add a `bool` member if the distinction is needed for a more effective use of the memory.

**Comment by sriemer** [comment]
Changed my mind. "> " looked better while testing. This has been pushed. So closing. Thanks!
