### ISSUE TITLE
gui: Context menu issue at found addresses list

### ISSUE THREAD

**Issue by avseredyuk** [scanmem/scanmem#230]
It seems that some items of the context menu of the list of the found addresses reacts OK only when user selects the address via mouse. But when you select it using keyboard arrow buttons & context menu button the problem appears. Menu items "Browse this address" and "Scan for this address" use first item in list or last selected via mouse item.

**Comment by 12345ieee** [comment]
Seems you're right, it comes from the fact that the detection of which row is highlighted is a bit hacky (I'm not sure why) and doesn't update when using the Arrow buttons.

**Comment by 12345ieee** [comment]
Proposed fix is at the tip of `gui-next`, awaiting review.
@avseredyuk , feel free to test it by building from the `gui-next` branch.

**Comment by 12345ieee** [comment]
I found out that the cheatlist would have had the same problem (though less obvious).
I changed the commit to include the fix needed there, too, force-pushing to `gui-next`.
