### ISSUE TITLE
how can I increase game speed (called "speed hack" in Cheat Engine)?

### ISSUE THREAD

**Issue by hub2git** [scanmem/scanmem#233]
I'm playing http://www.kongregate.com/games/jarofed/get-a-little-gold, an "idle" game. How can I increase the speed that the game runs. Cheat Engine has something called speed hack. What does Game Conqueror have? thank you.

**Comment by 12345ieee** [comment]
This was already discussed in https://github.com/scanmem/scanmem/issues/65 and classed as `wontfix`.

Closing this one as duplicate.
