### ISSUE TITLE
Branches and tags

### ISSUE THREAD

**Issue by 12345ieee** [scanmem/scanmem#235]
Considering we're about to release, I have a request about tagging.

As of now, releases are tagged only in the stable branch.
This makes using `git describe` on master really inconvenient, because everything is referred to the ancient tag v0.15.4, before stable split from master.

@sriemer , could you consider bringing the tags to master, too?
Either using stable as an "advancing pointer" over master, or merging master into stable at each release, or rebasing master over stable at each release, whatever you like the most.

**Comment by 12345ieee** [comment]
Another is the even/odd system, in which at every release the minor version increments twice, so that the branches can be kept separated.
Stable would have the even numbers and master the odd ones.

**Comment by sriemer** [comment]
Usually only fixes should go into the stable branch/releases. All new features should go in the master branch and the 0.15, 0.16, ... releases. Lu Wang had a different opinion. So it ended up like this that also performance optimization and other stuff went in. Usually it should be like comparing v0.15 to v0.16 and releasing these versions more frequently.

The other thing is that distributions don't pick up and maintain patches as fixes. So we have to do new releases for them also for fixes. This is what the stable branch is about. We had to fix a lot in the past. I hope that this will become better with 0.16.x and earlier release of 0.17.

**Comment by sriemer** [comment]
Maybe we can do 0.15.y and 0.16.y stable branches like the Linux kernel does.

**Comment by sriemer** [comment]
With a merge window for features in the beginning of 0.17 it should be different from 0.16.y right from the start.

**Comment by 12345ieee** [comment]
I understand why the stable branch exists.
It's a tradeoff between maintainability and complexity and it's your decision to have it or not.

My point was on the relationship between master and stable, if you keep them completely independent you need to tag both.

So, for a detailed proposal, tag the new release in stable as 0.16, then tag master as 0.17 (in a commit in which you just change autotools versioning from the stable version).

As master evolves we will release 0.17.1 (a master tag). After a while we'll get enough fixes piled on stable that we'll want to release 0.16.1 (a stable tag), and so on.
At the release of 0.18 master is "promoted" to stable, a new master is created (tagged 0.19) and stable is deprecated (or kept around, depends what came to depend from scanmem stable).

**Comment by sriemer** [comment]
Yes, it is intended in a way like that. We can rename the current stable branch to 0.15.y if further stuff is requested for that and start a new 0.16.y branch as the new stable branch. The master should derive immediately as we will merge features first then.

**Comment by 12345ieee** [comment]
I'm sorry for being dense, once we have piled up 100 commits on master (not bugfixes, features), what do we release? We tag master as 0.17.y and release that?

**Comment by sriemer** [comment]
On master we only tag v0.16, v0.17, v0.18, ... no matter what's in there. The idea is to release more often and if something is broken, then we fix it in the stable branches 0.16.y, 0.17.y and 0.18.y. Only fixes should go into these.

**Comment by 12345ieee** [comment]
Got it. The 0.N tag is the splitting point of each stable from master, from now on.

You can close this, thanks.

**Comment by sriemer** [comment]
Fixes in 0.17.y aren't put to 0.16.y as well. This is not the Linux kernel. So updates and version upgrades should be possible easily.

The only issue could be: Some distros have strict policies about major version (number) upgrades. So maybe we have to do exceptions.
