### ISSUE TITLE
gui: hexview: 'gtk-jump-to' icon not shown on Debian Stretch

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#236]
Commit 655e283debcf16cc07ece101acf7f8b90aa5753d (GameConqueror.xml: Replace GtkImage:stock with 'icon-name') didn't fix all icons. For some of them the "gtk-*" symlink is still used. The issue is that the 'gtk-jump-to' symlink has been removed in more recent GTK versions like GTK 3.22.

Affected icons: "gtk-edit", "gtk-jump-to"

A search in `/usr/share/icons` + `ls -l` shows to which files these are pointing to:

gtk-edit -> document-edit
gtk-jump-to -> go-jump

**Comment by sriemer** [comment]
Replacing 'gtk-jump-to' with 'go-jump' works but replacing 'gtk-edit' with 'document-edit' results in not showing that icon. 😠

**Comment by 12345ieee** [comment]
I can't reproduce this (fresh testing machine).
I went out of my way to install only LXDE and I can see both icons correctly.
You can tell they are from another theme, but they are there.

**Comment by sriemer** [comment]
I also did a fresh install with KDE and GNOME and the symlink "gtk-jump-to*" is not there. If this change doesn't break your system, then it should be fine.

````
find /usr/share/icons -name "*gtk-jump-to*"
````

output would help.

**Comment by 12345ieee** [comment]
```
# find /usr/share/icons/ -iname *gtk-jump-to* -exec ls -l --color=always {} \;
[...] /usr/share/icons/gnome/48x48/actions/gtk-jump-to-ltr.png -> go-jump.png
```

And this was expected, I have the symlink, in fact both `gtk-jump-to` and `go-jump` work.

```
# find /usr/share/icons/ -iname *gtk-edit* -exec ls -l --color=always {} \;
[...] /usr/share/icons/HighContrast/48x48/stock/gtk-edit.png
```

But the HighContrast version isn't the right one. I have no symlinks, either.
I have no idea where GC picks up the right icon.
