### ISSUE TITLE
mobile game cheating: scanmem on the Jolla smartphone

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#239]
I'd like to share a bit of experience porting scanmem for mobile game cheating.

I have the [Jolla smartphone](https://en.wikipedia.org/wiki/Jolla_(smartphone)) (SailfishOS 2 with sbj HW adaptation).

I've installed the [SailfishOS Platform SDK](https://sailfishos.org/wiki/Platform_SDK_Installation) and the [SailfishOS-armv7hl target](https://sailfishos.org/wiki/Platform_SDK_Target_Installation). That's a Scratchbox 2 `chroot` environment with QEMU for ARM code execution.

**Build steps** within the scratchbox
````
zypper install intltool libtool readline-devel
./autogen.sh
./configure --prefix=/usr --libdir=/usr/lib/scanmem
make && make install
````

**Deployment**
* enable developer mode on the Jolla device
* copy over libscanmem and the scanmem executable with `scp` (user `nemo`)
* move them with `ssh` to the right location as root (`devel-su` command to become root)

**Results** from first `scanmem` tests as root via `ssh`:
* many misc memory regions
  -> JavaScript stuff used by Android games
* finding game PID with `top` works best due to strange executable names
* scanning in memory is fast -> `/proc/$pid/mem` is available and used
* game isn't frozen when scanning in memory
  -> the Jolla guys modified `kernel/ptrace.c` breaking behavior compatibility to the mainline kernel
  -> they write that they need it to prevent keeping debuggers attached and not being able to kill apps
* **I've still been able to locate and modify a coins value in a game!** 😉

This is work in progress.

**Outlook**
* check if it works without root privileges 🚫
* check using scanmem from a terminal app on the device directly 🆗 
* look for other game freezing methods
* find more values in more games
* test locking/freezing variables reliably every game run (game trainer)

On my Nokia N9 MeeGo phone I even had a game trainer running with `ugtrain`. It made my space ship in a game invulnerable and equipped with unlimited ammo reproducible every game run. Relevant data was stored on the heap allocated by `malloc()` and `realloc()`. Quite some hacking was required to make that work and Debian packages had to be built. The device was not as open as it should have been. :wink:

Feedback, questions and help welcome.

@Funmungus: Do you have any experience to share regarding Android devices? Would be nice if you could open a new GitHub issue regarding this and share your knowledge. Thanks in advance!

**Comment by sriemer** [comment]
The developer mode and root are required but the developer terminal `fingerterm` can be used directly on the device for that. I've found and increased more coins values and a number of moves in a game. I would never pay real money for that. 😈

**Comment by 12345ieee** [comment]
@sriemer , a better place for this would be the scanmem repo's wiki: https://help.github.com/articles/about-github-wikis/ , which is currently not enabled in the scanmem repo.

I'd prefer to keep the issues just to issues themselves and TODOs, not content we'd like to keep around forever.

Good idea on sharing cheat methods on smartphones, though.

**Comment by Funmungus** [comment]
I have found in Android that the UI does not freeze.  I assumed it was just because of multiple threads, but I never looked into it.

**Comment by Funmungus** [comment]
I have also found that using /proc/pid/mem almost always fails in Android.  I do not know why.  My work-around is to always use ptrace by modifying the configure script before building.  It ends up being really slow on Android but more things are able to be found.

**Comment by sriemer** [comment]
Just process freezing is not working on SailfishOS. I guess the reason to avoid being unable to close apps with debuggers attached is the same on Android.

Btw.: I've seen that @KDSbest also failed to use /proc/$pid/mem on Android and had to fail back to ptrace() - see http://www.kdsbest.com/?p=197.

I'm glad that I have the fast method on SailfishOS. 😄

**Comment by sriemer** [comment]
We're through with experience exchange. So closing. Thanks! TODO: Move this to a Wiki.
