### ISSUE TITLE
gameconqueror pkexec is failing on OpenSUSE 42.1

### ISSUE THREAD

**Issue by Mirppc** [scanmem/scanmem#244]
So instead of using a precompiled version of scanmem and game conqueror i though i would compile it from GIT on Opensuse Leap 42.1.  Compiling worked flawlessly , yet when executing the program i get an error.

> ~/bin/scanmem> gameconqueror 
>==== AUTHENTICATING FOR org.freedesktop.gameconqueror.pkexec.run ===
>Authentication is required to run Game Conqueror
>Authenticating as: root
>Password:   
>polkit-agent-helper-1: error response to PolicyKit daemon: >GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: No session for cookie
>==== AUTHENTICATION FAILED ===
>Error executing command as another user: Not authorized
>
>This incident has been reported.

Tried it another way with sudo.

>~/bin/scanmem> sudo gameconqueror 
>Unable to init server: Could not connect: Connection refused
>Unable to init server: Could not connect: Connection refused
>
>(GameConqueror.py:9576): Gtk-CRITICAL **: gtk_clipboard_get_for_display: assertion 'display != >NULL' failed
>
>(GameConqueror.py:9576): Gtk-CRITICAL **: gtk_settings_get_for_screen: assertion >'GDK_IS_SCREEN (screen)' failed
>/usr/bin/gameconqueror: line 10:  9576 Segmentation fault      $PKEXEC >$DATADIR/GameConqueror.py "$@"
>

Now lets try kdesu.... 

http://paste.opensuse.org/11640172  That worked.

Note doing the kdesu game conqueror from the "Run Program" option in the menu didnt do anything.

Any help or suggestions would be appreciated.

**Comment by sriemer** [comment]
Scanmem and GameConqueror are usually working with `pkexec` on openSUSE Leap 42.1. Which window manager are you using? Is it KDE?

Please make sure that `polkit` and `polkit-kde-agent-5` are installed on your system.
Make sure that /usr/share/polkit-1/actions/org.freedesktop.gameconqueror.policy exists.

`kdesu` shouldn't be used any more due to security reasons.

I have an own package here: https://build.opensuse.org/package/show/home:sparschauer/scanmem

Unfortunately, for devel:tools and openSUSE Factory, GameConqueror may not be provided as the security guys don't like the `pkexec` stuff and think that it is a debugging tool for advanced users. So users should only use scanmem.

Btw.: On SUSE distros there are no `ptrace()` restrictions. So you can modify the `gameconqueror` script to contain this:

````
#!/bin/bash

DATADIR=/usr/share/gameconqueror

$DATADIR/GameConqueror.py "$@"
````

The only disadvantage is that you can't scan in processes of another user but for game cheating you usually scan in your own game processes.

**Comment by sriemer** [comment]
`/usr/lib/polkit-1/polkitd` and `/usr/lib64/libexec/polkit-kde-authentication-agent-1` should be running.

**Comment by sriemer** [comment]
This is what you should see:

![gc_polkit](https://cloud.githubusercontent.com/assets/1803210/23742898/fd94cd68-04ae-11e7-8a9b-b812a531bfdf.png)

**Comment by 12345ieee** [comment]
I add that simply doing:
```
sudo /path/to/GameConqueror.py
```
will work, at least on Debian-based distros, but here there is clearly something going on with `pkexec`, OpenSUSE and @Mirppc 's system.

**Comment by Mirppc** [comment]
@sriemer Oddly that window is not opening up after i compiled scanmem with gameconqueror enabled.

Oddly as you might know, i normally use the OBS version for Opensuse.  I just found it odd that i was not getting any error after doing 

>Run Program
>gameconqueror  
and nothing happens.  so running via a terminal is usually my next bet in debugging that issue.

Will fiddle around with this more later today as when i did get it running it was unable to trace some known memory addresses.

As for the security issue,  I come from a background related to game console memory address manipulation (gameshark, gamegenie, action replay, codebreaker and the like)  When creating the codes on an emulator one must treat the debugger with care and respect as manipulating memory addresses can sometimes have foul consequences.  There was a game i was working with on the Gameboy Advance and with the amount of memory address poking that was being done, well one of the addresses corrupted the ROM.  This sounds impossible but it can happen. 

So using things like Cheat Engine and Scanmem from my view point should be treated carefully.  So i concur with the security team putting gameconqueror as an advanced user debugging tool.


On another note to @sriemer  and @12345ieee ,  thanks for the swift and positive replies.  I appreciate it and your hard work.

**Comment by Mirppc** [comment]
Update.  I might have had a difficult time trying to explain my issue so instead i thought i would make a video instead.  I hope this helps.

https://youtu.be/HuKR7pgHwNE

**Comment by 12345ieee** [comment]
@Mirppc , is `/usr/share/polkit-1/actions/org.freedesktop.gameconqueror.policy` installed?
It **must** be installed in exactly that location (by a privileged user), or `pkexec` won't work.

What happens when you chain a "sudo-like" program like `gksu` or `kdesu` and `pkexec` I can't say, but I'm not surprised there are strange interactions.

**Comment by Mirppc** [comment]
If it isnt then something went wrong with compiling.

... some time later...

/usr/share/polkit-1/actions # ls
org.debian.pcsc-lite.policy	       org.freedesktop.systemd1.policy		 org.kde.kcontrol.kcmsddm.policy
org.freedesktop.accounts.policy        org.freedesktop.timedate1.policy		 org.kde.ksysguard.processlisthelper.policy
**org.freedesktop.gameconqueror.policy**   org.freedesktop.udisks2.policy		 org.kde.powerdevil.backlighthelper.policy
org.freedesktop.hostname1.policy       org.kde.fontinst.policy			 org.libvirt.api.policy
org.freedesktop.locale1.policy	       org.kde.kcontrol.k3bsetup.policy		 org.libvirt.unix.policy
org.freedesktop.login1.policy	       org.kde.kcontrol.kcmclock.policy		 org.opensuse.policykit.gparted.policy
org.freedesktop.NetworkManager.policy  org.kde.kcontrol.kcmkwallet5.policy	 org.opensuse.yast.modules.yapi.language.policy
org.freedesktop.policykit.policy       org.kde.kcontrol.kcmkwallet.policy	 org.opensuse.yast.modules.yapi.time.policy
org.freedesktop.RealtimeKit1.policy    org.kde.kcontrol.kcmremotewidgets.policy  org.xfce.power.policy


It is there.

**Comment by 12345ieee** [comment]
Uhm, I can see a difference.

When I run GC with `pkexec`, I'm not asked for the root password, I'm asked for my password, as I am in the sudo group. Isn't this the case on OpenSUSE?

Your first error (when you run `sudo gameconqueror`) is due to not having the correct envvars set, try with `sudo -E`, maybe.

What does the terminal say if you simply run `gameconqueror`?

**Comment by Mirppc** [comment]
If you look at the video i belive i tried executing gameconqueror without sudo.

thanks for the tip on the sudo -E will try that as soon as i can.

**Comment by 12345ieee** [comment]
Uhmm, see this: https://www.reddit.com/r/debian/comments/4h33rs/pkexec_authentication_failure/

**Comment by sriemer** [comment]
Like I said: `polkit-kde-agent-5` has to be installed.

**Comment by 12345ieee** [comment]
I am now going to make another inane question.

Do other packages that use this `pkexec` mechanism, such as gparted/virt-manager, work?

**Comment by Mirppc** [comment]
Gparted either requires one of the su comands(kdesu, gtksu etc) or to be run as root or sudo via command line. 

Just tried running Gparted as a normal user and got a popup saying it requires root.  I didnt use any command to elevate it and running gparted from the menu has no affect, the program doesnt open, no message, and no error.

**Comment by 12345ieee** [comment]
So, it's not an issue of our implementation if exactly the same happens to you with `gparted`, which I assume has a correct `pkexec` implementation.

I don't know anything about OpenSUSE and can't tell where something may have gone wrong, but it seems a setup problem of your particular system, @Mirppc , not a problem in GameConqueror.

Maybe @sriemer can be of further help.

**Comment by Mirppc** [comment]
Thank you @12345ieee.  I think i learned one lesson, use @sriemer package on the OpensuseBuild Service instead of compiling from source.  :)

**Comment by 12345ieee** [comment]
> use @sriemer package

@sriemer will be happy.

Closing this

**Comment by sriemer** [comment]
The package on OBS has a couple of patches. I can only imagine that [this patch](https://build.opensuse.org/package/view_file/home:sparschauer/scanmem/gameconqueror-incomplete-desktop.patch?expand=1) fixed the .desktop file as on openSUSE category "Utility" doesn't exist.

Apart from that, it is just configured with:

````
./configure --prefix=/usr --enable-gui --libdir=/usr/lib64/scanmem
````

**Comment by Mirppc** [comment]
yea it is likely and opensuse issue.   tried virt-manager and this is what i got.
______________________________________________________________________
Unable to connect to libvirt.

authentication failed: no agent is available to authenticate

Libvirt URI is: qemu:///system

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/connection.py", line 865, in _do_open
    self._backend.open(self._do_creds_password)
  File "/usr/share/virt-manager/virtinst/connection.py", line 161, in open
    open_flags)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 105, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirtError: authentication failed: no agent is available to authenticate

**Comment by sriemer** [comment]
Libvirt is special and doesn't use `pkexec`. `/usr/sbin/gparted_polkit` should be the script to compare with.

**Comment by sriemer** [comment]
Interesting, `gparted_polkit` contains this:

````
#!/bin/bash

if [ $(which pkexec) ]; then
        pkexec --disable-internal-agent "/usr/sbin/gparted" "$@"
else
        /usr/sbin/gparted "$@"
fi
````

The option `--disable-internal-agent` might help.

**Comment by 12345ieee** [comment]
In Debian it's simply:

```
~$ cat /usr/bin/gparted-pkexec 
#!/bin/sh
pkexec "/usr/sbin/gparted" "$@"

```

So, for sake of anybody landing here, this is something OpenSUSE specific.

**Comment by sriemer** [comment]
@msmeissn is the SUSE `polkit` maintainer. Maybe he knows why the internal agent causes trouble on SUSE distros.

**Comment by Mirppc** [comment]
Wasnt expecting this :octocat:   Thanks!

**Comment by sriemer** [comment]
TODO for myself: Add "--disable-internal-agent" to my scanmem package in my home project on OBS.

**Comment by sriemer** [comment]
Fixed in OBS [revision 8](https://build.opensuse.org/package/rdiff/home:sparschauer/scanmem?linkrev=base&rev=8). Thanks!

**Comment by msmeissn** [comment]
I have no particular glue about this option, would need to research it first. but if it works now... ;)

**Comment by Mirppc** [comment]
Well i had the drive in the workstation i was compiling scanmem on explode, so i installed a new drive and put 42.2 on it. scanmem compiled and asked for elevated privileges as expected and showed up in the menu as well.  Works via command line too.

I would consider this now fixed.
