### ISSUE TITLE
Option required to stay interactive after processing a script

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#246]
I've received a scanmem feature request via e-mail that an option is required to stay interactive after processing commands in the scripting mode of scanmem. This way you could create your own aliases to set different defaults for scanmem.

Also the scripting mode should be documented in the man page as only few people know about it.

My proposal is introducing option `-i/--interactive` with description _"stay interactive after processing a script"_.

Looks like this:
`echo -e "$cmd1\n$cmd2" | scanmem -i`

What are your thoughts?

**Comment by 12345ieee** [comment]
While you're looking into this, I raise another point.
I use the `echo -e "$cmd1\n$cmd2" | scanmem`-thing to do fast debug/testing and it is pretty cumbersome, to say the least.
Also, a new `-i` flag when the interactive behaviour is the default seems pretty strange to me.

So I propose to rework the handling and turn the syntax into `scanmem -- $cmd1X$cmd2` where `X` is some reasonable separator, and then adding a `-q/--quit` flag, to have scanmem quit after processing the cmdline.

This is probably more work and also drops the pid grabbing without `-p`, but I wanted to know your opinion on it.

**Comment by bkazemi** [comment]
Hmm, it would seem like a config file would be the best fit for persistent settings, maybe with something simple like libYAML. Should be easy to maintain, but it would add a new dependency.

I agree with @12345ieee that it seems a bit backwards to use a switch for interactive behavior as `scanmem` is described as a "interactive debugging utility" in the manpage. Unfortunately @12345ieee proposal would break backwards-compatibility if you were to disallow scripts through stdin, requiring a major version bump. But I also think it's a good idea for a one-line command separator, with `;` most likely for familiarity. But newlines should also be allowed as a separator for script files.

BTW - With modern shells like `bash` and `zsh` you can send a string to a command's stdin with a one-line heredoc:
```sh
scanmem <<<'cmd1\ncmd2'
```

**Comment by sriemer** [comment]
What about a `-c` switch which can be repeated for providing commands which should be processed before getting interactive and which are ignored if there is input from stdin?

**Comment by sriemer** [comment]
I'm sure @12345ieee can put the `exit` command at the end.

**Comment by sriemer** [comment]
Or maybe it is best to use `-c` together with input from stdin to stay interactive after processing commands from stdin e.g. when reading commands from a file.

**Comment by 12345ieee** [comment]
> I'm sure @12345ieee can put the exit command at the end.

This is better than my `-q` suggestion, one less flag.

**Comment by 12345ieee** [comment]
> `scanmem <<<'cmd1\ncmd2'`

You forgot the `$` sign to enable newlines.

    scanmem <<< $'cmd1\ncmd2'

This one indeed works and it's definitely better than echo, now, if we could convince `scanmem` not to close after processing this.

**Comment by bkazemi** [comment]
@sriemer 
A `-c` switch would definitely be much less work. I think the second option sounds better. Maybe a single `-c` without arguments could also act as a sort of implicit interactive mode switch as well. But maybe adding an `-i` switch also would be less confusing for that.

**Comment by 12345ieee** [comment]
@bkazemi Yes, what I meant is that if we can make 'continue' the default mode, we can manually call exit and get the behaviour we want without any extra switches.

**Comment by sriemer** [comment]
So the current opinion is "leave everything as is, just remove the exit from the scripting mode", right?

I would still prefer introducing a `-c` option as that's definitely more intuitive than
````
scanmem <<< $'cmd1\ncmd2'
````
It is like for a shell then. These also provide a `-c` option to process commands. You can keep your commands at the end of your shell command.

**Comment by 12345ieee** [comment]
So:
* `sm -c 'cmd'` leaves scanmem open in interactive mode
* `sm <<< 'cmd'` behaves as it does now and should be replaced by `sm -c $'cmd\nexit'`, that's a bit less insane
* `-c` could accept ';' as separators, removing more quotes and disasters

Did I get it all?

**Comment by bkazemi** [comment]
I also think a `-c` option makes sense. But I think for the sake of separation of concerns the two changes should be separate commits.

**Comment by sriemer** [comment]
Sounds good. Can be implemented this way.

**Comment by 12345ieee** [comment]
I have a simple implementation of this at 12345ieee/scanmem@07ea9913351fe1a4 .
It uses `strtok_r()`, due to strtok nesting in `execcommand()`, I'm not exactly sure how portable this is.

Please have a look.
