### ISSUE TITLE
Can't compile for Android platform successfully

### ISSUE THREAD

**Issue by ListerTheTormentor** [scanmem/scanmem#247]
I Can't compile for the Android platform with NDK toolchain successfully. The host is ubuntu 16.04. Can anyone tell me what's wrong? thanks!
[complie.txt](https://github.com/scanmem/scanmem/files/1050910/complie.txt)

**Comment by sriemer** [comment]
Sorry, it's a bug in ptrace.c in the case that /proc/$pid/mem is not available/usable. `peekdata()` is called although it has been renamed to `sm_peekdata()`. My fault. I'll fix that.

**Comment by sriemer** [comment]
Thanks for reporting!
