### ISSUE TITLE
Realtime memory editor

### ISSUE THREAD

**Issue by bquenin** [scanmem/scanmem#248]
I wanted to know if it's possible to add sort of an auto-refresh (every sec for instance) to the memory editor. It would help identifying increasing/decreasing values (timers and such).

**Comment by 12345ieee** [comment]
Looks doable on paper and reasonably useful, I'll have a look when I've some time.

**Comment by 12345ieee** [comment]
So, doing it actually realtime would be non-trivial, at least for now.

I added a refresh button, though, that should cover most of the use cases.

Build GC from 12345ieee@0762c15 and see what you think.
