### ISSUE TITLE
Coverity Scan reports memory leaks (settings calloc() in handlers.c)

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#260]
@12345ieee Please fix the memory leaks you've introduced with commit 7d2c52c6b9bd12717f122b3045162e1f9f97a9dd.

See: https://scan.coverity.com/projects/scanmem/view_defects

Furthermore, an explanation why putting stuff on the heap instead of on the stack is required would be nice. I know that alloca() is not very portable.

I've checked the whole PR #259 with Coverity Scan.

**Comment by sriemer** [comment]
I see at least four locations where `settings` is not freed. Coverity only reports three this time.

**Comment by 12345ieee** [comment]
I'm sorry @sriemer , the idea was that the user is in control of how may structs we allocate in that case, and I don't want them to blow the stack with `alloca()`.

I followed the previous commented free's, but I clearly missed some locations.

I'll have a better look tomorrow, thanks for stepping up.

**Comment by 12345ieee** [comment]
I have reverted the offending commit, and will think better next time before messing with memory allocation.

Thanks for reporting it this fast (and for adding me to the Coverity team, I hadn't noticed).

**Comment by bkazemi** [comment]
While on the subject,  `alloca()` is unnecessary as c99 
supports variable length arrays.

**Comment by 12345ieee** [comment]
But they've been made optional as of C11, so I'm not really 100% sure what is now the "proper" way to allocate memory on the stack.

**Comment by sriemer** [comment]
All green again. Thanks! A full revert wouldn't have been required. Coverity Scan can check code before submitting it to the master branch.

```
rm -Rf cov-int scanmem.tgz
cov-build --dir cov-int make -j 16
tar czf scanmem.tgz cov-int/
```
And then that file is uploaded for analysis.

**Comment by 12345ieee** [comment]
I use a kernel (4.11) that's too new for Coverity, and their tool fails on my environment.

I uploaded this new tarball (from the tip of the rebased VLT branch) from a VM, but it's a huge pain doing that consistently.

**Comment by bkazemi** [comment]
`scanmem` doesn't support c11, so it should be ok.

**Comment by sureshmahajan** [comment]
Hi, 
I am facing memory leak issue with Coverity v2017.07. Coverity build and analysis finished but it add some space to OS cache and never frees up and as a result it piles up the garbage on OS cache. Does above issue is the reason for this leak? OR could be another issue? any suggestions/help would be appreciated?

**Comment by sriemer** [comment]
This is about a memory leak in scanmem/libscanmem and not about leaks in the Coverity tool. Please report directly [to them](https://community.synopsys.com/s/topic/0TO340000000snQGAQ/static-analysis-tool-coverity).
