### ISSUE TITLE
 gui: Unable to launch pkexec'ed applications on Wayland session 

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#263]
Just FYI: There is trouble with GameConqueror when running it on Ubuntu 17.10 with Wayland:
https://bugs.launchpad.net/ubuntu/+source/scanmem/+bug/1713313

It is basically a Wayland bug and there is nothing to be done from our side. I'd just like to raise awareness and that we need to test GC against Wayland.

**Comment by yodatak** [comment]
I find a temporary fix for run with wayland in terminal 
`
xhost +local:
gameconqueror`
And it works but a workaround so we must wait to be fix.

**Comment by sriemer** [comment]
Not an issue on openSUSE Leap 15 by the way. ;)

**Comment by sriemer** [comment]
Ubuntu postponed Wayland by default to the next LTS. I handle this like GParted and set the Ubuntu scanmem bug to invalid. OpenSUSE shows that proper pkexec permission handling is possible. So let's close this now.
