### ISSUE TITLE
'?' doesn't work in fedora 26

### ISSUE THREAD

**Issue by yodatak** [scanmem/scanmem#265]
With the master compiiled and the package in the repository I can't click on '?' and have the usage of the command displayed. Is that normal?

**Comment by 12345ieee** [comment]
It's not clear what you're asking, but you might be victim of #263 .

Run `gameconqueror` on a terminal, post the output.
Also, check if you're running X or Wayland.

**Comment by sriemer** [comment]
It is correct that you cannot click at the '?'. It should show the help for the value input in a popup with a mouse hover event.
Is the question answered?

**Comment by 12345ieee** [comment]
I had totally misunderstood that, @sriemer 's interpretation makes much more sense.
Indeed the '?' is not clickable.

**Comment by sriemer** [comment]
I've changed the question with the correct punctuation marks. 😉

**Comment by 12345ieee** [comment]
I assume that by now @yodatak has got the '?' working.

Closing this issue.
