### ISSUE TITLE
Policykit issues on Puppy Linux

### ISSUE THREAD

**Issue by frenchiveruti** [scanmem/scanmem#286]
Hello, I'm kind of crap when it comes to linux installations, I feel like I end up bloating my distro a lot and don't know what the hell I'm doing.  
I'm using Puppy linux, and I get this message once I had installed the scanmem and gameconqueror.
"Install Policykit!"
What the heck does that mean? Puppy is a root only OS. So a policy really isn't a thing I need.  
Is there a way around it? My puppy uses [JWM](https://joewing.net/projects/jwm/config.shtml#keys) as window manager.

Is there anything else that would come useful for solving this?

**Comment by 12345ieee** [comment]
I see Puppy is an Ubuntu 14.04 derivative, so in all likelihood the packager just removed the dependency on policykit without updating the launch script.

I need to know:
* What version of GC have you installed
* How did you install it (source compile or some package)
* The content of the `gameconqueror` launch script (find it with `which gameconqueror`)

**Comment by frenchiveruti** [comment]
Hi there!  
So, I just cloned the git master folder yesterday (I really don't know how to check the version).  
Ran the exact commands posted here on the Git.
(autogen.sh
then configure with gui
then make install)
Finally:
`#!/bin/bash  
DATADIR=/usr/share/gameconqueror  
PKEXEC=$(command -v "pkexec")  
if [ -n "$PKEXEC" ]; then  
    $PKEXEC $DATADIR/GameConqueror.py "$@"  
else  
    echo "install policykit!"  
fi`

**Comment by 12345ieee** [comment]
Ok, just change the `gameconqueror` script to:

``` bash
#!/bin/bash

DATADIR=/usr/local/share/gameconqueror

$DATADIR/GameConqueror.py "$@"
```

which should do the trick, assuming you are actually using `root`.

**Comment by frenchiveruti** [comment]
I think I have to update python now:
```console
Traceback (most recent call last):
  File "/usr/share/gameconqueror/GameConqueror.py", line 34, in <module>
    import gi
ImportError: No module named gi
```

**Comment by 12345ieee** [comment]
The README has a list of requirements.

You can skip policykit because you're root, but you're going to need the rest.

**Comment by frenchiveruti** [comment]
Ok, So I have Python 2.7 so it should work.
Maybe has something to do with [this](https://askubuntu.com/questions/80448/what-would-cause-the-gi-module-to-be-missing-from-python)?

**Comment by 12345ieee** [comment]
### Requirements

libscanmem (latest version) - OK
Python (2.x / 3.x) - OK
PyGObject  - you're missing this
GTK+ 3 - and possibly also this
policykit - you don't need this

**Comment by frenchiveruti** [comment]
I'm sorry to bother you so much 😞 
I really shouldn't be messing with this if I don't know that kind of level of Linux.  
Thanks anyways for your help, my OS is an special kind...

**Comment by 12345ieee** [comment]
It's just a matter of installing the right packages, but I can't help you there, you have to find your distro's support channel.

If you also want my unsolicited opinion, while you're still learning it's better to use an easy and standard distro, like some user-friendly Ubuntu derivative.

Closing, as there's nothing to fix.

**Comment by frenchiveruti** [comment]
Hi there again, solved it installing the "python-gi" for python 2 as it seems to be the one working here.  
The distro comes with GTK so that was not the issue, GameConqueror is now running.
Thanks!
