### ISSUE TITLE
Status of v0.17 in the distributions

### ISSUE THREAD

**Issue by 12345ieee** [scanmem/scanmem#288]
Let's have a look at which distros picked v0.17 up (table from #119 ) : 

| Distribution | Maintainer(s) | Latest Unstable | Link |
| --- | --- | --- | --- |
| Arch | Levente Polyak ( @anthraxx ) | 0.17-1 | https://www.archlinux.org/packages/community/x86_64/scanmem/ |
| Debian | Sebastian Parschauer ( @sriemer ),<br> **Uploader:** Kartik Mistry ( @kartikm ) | 0.17-2 | https://tracker.debian.org/pkg/scanmem, <br>devel: https://salsa.debian.org/debian/scanmem |
| Fedora | Igor Gnatenko ( @ignatenkobrain ), Jakub Hrozek  | 0.17-1 | https://apps.fedoraproject.org/packages/scanmem |
| Gentoo | **No maintainer** See: https://github.com/scanmem/scanmem/issues/288#issuecomment-360041311 | 0.16.1 | https://packages.gentoo.org/package/dev-util/scanmem |
| Mageia | Shlomi Fish ( @shlomif ) | 0.17-1 | https://madb.mageia.org/package/show/name/gameconqueror/release/cauldron |
| openSUSE | Sebastian Parschauer ( @sriemer ) | 0.17 | official: https://build.opensuse.org/package/show/openSUSE:Factory/scanmem, <br>with GUI: https://build.opensuse.org/package/show/home:sparschauer/scanmem |
| Ubuntu | see Debian | 0.17-2 | https://launchpad.net/ubuntu/+source/scanmem/ (depends on Debian version) |
| Ubuntu PPA | Sebastian Parschauer ( @sriemer ) | 0.17 | https://launchpad.net/%7Es-parschauer/+archive/ubuntu/game-cheating |

Only Gentoo is missing, see https://github.com/scanmem/scanmem/issues/288#issuecomment-360041311

**Comment by ignatenkobrain** [comment]
yay, I'm the only one keeping scanmem up2date!

**Comment by shlomif** [comment]
On Wed, 15 Nov 2017 20:37:14 +0000 (UTC)
Andrea Stacchiotti <notifications@github.com> wrote:

> So, a month after release, let's have a look at which distros picked v0.17 up
> (table from #119 ) : 
> 
> | Distribution | Maintainer(s) | Latest Unstable | Link |
> | --- | --- | --- | --- |
> | Arch | Levente Polyak ( @anthraxx ) | 0.16.1-1 |
> https://www.archlinux.org/packages/community/x86_64/scanmem/ | | Debian |
> Sebastian Parschauer ( @sriemer ) | 0.16-1 |
> https://tracker.debian.org/pkg/scanmem | | Fedora | Igor Gnatenko
> ( @ignatenkobrain ), Jakub Hrozek  | 0.17-1 |
> https://apps.fedoraproject.org/packages/scanmem | | Gentoo | **No
> maintainer** | 0.16.1 | https://packages.gentoo.org/package/dev-util/scanmem
> | | Mageia | Shlomi Fish ( @shlomif ) | 0.15.7-1 |
> https://madb.mageia.org/package/show/name/gameconqueror |

Actually, scanmem in mageia cauldron is at 0.17 and has been upgraded on
October 24. Is there a good reason why it should be upgraded in mga v6 too?

Regards,

-- @shlomif


-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Selina Mandrake - The Slayer (Buffy parody) - http://shlom.in/selina

I have defined the 100 per cent American as 99 per cent an idiot.
    — https://en.wikiquote.org/wiki/George_Bernard_Shaw

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by 12345ieee** [comment]
Thanks for the answer, @shlomif .
I don't know the distro well enough and I blindly followed the link in the old issue.

Now I see at https://madb.mageia.org/package/show/name/gameconqueror/release/cauldron that it's updated to 0.17.

No need to update it in the stable release, 0.15.7 is recent enough and does not have huge issues.

Thanks to @ignatenkobrain as well.

**Comment by shlomif** [comment]
On Thu, 16 Nov 2017 13:56:37 +0000 (UTC)
Andrea Stacchiotti <notifications@github.com> wrote:

> Thanks for the answer, @shlomif .

you're welcome.

> I don't know the distro well enough and I blindly followed the link in the
> old issue.
> 
> Now I see at
> https://madb.mageia.org/package/show/name/gameconqueror/release/cauldron that
> it's updated to 0.17.
> 
> No need to update it in the stable release, 0.15.7 is recent enough and does
> not have huge issues.
> 

thanks for the info.

> Thanks to @ignatenkobrain as well.
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Best Introductory Programming Language - http://shlom.in/intro-lang

There are two types of command interfaces: good interfaces and user interfaces.
    — http://en.wikiquote.org/wiki/Daniel_J._Bernstein

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by anthraxx** [comment]
slipped through my watch diff, will package it in the evening :tada:

**Comment by sriemer** [comment]
openSUSE only provides `scanmem` as part of the official distribution via the `devel:tools` project. scanmem 0.17 is [on its way to Factory](https://build.opensuse.org/request/show/563206). Might not be too late to end up in Leap 15.0. As the security guys don't like `pkexec` stuff, I provide GC in my home project as well. Will update it soon.

**Comment by 12345ieee** [comment]
Thanks @anthraxx , updated.

----------------------

Good to hear, @sriemer .
Maybe place a link to both scanmem and GC pages, as they are different.

Will you do the Debian packaging as well?

**Comment by sriemer** [comment]
Thanks for your great work for `v0.17` @12345ieee and congratulations on more commits than I have! 🎉 You really saved me when I didn't have enough time for scanmem any more. I just finished quickly reviewing the commits to catch up.

After a severe development direction issue with my tool ugtrain I've got things sorted out there and started to get it rolling again. It will have priority for me as it has all the nice game trainer features which also work the next game run. But I'll try to support you at scanmem more from now on again.

I will add the link to the Factory project. As I'm in packaging mode right now let me try to take over the Debian packaging. The problem there is that I need to find a mentor as we don't have a regular uploader there. Work is located at: https://github.com/sriemer/scanmem-debian
Mentors platform: https://mentors.debian.net/
Last time we sneaked it in via a severe security bug and the release manager uploaded it.

**Comment by 12345ieee** [comment]
Thank you, @sriemer .

About "competing" projects, there's your ugtrain and @korcankaraokcu 's PINCE that supply interfaces and high-level capabilities, so I'm thinking about going into an orthogonal direction.

That is working most on making libSM a powerful and fast memory scanner library and less on the GUI (the last part, the CLI frontend, is mostly @bkazemi 's domain right now), so that you guys can provide fancy stuff and call SM code for the intensive memory-crunching part.

If you guys have some ideas for features you'd like to see, #285 is the place to go.

About Debian packaging, thanks for offering, I should be able to help this weekend.
This time I'd like to see the library split from `scanmem`, we can see better later.

The deadline we have right now is the [Ubuntu 18.04 release](https://wiki.ubuntu.com/BionicBeaver/ReleaseSchedule), which has a Debian import freeze on the 1st March, which means we have roughly a month to upload to Debian unstable.
Let's hope we have luck in finding a sponsor.

**Comment by sriemer** [comment]
https://github.com/scanmem/scanmem/blob/3b4bf8366c6fe2e15798ab252cfeda76fb003105/Makefile.am#L47
This is blocking me from splitting the library. `libscanmem.so.1` was almost everything already. I need libscanmem version 2 for this. So I can't rely on stable interfaces there. Also the interfaces aren't documented yet. Debian also doesn't want to split the library before there is another library user than GC. I even had to move the lib to /usr/lib/scanmem/. So without a pkg-config file, nothing will be able to find libscanmem at configure time. IMHO time is not right yet to do the split.
See: https://people.freedesktop.org/~dbn/pkg-config-guide.html

Let's do it the next release.

ugtrain still just calls scanmem and makes it the parent of the game with a chicken-and-egg hack to bypass ptrace() limitations on Ubuntu for value discovery. I've rejected GUI development - don't need it, don't have the resources. It is my personal game hacking project now. Discovery is done only rarely. If I have one value in a C++ object, then I can dump the object in two states, compare them and have the other values. So no need to implement memory scanning stuff. Only implementing ASLR/PIC/PIE support for scanmem was important to implement the counterpart. So ugtrain contains `maps.c` code.

**Comment by 12345ieee** [comment]
I see, there is a library user, but it's the same source package, so it "doesn't count".
Makes sense, next release we'll make a better documented libSM and make it version 2, then we'll see if we find users.
Thanks for the `pkg-config` link.

I thought that with the library split some versions ago `ugtrain` started to call the library as well, but if you call scanmem directly there's really no urgent need for the library.
Of course I can see why you don't need to scan often if you can just find the values once and then write a profile to be used at each restart.

I see ugtrain is C++ and I'm even more tempted to pass to C++ here as well, but this is for another issue.

**Comment by sriemer** [comment]
SUSE packaging updated. On its way to Leap 15.0 to be released in April. GC is also working fine. I only had to drop lang sr_ME - not provided by the distro. I like it. Works as expected. Well done!

**Comment by sriemer** [comment]
Bug reported to Gentoo: https://bugs.gentoo.org/645536

**Comment by sriemer** [comment]
Alright, scanmem/GC in my home project on opensuse.org now also uses Python 3 and the new metainfo.

**Comment by sriemer** [comment]
TODO: Update my Ubuntu game-cheating PPA for backporting to older distros at https://launchpad.net/~s-parschauer/+archive/ubuntu/game-cheating.

**Comment by sriemer** [comment]
Ubuntu trusty, xenial and artful users can also get `v0.17` by using my updated game-cheating PPA:
https://launchpad.net/~s-parschauer/+archive/ubuntu/game-cheating

Bionic will get `0.17-2` from Debian. Kartik only updated the `debian/watch` before uploading my latest changes.

**Comment by 12345ieee** [comment]
Thanks a lot to both @sriemer  and @kartikm for the work you've done.
I added a line with your PPA to the OP's table.

**Comment by sriemer** [comment]
Only Gentoo is still at 0.16. Version 0.16 was also a good release on Linux. It is just slower and missing some new features. Gentoo without a fixed scanmem maintainer is not that important here. So closing.
