### ISSUE TITLE
AM_PROG_CC_C_O error at autogen time

### ISSUE THREAD

**Issue by ChaosNicro** [scanmem/scanmem#289]
Hey there,
I'm trying to run autogen.sh but fail with the line:
`test/Makefile.am:4:` warning: compiling 'memfake.c' with per-target flags requires 'AM_PROG_CC_C_O' in 'configure.ac'`
The documentation for autotools says that his method is deprecated, is that the problem or did I mess something up? All dependencies should be present.

Full log:
```
+ running libtoolize ...
+ running aclocal ...
+ running autoheader ... 
+ running autoconf ... 
+ running intltoolize ...
+ running automake ... 
automake: warnings are treated as errors
test/Makefile.am:4: warning: compiling 'memfake.c' with per-target flags requires 'AM_PROG_CC_C_O' in 'configure.ac'

automake failed
```

**Comment by 12345ieee** [comment]
This looks really weird, can you post your `automake` version (from `automake --version`) and your distro/compiler?

**Comment by ChaosNicro** [comment]
sure:

`automake (GNU automake) 1.13.4
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.`

`gcc (SUSE Linux) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

`LSB Version:    n/a
Distributor ID: openSUSE project
Description:    openSUSE Leap 42.3
Release:        42.3
Codename:       n/a`

`Linux linux-xnr9 4.4.92-31-default #1 SMP Sun Oct 22 06:56:24 UTC 2017 (1d80e8a) x86_64 x86_64 x86_64 GNU/Linux`

Don't quite know what compiler it defaults to, but I would think it is gcc in my case.

**Comment by 12345ieee** [comment]
Ah, old `automake`, that's why I had no such issue.

Add `AM_PROG_CC_C_O` to `configure.ac`, at the 8th line and retry.

**Comment by ChaosNicro** [comment]
Going with latest automake/conf seems to solve the issue just as well as adding that line with the old version now both are stuck on this:

+ running libtoolize ...
+ running aclocal ...
configure.ac:12: warning: AM_NLS is m4_require'd but not m4_defun'd
m4/intltool.m4:27: IT_PROG_INTLTOOL is expanded from...
configure.ac:12: the top level
configure.ac:12: warning: AM_NLS is m4_require'd but not m4_defun'd
m4/intltool.m4:27: IT_PROG_INTLTOOL is expanded from...
configure.ac:12: the top level
+ running autoheader ... 
configure.ac:12: warning: AM_NLS is m4_require'd but not m4_defun'd
m4/intltool.m4:27: IT_PROG_INTLTOOL is expanded from...
configure.ac:12: the top level
+ running autoconf ... 
configure.ac:12: warning: AM_NLS is m4_require'd but not m4_defun'd
m4/intltool.m4:27: IT_PROG_INTLTOOL is expanded from...
configure.ac:12: the top level
configure:11848: error: possibly undefined macro: AM_NLS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

autoconf failed

**Comment by sriemer** [comment]
Same issue when packaging `scanmem 0.17` for SUSE distros. @12345ieee: Would be nice if you would send me the commit id of your release candidate before releasing for testing via direct e-mail. The SUSE build service covers many CPU architectures and OS releases. Fails on Leap 42.* and SLES12-SP*.

**Comment by sriemer** [comment]
Adding `AM_PROG_CC_C_O` to line 12 works. But then `make check` fails as it uses scanmem from `.libs/` and that one doesn't look for `libscanmem.so.1` in the same directory. Checks which rely on libscanmem to be already installed are pointless. So it seems to be best to remove the `test` subdir from compilation for distributions for now as this feature is not ready yet.

**Comment by sriemer** [comment]
openSUSE doesn't require root privileges for `ptrace()` so in theory it could run `make check` during the package build.

**Comment by 12345ieee** [comment]
Nice to see you around, @sriemer .

I had #278 open before release and have #288 open now for maintainer woes.
I'll open a new issue before releasing a new point release, but I'll be sure to send you an email if that's better for you. As of now, the commit is the one tagged `v0.17`, aka 4590cbb .

About `AM_PROG_CC_C_O` I have an `automake` new enough that it's not needed, and so have the other maintainers, but SUSE and Debian are a bit more behind and I can imagine you need it.
We can add it upstream if it's easier for you.

About `make check`, I do not really recommend package builders use it, it's more an internal testing framework I designed with travis integration in mind, using automake's facilities was just convenient.

When I run `make`, the `test` directory is entered by the main `Makefile`, but by default it doesn't build or run anything. If you want `memfake` to be built you need to run `make check`.
If you want the `test` directory to not even be entered in the `make` case we can write a configure switch, but it looks overkill to me.

The `scanmem` used by the `check` script is the root directory `scanmem`:
```bash
test_sm () {
    ../scanmem -p $memfake_pid -e -c "$1"
}
```
which is a shell script that knows that the library and exe are in `.libs`, there's no need to have `libsm` installed system-wide, nor any need to call the exe directly with `LD_LIBRARY_PATH` set.
I don't have `libsm` anywhere in my `PATH` and everything works.

If in your system this script doesn't work (aka, you need to call the exe directly as `LD_LIBRARY_PATH=.libs/ .libs/scanmem`) let me know, we'll figure out a workaround.

For other maintainer problems, #288 is the place to go.

**Comment by sriemer** [comment]
Thanks! The "make check" thing is a libtool bug. The generated `scanmem` wrapper script doesn't escape colons in the path but colons are the delimiter for `LD_LIBRARY_PATH` and are used inside OBS project names. Reported as https://bugzilla.opensuse.org/show_bug.cgi?id=1075196.

**Comment by sriemer** [comment]
Backwards compatibility is always preferred - especially for C tools. It should always be possible to build `scanmem` on older distributions. Adding the `AM_PROG_CC_C_O` doesn't hurt. So I hope to see it in `v0.17.1`.

**Comment by 12345ieee** [comment]
Glad you got the `make check` bug sorted.

As for backwards compatibility, I agree, I was just not sure if it was the issue the OP was having.
I'll add it in a commit shortly.

**Comment by sriemer** [comment]
This is fixed. Thanks!
