### ISSUE TITLE
GUI Feature Request: "snapshot" use in gameconqueror

### ISSUE THREAD

**Issue by apocalyptech** [scanmem/scanmem#290]
Hello!  It'd be nice to have the ability to use "snapshot" in the GUI.  Obviously one can just use the CLI scanmem, but the GUI's fairly pleasant, and it'd be a nice addition.  I wonder if it'd make more sense as a separate button, next to 'reset'.

If I'm feeling adventurous later, I may see about putting a pull request for this together.

Thanks!

**Comment by 12345ieee** [comment]
It's already there, as the `?` command (enter it in the search textbox).
Sure, we forgot to document it, so it's almost like it's not there.

I'll fix this later.

**Comment by apocalyptech** [comment]
Oh, what the hell - I spent like ten minutes combing through the popup help dialog next to the text entry box there, and on every readthrough somehow managed to miss the very-clearly-labelled "?" entry.  I think this is actually probably documented just fine, and I'm just being a fool by not seeing it.  :)

I'll go ahead and close this out, this already works just how I'd hope it would.  Thanks, and sorry for the spam!

**Comment by 12345ieee** [comment]
The funny thing is that I missed it as well while looking for it 2 minutes ago.
I'm probably putting it after the operator options, which is a more logical place.

Closed.
