### ISSUE TITLE
Lintian complains about legacy format in GameConqueror.appdata.xml

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#295]
```
W: gameconqueror: appstream-metadata-in-legacy-location usr/share/appdata/GameConqueror.appdata.xml
E: gameconqueror: appstream-metadata-legacy-format usr/share/appdata/GameConqueror.appdata.xml
```

See: https://lintian.debian.org/tags/appstream-metadata-legacy-format.html

Blocks Debian packaging for #288.

**Comment by 12345ieee** [comment]
Thanks for starting the packaging, @sriemer !

I'm tagging this as [Help Needed], as I don't know the new appstream spec and can't study it in these days.
@ignatenkobrain wrote it initially, maybe he can help.

I'll take a look this weekend if nobody had before then.
Worst case, we can drop it.

**Comment by sriemer** [comment]
New location: `/usr/share/metainfo/`. This way only the error remains.

**Comment by kartikm** [comment]
@sriemer Can you backport this to 0.17 in Debian package, so we are clear to upload? :)

**Comment by sriemer** [comment]
@kartikm: Sure, got it in my private repo https://salsa.debian.org/spars-guest/scanmem-test for testing. Only width and height are different due to the need to merge with 0cc3830215c131a4b54cbd43f9199cfb68f6ab3e. Still got some trouble with the Debian guidelines regarding this: https://wiki.debian.org/AppStream/Guidelines

```
If the file is named 'guiapp.desktop', the ID in the metainfo file must be 'guiapp' or
'guiapp.desktop', if it is 'org.example.guiapp.desktop', the ID must be 'org.example.guiapp'
or 'org.example.guiapp.desktop'. If you want to be compatible with older AppStream
versions, having the .desktop suffix is recommended.
```

`appstreamcli validate` wanted to have the new format like `com.github.gameconqueror` but for that we have to rename the `*.desktop` file and the `*.appdata.xml` as well. I'll try to do that in a second commit.

**Comment by sriemer** [comment]
@kartikm: Upstream PR created, pushed to https://salsa.debian.org/debian/scanmem for package testing.
