### ISSUE TITLE
Search for pointers?

### ISSUE THREAD

**Issue by hopeseekr** [scanmem/scanmem#301]
I need the ability to search for pointers because the memory address changes with each level of the game I am playing and I hate killing the guy 4-6x each round just to find the health variable.

**Comment by 12345ieee** [comment]
I assume you're talking about the GUI:

the feature is already implemented, right-click on a variable in the result list (left part) and you'll see a "Scan for this address" entry.
This isn't available for variables in the cheat list (bottom), I might add it there as well if it's useful.

**Comment by sriemer** [comment]
Is the found health value located on the heap?

I guess you're talking about the `Cheat Engine` method to find pointers in static memory pointing to heap objects. Also on Linux it is required to use a debugger (e.g. `gdb`) and a watch point to locate the code which modifies the interesting memory value. With the code part you get the offset of the health member within that object and with that also the memory address of the object. Then you can look for the memory address of the object as `int64` on `x86_64` and if you are lucky, then there is a single match.

**Please note**: scanmem/GameConqueror is not able to follow such pointers. Use an advanced game trainer like e.g. [ugtrain](https://github.com/ugtrain/ugtrain) for that.

This method also doesn't provide the size of the object on the heap. But you could guess, dump and compare that memory to possibly find other interesting values within the object. This method is only that simple if there is a single object of the C++ class you're interested in.

An example with the game `chromium-bsu` can be found [here](https://github.com/ugtrain/ugtrain/blob/master/examples/incomplete/chromium-bsu64_pointer.conf).

But the preferred way for dynamic memory cheating with `ugtrain` is API hooking of `malloc()`, `free()`, etc with `LD_PRELOAD`. Discovery records all malloc()s, then this is matched with the memory address from `scanmem` and the memory object size, the offset of the member, and the code address of the C++ constructor which allocates that object is found. This is much easier to adapt to different compiler versions/option and game versions. Furthermore, you can hack all objects which are allocated from that constructor.

The `chromium-bsu` example for this can be found [here](https://github.com/ugtrain/ugtrain/blob/master/examples/chromium-bsu64.conf).

**Comment by sriemer** [comment]
I've even tested the `Cheat Engine` pointer following stuff on Windows with trainer auto-generation for `chromium-bsu` See: https://github.com/sriemer/spars-coding/tree/master/CheatEngine/chromium-bsu

That stuff doesn't support wish values. So I had to use the same key to toggle freezing and to set the configured value to my wish value.
In the .CT XML file it is visible that `Cheat Engine` also works with an offset within the heap object. `004496EC` is the address of the pointer in static memory. It is repeated for all values within the object which is kind of stupid if a single pointer could be followed once per cycle. Together with the offsets, the `RealAddress`es are calculated from it.

The offsets only differ a bit as this is 32-bit on Windows.

**Comment by 12345ieee** [comment]
Thanks @sriemer for answering the question as it was probably intended.
I simply answered it as stated and I didn't really give a useful answer.

To make the feature more useful we could start a series of searches on the address going back `sizeof(variable)` each time (assuming aligned members), hoping to find a single match after a while, but this looks way too much "needle in a haystack" to spend time on it.

Dedicated people will definitely use either gdb or ugtrain.

**Comment by 12345ieee** [comment]
This was answered in detail, so closing.
