### ISSUE TITLE
Coverity Scan builds should scan Python code as well

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#317]
Coverity Scan has Python support as well now. So I've configured the project there not to ignore the code in `gui` any more and that Python is a secondary programming language.

I've built and uploaded manually:
```
cov-build --dir cov-int --fs-capture-search gui make -j 16
tar czf scanmem.tgz cov-int/
```

It found two new defects - both in the GUI. The defects should be fixed and the Travis CI build should also be configured to check Python as well.

See: https://scan9.coverity.com/reports.htm#v21953/p12219

**Comment by sriemer** [comment]
I've edited the previous comment as I analyzed the wrong code. Now it is correct. Sorry.

**Comment by 12345ieee** [comment]
Great idea.

Gave them a quick look, totally harmless stuff, but I'll fix them.

The language configuration should be server-side, so nothing needs to be changed in the travis config, I'll test this when I fix them by pushing to the `coverity_scan` branch.

**Comment by sriemer** [comment]
This is not correct. Just tested by pushing to branch `coverity_scan`. It does not upload the Python source (`--fs-capture-search gui`) for analysis.

**Comment by 12345ieee** [comment]
I've done the necessary changes to the `.travis.yml` file, fixed the trivial issues and resubmitted a scan.

You can see the final commit at the tip of `coverity_scan` : 461b583 .

I'll merge that into master in a few days if you see no problems.

**Comment by 12345ieee** [comment]
I've merged the changes into master after further testing, closing.
