### ISSUE TITLE
"Lock Value" needs to give up after process is dead

### ISSUE THREAD

**Issue by BluecoatEngineer** [scanmem/scanmem#321]
Reproduction steps:
1) Play Game.
2) Realize Game is a bastard and was never going to let you unlock all the MacGuffins no matter how hard you grind; use GameConqueror (spawned in a terminal) to reinforce that machines don't get to win ever.
3) Specifically, find where Game is keeping the MacGuffin counters, set them to a hojillion, and lock the value just to spite it.
4) Your impatience draws the ire of the Patron Saint of Backgammon, who under the rules of Vatican II is stuck with every form of non-physical contest under their purview; they smite Game to reinforce that only they may grant gaming boons.

At this point, GameConqueror throws up on the console once a second-

    error: failed to attach to 16328, No such process

-as it tries to keep the specified value in memory.  It should stop trying to hold the value when the process it was watching gets derezzed.

**Comment by sriemer** [comment]
Please bare in mind that not every developer is a native speaker. The detection if a process is really gone can be pretty complex.

[ugtrain](https://github.com/ugtrain/ugtrain), which is a game trainer which runs the game, has that detection [here](https://github.com/ugtrain/ugtrain/blob/bebbf30032c3334e88eb9247c23577ad444bf0e5/src/ugtrain.cpp#L1205) with code from [here](https://github.com/ugtrain/ugtrain/blob/bebbf30032c3334e88eb9247c23577ad444bf0e5/src/lib/system_l.c#L63). It basically comes down to checking if directory `/proc/$pid/` still exists and checking the state in `/proc/$pid/status` directly. I have the same for the detaching there.

**Comment by BluecoatEngineer** [comment]
> Please bare in mind that not every developer is a native speaker.

Of English?  I should hope not; it's a sloppy language with far too many homophones, as you've just demonstrated. :-)  (Bare == naked, Bear == carry)  Irregardless, your title change is for sure more accurate.  "Dies Horribly" was meant to convey any sort of abnormal process termination (segfault in my case).  After filing the bug I realized that it happens even if the process exits gracefully!

> The detection if a process is really gone can be pretty complex.

What does "really gone" mean?  If it goes Zombie or Dead, it's not coming back and GameConqueror / ugtrain should detach.  Also, I agree that your "check_process" code is complex; you're building strings of shell commands so you can parse /proc/$pid/status using sed and then executing them with a system call!  You're also checking that the PID matches the process name unnecessarily.

Much simpler implementation:
1) when you attach to a process, use stat to check if /proc/$pid/stat exists.  Open it, and save the file descriptor.

2) To check if the process is alive, rewind() and use fscanf to grab the third field; that's the process state.  If it's Z, X, or x, the process is dead and you can detach.

This has the added benefit of not opening / closing the file on each check, eliminating the chance you'll "miss" the process ending and getting reaped.  It's additionally much, much faster than spawning multiple subprocesses in a shell.

**Comment by sriemer** [comment]
Thanks for your recommendations. Yes, for ugtrain I've implemented it in a lazy way as I had the shell commands at hand. For scanmem/GC I'll implement a better variant. Thanks for reporting.

**Comment by sriemer** [comment]
The function is optimized now and also implemented for the scanmem `set` handler but without checking the process name. I'm still working on the GameConqueror part.

**Comment by sriemer** [comment]
The bug is fixed. So closing. Thanks.
