### ISSUE TITLE
Possible to use scanmem without ptrace?

### ISSUE THREAD

**Issue by Cloudef** [scanmem/scanmem#325]
My workflow is follows:
- Find the address of variables I'm interested in scanmem
- Attach gdb and add watchpoints for the addresses, so I know what writes/reads them
- Finally look up the related code in radare2 for analysis

However, now scanmem can't be used until gdb is detached. Not a huge inconvenience, but was wondering if it's possible to make scanmem optionally read /proc/<pid>/mem directly or use the syscalls as detailed here https://stackoverflow.com/a/35639708

**Comment by 12345ieee** [comment]
The guy that opened that SO question asked us the same thing some time ago, in #198 , I believe there you can find some answers.
He is also the author of the related https://github.com/korcankaraokcu/PINCE , which might suit your use case better.

About `/proc/pid/mem`, that's exactly what scanmem uses, as it's order of magnitudes faster than looping `ptrace`, but to read that file for another process you need to attach to it with `ptrace`, so it changes nothing.

**Comment by Cloudef** [comment]
Thanks, seems like it's not possible on linux. I know about PINCE, but sadly it's not really up-to-par of CE, or even just using gdb. I would use r2's debugging facilites, but they don't really seem to work well compared to standalone gdb, so I've been pretty much forced to rely on different tools, and it isn't actually that bad in the end as every tool does that one job pretty well in the end.

**Comment by Cloudef** [comment]
I've looked at ugtrain and it's interesting. Unfortunately I'm working with a wine process, which it doesn't work with I guess. (I guess easiest would have windows version of ugtrain that you can run inside wine, or use CE for similar ability to find pointers). My end goal is to just modify and document the machine code itself though, so I don't really need pointer searching ability, though it could make life easier if I need to find variables again. My usecase for scanmem for this project, is solely for finding variables which I can then watchpoint to see what writes/reads them, to find the relevant code sections I want to understand / modify. In short, I'm modifying/patching a game statically rather than writing a trainer to do it runtime.

**Comment by Cloudef** [comment]
https://www.youtube.com/watch?v=zw4fWzTWGx8 (that said, I wrote some tools to reload the modified code back to the program's memory runtime)

**Comment by sriemer** [comment]
There is also a simple tool already using `process_vm_readv()` with https://github.com/skeeto/memdig. But it has to attach as well. I think the best solution to this would be a special crafted gdb extension which uses (a maybe modified) `libscanmem`.

Something like a `scanmem` or short `sm` command:
```
(gdb) scanmem option scan_data_type number
(gdb) sm 4
01/25 searching   0x62d000 -   0x650000..........ok
...
info: we currently have 29353 matches.
(gdb) 
```

It is important that the process which attaches also conducts the search. Has to be researched how to do this. I'd be willing to look into this.

**Comment by Cloudef** [comment]
That would be quite nice actually, it's not super important though. Detaching/attaching doesn't lose your work in gdb after all. 

I wrote this bit more generic tool to read/write memory regions as well https://git.cloudef.pw/proc-region-rw.git/tree/proc-region-rw.c, but didn't try the vm syscalls yet. This tool isn't intended to replace scanmem or such, it's just a bit more dumber one for writing various tools on top of, and for overwriting memory mapped files / replacing the program code.

One thing that would be nice is real-time memory view. Do you happen to know any existing tools for this?

**Comment by 12345ieee** [comment]
GameConqueror, the scanmem GUI, has a realtime memory view.
The CLI doesn't.

Il 10:18 Ven 19/Ott/2018 Jari Vetoniemi <notifications@github.com> ha
scritto:

**Comment by Cloudef** [comment]
>GameConqueror, the scanmem GUI, has a realtime memory view.
Hmm are you sure. The memory view doesn't seem to refresh on its own.

**Comment by 12345ieee** [comment]
Ah, yes, you have to hit refresh when you want.

Having it (optionally) autorefresh every second wouldn't be difficult, can be implemented if you're interested.

**Comment by Cloudef** [comment]
>Having it (optionally) autorefresh every second wouldn't be difficult, can be implemented if you're interested.

Having used CE before, I thought it was useful feature, especially how CE has this fading effect for bytes that change in the memory. Really useful for finding interesting stuff near the variables you have found. (As well as seeing how areas of memory respond to actions you make in program)

**Comment by 12345ieee** [comment]
The conversation here deviated a bit, but the answer to the question in the title is: now yes, due to #372 .

I'm closing this for now, feel free to reopen if there's other relevant stuff to discuss.
