### ISSUE TITLE
Android: configure: error: C compiler cannot create executables

### ISSUE THREAD

**Issue by 7763sea** [scanmem/scanmem#327]
export NDK_STANDALONE_TOOLCHAIN="/usr/local/ndk/toolchains"

./build_for_android.sh

Defaulting to arm-linux-androideabi
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-linux-androideabi-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for arm-linux-androideabi-gcc... no
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/deeplearning/Desktop/android_memory_test/scanmem':
configure: error: C compiler cannot create executables
See `config.log' for more details

**Comment by sriemer** [comment]
The path `/usr/local/ndk/toolchains` is wrong for the standalone toolchain. Please follow the instructions linked in README.md.

The command is something like this:
```
$NDK/build/tools/make_standalone_toolchain.py --arch arm --api 21 --install-dir /usr/local/arm-android-toolchain

export NDK_STANDALONE_TOOLCHAIN="/usr/local/arm-android-toolchain"
...
```

**Comment by sriemer** [comment]
Closing as invalid for now. Issue seems to be resolved. Feel free to reopen if that is not the case.
