### ISSUE TITLE
[Question] how do I mount /proc

### ISSUE THREAD

**Issue by Mhowser** [scanmem/scanmem#330]
It is listed as a requirement but since I'm a Linux noob I dont exactly know how to mount `/proc` correctly.

Thanks in advance!

**Comment by 12345ieee** [comment]
Assuming you're using a reasonable Desktop distro it's already mounted.

Run `ls /proc`, if you see something, it's mounted.

**Comment by sriemer** [comment]
Does this answer your question so that we can close this?
```
sudo mount -t proc none /proc
```
otherwise.

**Comment by Mhowser** [comment]
You can close this thread now. The program I'm targeting isn't compatible
with gameconquerer.
