### ISSUE TITLE
Error while compiling for android

### ISSUE THREAD

**Issue by MichaelElianKevin** [scanmem/scanmem#333]
I have tried to run sh build_for_android.sh but i got this error at the end.
/usr/bin/ld: ./.libs/libutil.a: error adding symbols: archive has no index; run ranlib to add one
collect2: error: ld returned 1 exit status
make[2]: *** [scanmem] Error 1
make[2]: Leaving directory `/home/clown/scanmem'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/clown/scanmem'
make: *** [all] Error 2

what is the problem and how to solve that?

**Comment by MichaelElianKevin** [comment]
I have solved the problem by run ranlib. thanks

**Comment by sriemer** [comment]
Please report required code changes in form of commits/patches/diffs. Reopening. I'll look into this in a couple of weeks.
