### ISSUE TITLE
Android build failed libreadline-dev not found

### ISSUE THREAD

**Issue by MichaelElianKevin** [scanmem/scanmem#334]
I have tried to install using ./build_for_android but i got this error at the end.

> checking for tgetent in -ltermcap... no
> checking for readline in -lreadline... no
> libreadline could not be found, which is required to continue.
> The libreadline-dev package may be required.

i have installed libreadline-dev
how to fix that?

**Comment by MichaelElianKevin** [comment]
fixed, thanks

**Comment by sriemer** [comment]
Yep, the `libreadline-dev` package on the host system is not the right one. So the script downloads required package source and builds from there.

Was this just a usage issue or is this something to be changed here at upstream?
