### ISSUE TITLE
Feature Request: undo

### ISSUE THREAD

**Issue by asdf23** [scanmem/scanmem#341]
Sometimes I'll run a filter and realize that it was incorrect..
35> =
0>

Whoops.. I didn't mean = I meant !=

**Comment by 12345ieee** [comment]
This and #340 suffer of the same technical problem:
keeping the current match list and N old ones in memory takes (N+1) times the memory, which is a lot in dense scans, as SM uses roughly 4 bytes per matched byte.

I can think about some clever schemes to pack some undo data in the structure, (using some flags bit for an undo count and masking them for every other use), but that means you have to keep the big initial list in memory until it's out of the buffer.

Ultimately, I should find a way to decrease memory usage, maybe a flags map...
I'll think about this.

**Comment by asdf23** [comment]
> This and #340 suffer of the same technical problem:
> keeping the current match list and N old ones in memory takes (N+1) times the memory, which is a lot in dense scans, as SM uses roughly 4 bytes per matched byte.
> 
> I can think about some clever schemes to pack some undo data in the structure, (using some flags bit for an undo count and masking them for every other use), but that means you have to keep the big initial list in memory until it's out of the buffer.
> 
> Ultimately, I should find a way to decrease memory usage, maybe a flags map...
> I'll think about this.

I think just save to disk no?
On an unrelated subject.. I think heap memory never send to be the right answer.. Not sure how that comes into play here or not. It seems to me that messing with heap = crash

**Comment by asdf23** [comment]
... I mean I could do this.... 
List and perhaps dump to terminal > copy to file > format to json > to javascript > external call to scanmemlib? > repeat to refine list
Whereas the javascript program would store and I guess clear the memory...

Along that line.. If I could.store history and convert that to svg.. Hard to explain.. But hex values under semi-transparent ovals streching over blocks of data, that have some sort of gradient that changes with the values. Think gray caterpillars crawling lines of changing instering data, changing colors associated with values changes...

**Comment by sriemer** [comment]
The undo can do more harm than benefit. It is unknown if the game process is still in the same state. In terms of memory consumption this does not make any sense. Unless you find enough supporters for this, this is invalid.
