### ISSUE TITLE
Feature Request: Save list

### ISSUE THREAD

**Issue by asdf23** [scanmem/scanmem#342]
Sometimes I'll file a memory region such as a number of lives.
Great now I want to run:
1> set 0=1/5

Okay.. now I want to find how to alter the gun type. Problem is I need the memory region in my list and reset every 5 seconds. 

Ideally I'd like to be able to save the list. Then jump to a new list. So while my lives are being reset.. Or pehaps while I'm searching for live. I can switch directions searching for a different thing that is not related to the previous list. 

If I could manually add a thing to the list, or if scanmem had the concept to save and set memory regions separated from finding new memory regions.  

Also when I load up a new game.. I have to re-find each cheat. I'm turning of memory randomization and I'm playing old nintendo/dos games so (I believe) these memory regions are in predictable places.  I can do a write command... however I cannot automatically set the memory regions without it being in the list.

**Comment by sriemer** [comment]
You are actually looking for a real game trainer. You can run multiple `scanmem` instances fighting for the same game process to attach via `ptrace()`. So if you're fine with seeing lots of errors, then go this way. Otherwise, put the stuff you've found into a game trainer config. `GameConqueror` only supports static memory within a non-PIE executable. So very likely `GameConqueror` cannot handle what you need. I've created a [feature issue for ugtrain](https://github.com/ugtrain/ugtrain/issues/57) already for doing value freezing during discovery. This is not really trivial and takes time which I don't have right now. Feel free to research how this is done and to contribute a working feature.

**Comment by sriemer** [comment]
`scanmem` is a memory scanner and not a game trainer. So closing as invalid.

**Comment by asdf23** [comment]
> You are actually looking for a real game trainer. You can run multiple `scanmem` instances fighting for the same game process to attach via `ptrace()`. So if you're fine with seeing lots of errors, then go this way. Otherwise, put the stuff you've found into a game trainer config.

Thank you, I did not think of that. At the core my c-fu is very lacking. This tool is amazing, and gets very close to the other crazy use-cases that I can imagine.I am got yet aware of game trainers. I'll have to look into it. 

>  `GameConqueror` 

I never used this, but what I was able to do was to take the results from scanmem deserialize to some json/object array, then convert that into other commands. I'll post it. Next I want to convert the memory regions to svg/graphics.

> only supports static memory within a non-PIE executable. So very likely `GameConqueror` cannot handle what you need. 

I've turned randomization off and only play older pre-90s nes and DOS games. Also the emulator might have a variable here. I can compare game states by loading and then saving game restores. So (I think) even if there was some obfuscation involved I could still get around it.

> I've created a [feature issue for ugtrain](https://github.com/ugtrain/ugtrain/issues/57) already for doing value freez yring during discovery. This is not really trivial and takes time which I don't have right now. Feel free to research how this is done and to contribute a working feature.

Having more of a web based programming outlook.. I don't know that I could take this on atm.. One thing I could contribute though. I have a pretty sweet setup. I can connect a game to a joystick.. And there is this usb device converting a joystick to basic switches and an adrino board.
