### ISSUE TITLE
Feature request: repeated search for unknown value

### ISSUE THREAD

**Issue by ssv-170379** [scanmem/scanmem#343]
Case: Lifebar is full. Search for unknown value. Take some damage. Search for decreased values. Use heal to fully restore health. Search for exactly(!) the first values, not just 'increased' ones. IMO it may greatly reduce steps needed to pin-down required address.

Implementation maybe like: When i planning to later search for exactly this unknown value, add some sort of tag to request, maybe numerical index like '? {0}' or named, like '- {1 hit taken}', and use them later, simply entering that tag in search field, like '{0}'.

I apprehend this may take a lot of memory (to memorize exact values of all matches for particular step), but it really may be a time-savior for some situations

**Comment by sriemer** [comment]
Feel free to implement this for yourself. This indeed takes too much memory for too little benefit. Memory search is not the only method to find interesting values in memory. E.g. with dynamic memory it is often enough to find one value within the same hero object and then dumping and comparing two states of the same object to find further values.

This is not feasible. So closing. Sorry.
