### ISSUE TITLE
Feature requesd: Offset to all addresses

### ISSUE THREAD

**Issue by ssv-170379** [scanmem/scanmem#344]
Case: I made a table for several addresses (e.g. a bunch of usable items in inventory), saved it, but next time game is loaded to a different memory block and all values are moved to different addresses (but with their relative spacing preserved). I need ability to remap saved table to a new range by searching one of the values in new game session and apply difference between old and new address to whole table. Currently I use a short Python script (which edits saved table) for this, but it will be good to be able to do this in-program.

**Comment by asdf23** [comment]
here is how I do it:
First of all I turn off memory randomization. Next I load the game state, I have a couple is saved games at different points, next I know the values I'm looking for. I can pipe commands to scanmen. I'm working on an ability to pipe the result back out. With the output I can convert a list or memory dump to a json object. Then convert that object to one of several scanmen commands. Given all this I can pretty much do what I want. What I can't do is use the timer or basically get the data back into a scanmem list. I'm also working on a memory dump to  svg object to "see" how the memory changes.

**Comment by sriemer** [comment]
ASLR/PIC/PIE + stack value + dynamic memory support are unique features of the universal game trainer [ugtrain](https://github.com/ugtrain/ugtrain) on Linux. Check its documentation and code. Scanmem is no game trainer. GameConqueror tries to be one but is lacking essential methods for things which are not static memory within the executable.

Feel free to contribute PIE support for GameConqueror if you really need it but then you'll quickly notice that there is an issue if there is a mix between static and dynamic memory. Blindly modifying values can cause crashes and in worst case corruptions. So having universal checks makes sense.

Closing as we can't/won't extend GameConqueror to be a real game trainer - no need and not enough development resources.
