### ISSUE TITLE
Android Build

### ISSUE THREAD

**Issue by Raslin777** [scanmem/scanmem#345]
Does not build any arm binary only x86-x64
export HOST=aarch64-linux-android
export HOST=arm-linux-androideabi

is it because it doesn't find:
_checking for arm-linux-androideabi-gcc... no_

https://pastebin.com/Y55VLPSV

**Comment by sriemer** [comment]
It is not meant to work with the NDK directly. It is meant to work with a stand-alone toolchain as described in the README. The link is working. So please build your stand-alone toolchain from the NDK first: https://developer.android.com/ndk/guides/standalone_toolchain.html

**Comment by sriemer** [comment]
Also run `./build_for_android.sh help` first.

**Comment by Raslin777** [comment]
Works perfect! ,Sorry and Thank you
