### ISSUE TITLE
Lua implementation and key-binds

### ISSUE THREAD

**Issue by Zedespook** [scanmem/scanmem#347]
Like in Cheat Engine, it would be really good to see a scripting language to edit game values. Also, setting keybindings to get certain values would be nice. What I mean, like in Cheat Engine, you can set a key-bind to scan a value which got lower/higher from the last scan.

**Comment by 12345ieee** [comment]
While it would be nice to add some more complex features from Cheat Engine or similar, I think, and I imagine @sriemer agrees, that we don't have the dev time to do so.

**Comment by sriemer** [comment]
Yep, I agree. Closing. Thanks.
