### ISSUE TITLE
GameConqueror won't launch with Arch package on Manjaro

### ISSUE THREAD

**Issue by Gonza21Gd** [scanmem/scanmem#349]
I'm using Manjaro (Linux 5.2) and the app won't launch. I've installed GameConqueror via AUR (https://www.archlinux.org/packages/community/x86_64/gameconqueror/). Gives this output when trying to launch:

/usr/share/gameconqueror/GameConqueror.py:1204: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
  GObject.threads_init()
/usr/share/gameconqueror/GameConqueror.py:1205: DeprecationWarning: Gdk.threads_init is deprecated
  Gdk.threads_init()
Traceback (most recent call last):
  File "/usr/share/gameconqueror/GameConqueror.py", line 1206, in <module>
    gc_instance = GameConqueror()
  File "/usr/share/gameconqueror/GameConqueror.py", line 335, in __init__
    self.backend = GameConquerorBackend(os.path.join(LIBDIR, 'libscanmem.so.1'))
  File "/usr/share/gameconqueror/backend.py", line 43, in __init__
    self.init_lib_functions()
  File "/usr/share/gameconqueror/backend.py", line 51, in init_lib_functions
    f = getattr(self.lib, k)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libscanmem.so.1: undefined symbol: sm_process_is_dead

**Comment by sriemer** [comment]
Sounds like an old `libscanmem` has been picked up. The function `sm_process_is_dead()` has been introduced **10/2018**. Version `0.17.1035.0cc3830-1` didn't have this.

Make sure that all three packages `libscanmem`, `scanmem`, and `gameconqueror` are at the same version. I guess the latest version is `0.17-2`. @anthraxx can likely help here.

I don't see an upstream issue here but a packaging/package installation issue here instead.

**Comment by anthraxx** [comment]
the AUR supports Arch Linux, Manjaro is not Arch Linux. Its like intalling debian packages in Ubuntu, it may or may not work for various reasons.
Also the posted link above is not the AUR but the official Arch repositories, which I also can't give any advice for behavior in Manjaro.
For me the latest git version of gameconqueror works perfectly, guess libscanmem was not installed when installing from AUR

**Comment by sriemer** [comment]
@anthraxx Thanks for your help. Already thought about that. I‘d like to get the empty process name fix and the subcommand completion out the door. Let‘s add the forward stack offset support as well and release 0.18. We both upstream maintainers didn‘t really find the time to implement bigger features for 0.18. Being a maintainer shouldn’t mean that we have to implement all features ourselves.

**Comment by 12345ieee** [comment]
Yeah, I'm not opposed to cutting a v0.18 soon.

Give me some days to review your pending PR and check if there is some small thing I want to get in.

**Comment by Gonza21Gd** [comment]
Thanks for the help, problem solved :)

> Sounds like an old `libscanmem` has been picked up. The function `sm_process_is_dead()` has been introduced **10/2018**. Version `0.17.1035.0cc3830-1` didn't have this.
> 
> Make sure that all three packages `libscanmem`, `scanmem`, and `gameconqueror` are at the same version. I guess the latest version is `0.17-2`. @anthraxx can likely help here.
> 
> I don't see an upstream issue here but a packaging/package installation issue here instead.
