### ISSUE TITLE
Can GC/scanmem do that? (track changes to code)

### ISSUE THREAD

**Issue by x3c** [scanmem/scanmem#352]
I have a Windows game, which runs fine in under Linux + wine. I can access it with GC while it runs and freely modify strings in there. It works.

The game at some points loads a DLL which does some very minor code modification in the memory of the main process, probably punctually, at load time. Most likely, adds some RETs or NOPs here and there. I can not really tinker with that DLL. I'd like however to be able to identify what it did to the process, and selectively reverse the changes after they are made.

This way, the DLL is happy, and I'm happy.

Can GC/scanmem do that? If not, what kind of tool would you guys recommend?  I don't have a RE background so tools such as Ghidra or IDA are totally over my head (I'm a high level language programmer though).

**Comment by korcankaraokcu** [comment]
You might need a debugger for this. However, debugging an emulator might be tricky, wine probably has its own tools for debugging purposes. Without a debugger, you can take snapshots of the emulator memory and compare the sections after the dll is loaded. This requires you to know the exact moment when the dll is loaded tho, so might not be possible.

How about debugging it within a virtual machine? So you wouldnt have to deal with emulation layer.

**Comment by sriemer** [comment]
What you request is out of scope for scanmem/GameConqueror.

The library accesses memory directly. So there is no easy way to track what it is doing. With a debugger you can't set watchpoints to all code memory addresses. With API hooking it would be possible to get the code regions at executable load and also at (or rather short time after) library load. You could also prevent the lib from loading via API hooking or Wine source modification.
An x86_64 emulator emulating every assembly instruction and dumping code memory modifications would be too slow. Games often notice if they fall out of realtime and just terminate.

Reverse engineers would analyze the assembly code of the lib and overwrite unwanted parts with NOPs or if more space is needed, with jumps into a further code region with own/modified code and back - this is a so called `code cave`.

This is definitely a task for custom coding or reverse engineering.

**Comment by sriemer** [comment]
@x3c Is the question answered so that this can be closed? TIA

**Comment by x3c** [comment]
Absolutely. Thanks guys.
