### ISSUE TITLE
Enhancement: Search for unknown values in GameConqueror

### ISSUE THREAD

**Issue by AlexApps99** [scanmem/scanmem#360]
Currently when searching for a number there is only a box with asking for a value.
I propose that a dropdown next to the value input should be added that selects an operator eg <, <=, =, !=, >=, >, and 3 buttons to say whether the number has increased, remained the same or decreased.

This is because the exact number of a memory location is not always known, so comparison operators would allow for easier finding of some locations and an increase/decrease/neither button would be helpful if the values it is set to are unknown.

I am aware that this can be done syntaxically, but it would be a lot better if there was a way to do it through the GUI.

**Comment by 12345ieee** [comment]
This is a list of the allowed operators:
```
 N         Exactly this number
 N..M      Range between two numbers
 ?         Unknown initial value
 > or +    Increased values
 < or -    Decreased values
 =         Unchanged values
 !=        Changed values
 > N       Greater than N
 < N       Less than N
 + N       Increased by N
 - N       Decreased by N
 != N      Other than N
```

not all of them take one number as argument, some take 0, some 1 and some 2, so
supporting all the changing input boxes in the GUI is not in the plans.

**Comment by DHLF** [comment]
> Currently when searching for a number there is only a box with asking for a value.
> I propose that a dropdown next to the value input should be added that selects an operator eg <, <=, =, !=, >=, >, and 3 buttons to say whether the number has increased, remained the same or decreased.
> 
> This is because the exact number of a memory location is not always known, so comparison operators would allow for easier finding of some locations and an increase/decrease/neither button would be helpful if the values it is set to are unknown.
> 
> I am aware that this can be done syntaxically, but it would be a lot better if there was a way to do it through the GUI.

It sounds like an easy addition but it may be necessary for people with disabilities like one armed(no offense intended!).
Using the keyboard also seems to me the fastest way to get all the searches done.
I would always prefer using the keyboard over moving a mouse pointer instead to select tiny buttons (or drop down menu like +/- = or != ) 

But this depends on different people with different likings/abilities.

**Comment by AlexApps99** [comment]
Alright, will close this as it's difficult to implement and could clutter the GUI.

Thanks for all of the work on this amazing tool so far :)
