### ISSUE TITLE
GC saving address list does not work any more(GC 0.18~dev)

### ISSUE THREAD

**Issue by DHLF** [scanmem/scanmem#361]
"Found" addresses which has been saved by gc0.17 loads fine using gc0.18dev.
But saving found addresses did not work correctly in gc0.18dev.

Working list created with gc0.17:
```
{"cheat_list": [
["=", false, "Keine Beschreibung", 140357222670409, "string", "Hero", true]]}
```

Not working list created with gc0.18dev:
```
{"cheat_list": [
[false, "Keine Beschreibung", 140357222670409, "string", "Hero", true]]}
```
In any entry in the table `"=",` is missing so gc cant read the saved table any more.

**Comment by 12345ieee** [comment]
Oh dammit, I broke this in 461b583c5e389d198 .

**Comment by DHLF** [comment]
No problem -at least for me- as i am using automated scripts to build those tables from scratch to put in the proper values.
To circumvent those bug we could just add those missing `"=", ` manually each time.. but most of the users will miss this feature(the working version).
