### ISSUE TITLE
Game Conqueror depends on python-gi

### ISSUE THREAD

**Issue by caseyomah** [scanmem/scanmem#364]
In Ubuntu 19.10 running `gameconqueror` from command line after following GUI install instructions yields:
```Traceback (most recent call last):
  File "/usr/share/gameconqueror/GameConqueror.py", line 35, in <module>
    import gi
ImportError: No module named gi
```

Installing package python-gi resolves this issue. Suggest adding to dependency list.

**Comment by 12345ieee** [comment]
I've looked, and in Debian/Ubuntu the package depends on python3 and python3-gi, but you're probably running it with python2, hence the issue.

I page in out maintainer for Debian @kartikm , he can tell us more.

**Comment by kartikm** [comment]
In Debian, gameconqueror depends on 'python3-gi' already.

**Comment by 12345ieee** [comment]
Thanks Kartik, so this is actually fixed in the distributions, I've also checked on salsa, we have the shebang set to py3.

I'm closing this for now, if someone else comes from google with the same problem, please let us know what distro and GC version you're using.
