### ISSUE TITLE
PINCE integrates libscanmem

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#371]
Just a heads-up that PINCE has a new PR that integrates libscanmem:
https://github.com/korcankaraokcu/PINCE/pull/76

Any opinions on this @12345ieee?

**Comment by 12345ieee** [comment]
Had a very brief look, they pass through a modified copy of the GC backend which is good, so the exposed api is somewhat limited.

It would be better to provide the bindings ourselves, though, maybe we can discuss with them how to extract out what they need and provide a python API.

I was looking forward to this, I find the C library the interesting part of this project, it's high time someone with better frontend skills makes a good frontend and we just focus on the library and the CLI frontend.

I'm having a chat with the guys on discord right now.

**Comment by 12345ieee** [comment]
I have committed ba6d473781838846908d459d5c8272a69a2a0f42 to help the guys out.

We now provide a self-contained Python interface for libscanmem via the `scanmem.py` file, that should be used by any downstream project that wants to talk python to it.

I'm sure it'll need further modifications, but now they can carry on the integration without replicating effort we had already done.
