### ISSUE TITLE
Is there any way for scan for pointers?

### ISSUE THREAD

**Issue by Klairm** [scanmem/scanmem#375]
So on a game i want to have infinte ammo, but everytime i die the memory adress where is located it changes ( also there are 2 addresses for ammo), so it's kinda boring having to search for the address everytime.

Also how would be able to find for health address?

Is there any real good replacment for CE on linux?

Sorry if i'm making some offtopic  questions

**Comment by 12345ieee** [comment]
Scanmem only provides memory searching and editing capabilities, to follow pointers you need more of a debugger.

You can look at the following projects, that are still focused on game cheating: https://github.com/ugtrain/ugtrain and https://github.com/korcankaraokcu/PINCE

**Comment by Klairm** [comment]
> Scanmem only provides memory searching and editing capabilities, to follow pointers you need more of a debugger.
> 
> You can look at the following projects, that are still focused on game cheating: https://github.com/ugtrain/ugtrain and https://github.com/korcankaraokcu/PINCE

I tried those, but i just dont understand how to use them, they are not much user friendly as scanmem or gameconqueror, that's why i'm asking something like CE
