### ISSUE TITLE
[Feature Request]Way to use speedhacks on GUI

### ISSUE THREAD

**Issue by Neverest** [scanmem/scanmem#379]
Don't know if I missed it, but if not, it would be great to have a way to alter a game's speed via GameConqueror if its possible. This is how it appears on Cheat Engine(right of memory scan options):

![image](https://user-images.githubusercontent.com/13340767/81026078-e3dd2f80-8e46-11ea-8e9d-cccce0a65116.png)

Speeding up the grinding on rpg's is a godsend.

**Comment by 12345ieee** [comment]
Eh, I'd like to have this as well, but the only way I can think to do this is `LD_PRELOAD`-ing every timewaster in the C library and modifying the input values to them (stuff like `sleep`, `nanosleep` and so on).

This path has already been refuted in #65 and #233 , as scanmem/GC isn't really made for it.

I won't close this immediately, maybe some contributors have better ideas on how to implement it

**Comment by marcussacana** [comment]
what about include this tool? https://github.com/evg-zhabotinsky/libspeedhack

**Comment by sriemer** [comment]
@marcussacana This requires `LD_PRELOAD`. Neither `scanmem` nor `GameConqueror` start applications. So this won't work without major architectural changes for which there aren't enough development resources.

It should be also possible to inject the library with a debugger but neither `scanmem` nor `GameConqueror` come with debugger features. Debugger features aren't implemented for the same reason: Lack of development resources. So IMHO this is something for e.g. [PINCE](https://github.com/korcankaraokcu/PINCE).

**Comment by marcussacana** [comment]
huh... I will wait the github publish the discussions feature, I don't wanna open a issue because of a request.
