### ISSUE TITLE
Explanation of offsets with GameConqueror

### ISSUE THREAD

**Issue by NoussMaster** [scanmem/scanmem#387]
Hi all!

I don't understand what the offsets on gameconqueror mean, could someone please explain it to me.

I have a base address which is 55ed015cc000 and the ball address is 55ed02a8d838.

GameConqueror tells me that the offset of the balls is 37838.
So I took the base address and added the offset to see if I get the memory address of the balls but not at all, I have a completely different memory address (55ed015cc000+3738 = 55ED015CF738)

**Comment by 12345ieee** [comment]
The offset is from the start of the region, if GC tell you the address is `55ed015cc000`, that is the actual address.
The memory region just happens to start `37838` bytes before that, this might be useful info if you are mapping many memory locations.

**Comment by NoussMaster** [comment]
In fact the base address is not GC that tells me that.

I got it by doing a cat /proc/PID/maps.
GC just gives me the ammo address. Can you shed some more light on this for me, please?

**Comment by sriemer** [comment]
@NoussMaster Offsets make sense for static memory in positions-independent executables (PIE) or libraries (position-independent code, PIC). In theory, static memory means static addresses but the base/load address of those binaries is randomized in memory by address-space layout randomization (ASLR). The load address is the start of the .text region. The variables in static memory are accessed the same way in the code (relative to the instruction pointer).
So you see the offset in the disassembly of your non-PIE binary file as the address of the variable.

You need it to access the static memory value reliably at each program execution. A game trainer with ASLR/PIC/PIE support gets configured by that offset and adds the current load address to get the effective memory address.

Does this answer your question?

**Comment by sriemer** [comment]
The `scanmem` `lregions` command shows the load addresses and `scanmem` has better support for the match offsets in general as it shows the region ID to which a match offset belongs. It even shows the region type.

`55ed02a8d838 − 37838 = 55ed02a56000`.
Looks like your match is **inside the heap region** and is not part of the PIE. For dynamic memory cheating I recommend [ugtrain](https://github.com/ugtrain/ugtrain) which discovers dynamic memory allocations by recording them all and matching against the found heap address from scanmem.

Question answered. So closing.
