### ISSUE TITLE
Cannot run GC on Gentoo

### ISSUE THREAD

**Issue by ShorTyy05** [scanmem/scanmem#390]
I emerged scanmem from the official repository, with the following USE flags:
`USE="gui -static-libs" PYTHON_SINGLE_TARGET="python3_7 -python3_6"`,
 but whenever i try to run gameconqueror, I get the following output:
`Error getting authority: Error initializing authority: Could not connect: No such file or directory`
How do I fix this?

**Comment by ShorTyy05** [comment]
Launching GameConqueror.py directly, works though.

**Comment by 12345ieee** [comment]
This looks like a `pkexec` error.
Can't help you with that, but as you've seen you can bypass that.
