### ISSUE TITLE
GameConqueror cannot find 'gi' module (it's installed)

### ISSUE THREAD

**Issue by arrrbeee** [scanmem/scanmem#391]
Here's the error I'm getting:

```
Traceback (most recent call last):
  File "/usr/share/gameconqueror/GameConqueror.py", line 35, in <module>
    import gi
ImportError: No module named gi
```
When I run `which python3`, it returns: `/home/xxx/anaconda3/bin/python3`.

So I checked by running `python3` and then `import gi` and it worked. I also tried with vanilla Python `/usr/bin/python3` and confirmed that `import gi` works as well.

Interestingly enough, if I just run `python3 /usr/share/gameconqueror/GameConqueror.py`, the program opens.

Any ideas on how to debug this?

**Comment by 12345ieee** [comment]
Check that py3 is used in the script, maybe the script is using py2.

**Comment by bkazemi** [comment]
Try setting the distro's default python to python3.

**Comment by sriemer** [comment]
Seems to be solved. So closing.
