### ISSUE TITLE
[Feature Request] Allow libscanmem to search for executable regions

### ISSUE THREAD

**Issue by korcankaraokcu** [scanmem/scanmem#406]
Libscanmem currently discards executable regions even when scanning with full scope. It can be quite useful for debugger integrations, such as PINCE. This feature is also requested in https://github.com/korcankaraokcu/PINCE/issues/107

**Comment by sriemer** [comment]
Could be easily done by adding a scan level 4 I guess. Got no time to implement this unfortunately. Feel free to contribute.

**Comment by pollev** [comment]
Hello,

I also need this feature (and would also like to see it added to PINCE).
I have opened a PR for this: https://github.com/scanmem/scanmem/pull/410
Please give feedback and merge if appropriate.
