### ISSUE TITLE
GUI Installation problems on Kali Linux

### ISSUE THREAD

**Issue by randomguybob** [scanmem/scanmem#407]
I am using Kali (based on Debian):  
Linux kali 5.9.0-kali1-amd64 #1 SMP Debian 5.9.1-1kali2 (2020-10-29) x86_64 GNU/Linux

I get this error when running "make":
make[2]: *** No rule to make target 'all-@USE_NLS@', needed by 'all'.  Stop.

True, I don't see it in the makefile.

TIA <3

**Comment by sriemer** [comment]
Sorry about that. The code base didn't receive much updates recently. I was busy with health recovery and I'm busy with a toddler right now. Priorities shifted for me as nobody would pay me for scanmem development. I guess there are similar issues at the side of @12345ieee. Maintaining this code base alone is pretty hard.
NLS should be "native language support". We don't have something like that in the code. Seems to be an incompatibility introduced by more recent autotools. There is an article about it: https://thegreyblog.blogspot.com/2017/11/making-gettext-optional-during-build-of.html
Please try using `./configure` together with option `--enable-nls` and report back if this works. TIA

**Comment by randomguybob** [comment]
Awesome - this works! Thanks.

**Comment by 12345ieee** [comment]
Indeed I'm busy with work and other projects, I read, but cannot really act.

Thanks for triaging this one @sriemer .
