### ISSUE TITLE
gameconqueror not following system gtk theme on kde plasma

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [scanmem/scanmem#411]
pretty self explanitory issue, and I am pretty sure it is caused by the use of python in the gui

**Comment by grazzolini** [comment]
It doesn't follow the theme on any environment, from what I can tell. I'm using i3 WM. This one is kind of annoying, since it blinds you in low light environments.

**Comment by 12345ieee** [comment]
The gtk version is mildly old, would probably need an update.

Help welcome.

**Comment by Etaash-mathamsetty** [comment]
> The gtk version is mildly old, would probably need an update.
> 
> Help welcome.

Haven't really worked with gtk before and i personally am a python hater, but I'll see what I can do

**Comment by Etaash-mathamsetty** [comment]
ok the problem is that gameconqueror is running through pkexec (root) and because of that it is really tough to set the correct gtk theme

**Comment by 12345ieee** [comment]
Mmm, `gparted` has the same root requirements, does that not set the theme correctly in your systems as well?

**Comment by Etaash-mathamsetty** [comment]
> Mmm, `gparted` has the same root requirements, does that not set the theme correctly in your systems as well?

gparted runs pkexec within the program, while gameconqueror is running under pkexec

**Comment by Etaash-mathamsetty** [comment]
![image](https://user-images.githubusercontent.com/45927311/178110222-a997f1ef-9ea8-476a-a5eb-2d49c7f77b8a.png)
here is an image of the final result
