### ISSUE TITLE
Feature request: Time, custom sized integers and expression based values

### ISSUE THREAD

**Issue by awsdert** [scanmem/scanmem#412]
- [ ] I'd like an option in GC to present the value as a time value, such as HH:MM:SS:MMM (I think that's right for milliseconds).
- [ ] I'd also like to set a custom sized integer to look for, such as 24bits
- [ ] Finally I'd also like to be able to set the table entries to use expressions both to & from the value the address holds, example functions:
* showValue(gotFromMem / 8)
* sendValue((gotFromGui * 8) + 1)

For enabling the user to use those modes in the table maybe add a drop down menu? Something like:

Mode:
* Plain Number
* Expressions Number
* Display as time format...

In each case you could just attach a callback to the items to call instead of directly interfacing with the values, can just switch out the callbacks under the hood, though I imagine you already do that

For the custom sized integers you could just add in brackets next to the base type the number of expected bits, so the type would display as something like int(24), uint(24) & float(16), for the search part just add the base types to the drop down and enable a range box or something for the bit count when the base types are selected

**Comment by awsdert** [comment]
Well for contribution I'd say ideas would be the main as I'm busy with other projects, might jump into the code myself if I ever get my projects to a state I consider them complete enough to ignore for long periods of time, for now I use games and gameconquorer for stress relief.

For worth, an easier time hacking my games since I don't have to spend time converting time data into the readable format. I also like playing emulated games and they sometimes use non-native value sizes which is where the custom size option comes into play, finally there are some games that try to hide the values searching for in memory by multiplying them, hence the expression option.

I've also noticed that I cannot directly edit the addresses for table entries without either going into the source file or just creating a new entry with a new address and deleting the old one which is annoying so would appreciate being able to edit those in app.

Now that I've thought of it it would also be nice to make "slide" entries, meaning that upon activation it does a loop adding x to the address and y to the value after every write upto n times.

These are mainly "quality of life" options that can be appreciated by everyone, I'd also like offset support, so "+4" from parent entry that has address "0x2000000" would point the child entry to "0x2000004", I'm not expecting every change to make it in all at once but I would greatly appreciate at least 1 being added in per update the AUR detects.

**Comment by awsdert** [comment]
> The list of found values does not stay the same anyway (Address Space Layout Randomization, ASLR). So why bother too much about this?

That's where you're wrong in some cases, particularly emulators, I often find that until an update occurs even some steam games retain the same address when booted.

> The write feature is easily accessible via command line (scanmem). The support for ASLR and offsets is something for a real game trainer (GameConqueror is not really one, wrongs software architecture). You might want to look into [ugtrain](https://github.com/ugtrain/ugtrain) for this. The offsets are e.g. visible in the [Chromium B.S.U. config](https://github.com/ugtrain/ugtrain/blob/88e057a22d88360c35170f1101721d72025980bb/examples/chromium-bsu64.conf#L28).

Well at the moment GC is the only real option, as far as PINCE is concerned I've always found it to not yet be ready for daily use when I try it, and I'm too busy trying to get myself a job to spend time on my own attempt at replacing GC.

> The maintainers of this project (like myself) are also very busy, care for this project in their leisure time and do not get enough appreciation for their work. In my case, my personal need for scanmem/GameConqueror changes ended, as I prioritize other things (like e.g. health and work-life-balance) a lot more now.

I'm not expecting to any of you to dedicate entire days or weeks to it, just to work on it when you do find yourself working on GC & scanmem

> So I was actually asking you to put a price tag on your requested features you're willing to pay so that bounty hunters can develop for you what you are requesting. If you cannot contribute anything and are not willing to pay anything, then your wishes are noted and we know that we won't work on them and close this issue as there is no motivation for us to do so. Maybe others will have the same wishes in the future so that a really needed feature can be identified.

If I had the money I would offer it but I don't so I can't, don't expect every user to fork out for features they want when not every user can afford it, you're living in la la land if you think otherwise.

> You cannot demand without giving.
What part of REQUEST equates to demanding to you???

**Comment by sriemer** [comment]
Thanks for reporting. Maybe you hit the personal need of my co-maintainer or other developers.
But e.g. time values are stored very differently in different applications. An example would be integer milliseconds * 70. It depends on the selected clock rate and time resolution.

Your request without associated value means it is nothing more than a wish and this is not even important to yourself. So this is closed.

**Comment by awsdert** [comment]
Well that millisecond issue can easily be solved by simply adding a parameter, you could store the type as "time" or "time(#)" where # would be the custom milliseconds/ticks, the standard math can be applied there after for upto to day intervals, months & years should be ignored until a suitable way to fob off the locality math to the system (I think I would just divide the input by the custom milliseconds/ticks then multiply by the system milliseconds/ticks and just fob it off from there).

As I said before these are "quality of life" changes so even if there's no rush I don't see a reason to outright refuse to do them, just putting them on the TODO list for when you do make time for GC would be enough.
