### ISSUE TITLE
Main branch name "master" is non-inclusive and should be renamed to "main"

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#420]
If @12345ieee agrees, then I'd like to change the main branch name from "master" to "main". The reason behind this is that the old git/GitHub default name "master" can trigger people who were victims of slavery or their ancestors were.
Companies do the same because of this reason.

**Comment by 12345ieee** [comment]
My personal opinion on these sort of things is really negative, but it's directed at GitHub and other big corporations, not at you.

It still starts with `ma`, so it's fine on my muscle memory, feel free to go ahead.

**Comment by sriemer** [comment]
Done, thanks.
