### ISSUE TITLE
CI: Need to migrate away from Travis-CI

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#421]
The travis-ci.org is deprecated and travis-ci.com costs money. So the build of this project should be moved. @airvzxf who is interested in becoming a new maintainer suggests to migrate to [GitHub Actions](https://github.com/scanmem/scanmem/actions).

**Comment by 12345ieee** [comment]
Yeah, the CI of choice for FOSS on GitHub is Actions, I've used it on other projects, I quite like it.

**Comment by airvzxf** [comment]
I'll work in this migration, I forked in this repo [airvzxf/scanmem](https://github.com/airvzxf/scanmem) (main branch). If anyone wants to contribute, feel free to do it.

**Comment by sriemer** [comment]
Agreed to use GitHub Actions and handling this in the other issue. So closing. Thanks for the input. :smiley:
