### ISSUE TITLE
Why after all these years is there still not pointer & offset support?

### ISSUE THREAD

**Issue by awsdert** [scanmem/scanmem#428]
For starters the offset support should be rather easy to implement, just add an array to the end of the base item, so for example this:

```
...
["=", false, "Hearts", 25077096084, "int32", "0", true],
["=", false, "Crop Type Count", 25077097764, "int8", "0", true]
...
```

Would be come this:
```
["=", false, "Hearts", 25077096084, "int32", "0", true, 0, [
["=", false, "Crop Type Count", 1680, "int8", "0", true]]],
```

As for pointers the declaration should be easy enough, just slap a checkbox into the GUI saying "Is pointer" or something like that and add a * to the front of the type like this:

`["=", false, "Hearts", 25077096084, "*int32", "0", true, 32]`

Quick and easy to detect and the extra value between the boolean and the array of offsets would help indicate what size the pointer is expected to be, can just ignore the value when it's not indicated that the item should be treated as a pointer.

As far as under the hood operations to support them goes I expect the offsets should be easy enough, just start by shifting the current implementation from static addresses to offsets from a head pointer which starts as NULL, a simple buffer of head pointers where the length of the buffer indicates the current head pointer (don't need ones that had after returning up a level) should be enough to extend the current method without a heavy change to how it works, as for the pointer support, maybe just store a duplicate of the offset/static address upon creating the object for said item and then just update the original member used for static addresses with the value of either the duplicate offset or the value of the address it pointed to if it was supposed to be a pointer, that should avoid the need to hunt through the code for every reference to the original variable and since it will continue to use it as it originally expected the value to be

And if you're not gonna do it yourself then point me in the right direction as for what functions I would need to look into modifying to then submit a patch for, even if I would be slow due laziness

**Comment by sriemer** [comment]
Because it does not make any sense on Linux. The binary variation is too huge and this is too hard to adapt. scanmem/Gameconqueror focus on what they can do best: Memory scanning. A tool that focuses on being a proper game trainer and integrates scanmem is [ugtrain](https://github.com/ugtrain/ugtrain).

The favorite method of ugtrain is API hooking for dynamic memory support and it can follow pointers from dynamic memory objects. This is the preferred method and can be adapted easily. For educational purposes, also following pointers from static memory is possible. But it is also shown why this is too cumbersome. I'm looking for a new maintainer for this project.

**Comment by awsdert** [comment]
The binary thing is a non-issue as I've already given an example of how to ignore that completely, by declaring the size of the pointer in the entry can just read out that amount into a cleared 64bit integer and use that as an offset of the `/proc/<pid>/mem` file, that puts the problem of pointer size on the user to adapt to their system, additionally can use the local `sizeof(void*)` as the default size since 9 times out of 10 that's what the user will need. Simply put you don't need to put the pointer value in a `void*`, nor do you need to auto-decide the size, you just need a default size the user can change and an indicator in the item entry for the expected size which the user can again change.

**Comment by 12345ieee** [comment]
I'm closing this as nonconstructive.

I hope @awsdert will decide to contribute to the project with the features he'd like, we can then do a review on the code instead of talking big words.

**Comment by awsdert** [comment]
At least point me in the right direction for what functions I would need to edit for the feature to be available

**Comment by 12345ieee** [comment]
The changes you want are sweeping, take your time getting acquainted with the C library codebase first.

You'll need handlers.c edits mostly, and some ptrace.c.

**Comment by awsdert** [comment]
I programme with C as a hobby and from what I've seen of the handlers.c it has nothing to do with my suggested way of supporting pointers and offsets, the scanner does NOT need to change, neither does the means of reading memory, the pointer/offset is purely for gameconqueror, not for libscanmem. As I stated in various ways already, as long as the GUI can identify the default size to treat a pointer - for example a user/cheat list configured value - and has an option for the user to change the  integer type and size it reads as an address(uint64_t etc)/offset(int64_t etc) then it can use the value read from the static/calculated address, use it either as an address or offset depending on the setting given to the entry and the display the value given for that address, child entries can just apply their offsets to either the main head entry's address or the read value's resulting address depending on if the entry is declared a pointer/offset or not. I repeat, NOTHING in libscanmem needs is change, it is only how the values it reads out are used that needs extending
