### ISSUE TITLE
Android: error: failed to attach to PID, Operation not permitted

### ISSUE THREAD

**Issue by lasnikr** [scanmem/scanmem#433]
Related to #393.

Scanmem works on some games but others give following error as soon as I search for something:
```
> = 5
error: failed to attach to 3707, Operation not permitted
error: failed to search target address space.
Please enter current value, or "help" for other commands.
```

I don't know how I would do what @sriemer suggested in android since I am running APK's.

I am running on an emulator through adb, adb is in "root mode"

Any idea / link / reference how to remedy this issue in android?

**Comment by sriemer** [comment]
In a high security environment such as smartphones, it is often not enough to be root. Certain capabilities such as `CAP_SYS_PTRACE` need to be available as well due to security modules. See: https://man7.org/linux/man-pages/man7/capabilities.7.html.

**Comment by lasnikprogram** [comment]
I actually think the error occurs because there is a security mechanism by the application.
Here is a post where I described it a bit more: 
https://stackoverflow.com/questions/76254673/how-to-prevent-ptrace-anti-debugging-in-android

**Comment by sriemer** [comment]
Closing as there does not seem to be a `scanmem` issue that could be fixed soon.
Thanks again for reporting.
