### ISSUE TITLE
Cheat Engine Tables support

### ISSUE THREAD

**Issue by Mte90** [scanmem/scanmem#444]
I see it was asked various years ago https://github.com/scanmem/scanmem/issues/285#issuecomment-390495057 so I am asking here in a ticket as it isn't clear the status of this project as the last official release was years ago.

**Comment by sriemer** [comment]
Still no dev resources and no need for this. Those files aren't compatible or of major use on Linux. Following pointers only works well with binaries that rarely differ. This is usually not the case on Linux.
I personally prefer API hooking of memory allocation functions. Those are easy to adapt. See [ugtrain](https://github.com/ugtrain/ugtrain).

Feel free to volunteer as a new maintainer and main developer or to contribute code. We (@12345ieee and I) did the same when we started our maintainer roles. But after quite some time our priorities in life changed. This is why we are pretty inactive here.

Question answered. So I'm closing this for now. Thanks for understanding.

**Comment by 12345ieee** [comment]
These days I recommend people to take a look at https://github.com/korcankaraokcu/PINCE .

We should probably update the readme saying we're looking for maintainers, the PINCE community has a libscanmem fork, maybe they want to take the whole thing.

**Comment by Mte90** [comment]
For the future also in Pince there was the same request and for similar reasons was closed: https://github.com/korcankaraokcu/PINCE/issues/149
