### ISSUE TITLE
gui: resizing works incorrectly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [scanmem/scanmem#74]
```
try to resize window

it just moving... take a look for video
```

Original issue reported on code.google.com by `i.gnaten...@gmail.com` on 16 Jun 2014 at 5:25

Attachments:
* [Screencast from 06-16-2014 09:24:29 PM.webm](https://storage.googleapis.com/google-code-attachments/scanmem/issue-74/comment-0/Screencast from 06-16-2014 09:24:29 PM.webm)

**Comment by 12345ieee** [comment]
As stated in https://github.com/scanmem/scanmem/issues/149#issuecomment-215374140 and following, the same problem is still present in GC 0.15.7
