### ISSUE TITLE
Feature Request: ranges

### ISSUE THREAD

**Issue by GoogleCodeExporter** [scanmem/scanmem#76]
```
What steps will solve the problem?
1. In the UI, enter a value like "1..100"
2. Press Enter to start the search
3. Scanmem finds all items between 1 and 100

What is the expected output?
#3 above

What version of the product are you using? On what operating system?
0.13, Ubuntu 14.04

Please provide any additional information below.
When using scanmem, I'm generally looking for a range of values, not always a 
fixed value. It's a little tedious to keep searching for "< 101" and then "> 0" 
especially when there are a lot of changing values in memory from the 
application.

I imagine the ascii character(s) used to delimit a range would be something up 
for debate, perhaps 1:100 since many folks are accustomed to using the colon 
character to denote a range from spreadsheets, etc.

```

Original issue reported on code.google.com by `iandouglas736` on 23 Jun 2014 at 3:50

**Comment by phadric** [comment]
yes! that would be awesome.
For example if you have a value where the last digit is unknown. For example the game only shows 123 but internally it is 1234 and could be anything in between 1230 and 1239.
The only option right now is to search for  > 12329 and then < 12340.
Which is working on one of my Laptops but not on the other as it gives too many results and im running out of RAM.

**Comment by vyacheslavs** [comment]
Hi! I tried to create branch, but failed. Here's the range support for scanmem


[scanmem_range.patch.txt](https://github.com/scanmem/scanmem/files/45445/scanmem_range.patch.txt)

**Comment by sriemer** [comment]
@vyacheslavs Thanks, we need your real name and your e-mail address. You should fork this repo and commit to your fork at vyacheslavs/scanmem. Then you can create a pull request from there. Furthermore, it would be more complete if GameConqueror gets support for this with a second commit as well. But it has to work with Python 2 and 3.

**Comment by sriemer** [comment]
I've implemented this differently and my implementation is actually working. Please review and test! Thanks!

**Comment by sriemer** [comment]
Special thanks go to @iandouglas for reporting this long time ago. I hope that we can become faster now in implementing new features as all the nasty bugs have been fixed in the 0.15 series. Stability has priority over new features.

**Comment by sriemer** [comment]
Remaining TODO: Check man pages and further documentation for the need to update to show the ranges support.

**Comment by apocalyptech** [comment]
Since I'd been watching this and you'd asked for testing: this looks like it's working great for me.  Thanks!

**Comment by sriemer** [comment]
Thanks, @apocalyptech
