### ISSUE TITLE
When Launching Game Conqueror 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [scanmem/scanmem#79]
```


When I am Launching Game Conqueror nothing is showing up.
```

Original issue reported on code.google.com by `lvleo...@gmail.com` on 1 Nov 2014 at 8:51

**Comment by sriemer** [comment]
Could be a duplicate issue of " GUI won't start #77". The question is: Which python version is used?

**Comment by sriemer** [comment]
This is likely a duplicate. So closing.
