### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by GoogleCodeExporter** [scanmem/scanmem#80]
```
搜索value后程序无响应，shell显示
Traceback (most recent call last):
  File "/usr/share/gameconqueror/GameConqueror.py", line 936, in data_worker
    addr, cur_value, scanmem_type, valid = row
ValueError: too many values to unpack
```

Original issue reported on code.google.com by `china.fr...@gmail.com` on 25 Nov 2014 at 12:27

**Comment by sriemer** [comment]
Sorry, this is my fault. Commit 94c3b9545a5dda1f9d2828f84541eba27fbce935 "gui: fix a hang when searching in scan results" fixes this.

**Comment by sriemer** [comment]
The fix has been merged, hence closing.
