### ISSUE TITLE
'set' command don't modify values in memory (ARM, android 5.1)

### ISSUE THREAD

**Issue by ChD1** [scanmem/scanmem#87]
What steps will reproduce the problem?
1. Use Google Nexus 5 (LG) with latest android (5.1)
2. Compile scanmem with latest NDK for arm
3. Upload binary to phone, seems work fine.
4. Searching work fine.
5. Use "set" command to modify values.
6. Use "list" command to check new values, but it is old values.

What is the expected output?
Memory writing works.

What do you see instead?
All work fine. No error messages. Just don't modify values (write command don't work too, i have checked)

What version of the product are you using?
Latest git master

On what operating system?
ARM (android 5.1)

Please provide any additional information below.
I try to compile old version scanmem (0.12, 0.13) (it work fine on android 4.4, except Bus error, but i compiled it in 2011 and fix bus error) but old version don't modify values too. Seems google change something in android 5 :(

If it's metter, in android 5 we need to use -fPIE gcc flag. Otherwise created binary don't start.  With error: only position independent executables (PIE) are supported 

Android source code:
https://groups.google.com/forum/#!topic/android-building/8wtrXszl7hM

**Comment by sriemer** [comment]
Mobile phones are or should be high security environments. Mobile game cheating often requires a hack to gain root and ptrace permissions. On my MeeGo phone I even wouldn't be able to read memory without the aegis hack installer. So you need a hack for your phone and there is no issue in scanmem IMHO.

**Comment by sriemer** [comment]
Btw. If you noticed the bus error as well, much earlier than I did, why didn't you report the issue so that we could have fixed it earlier?

**Comment by ChD1** [comment]
I thought that the project was freezed and is no longer supported. In 2011 when i compiled ver 0.11 to arm (android) platform, i replace many things in source code of scanmem before it can be compiled without errors. But when i run it on my phone, and try to find something i see bus error. Then i insert many print("Message") in source code, compile it again and find my last message. So I figured what the instruction causes an error. And i understand all problems in int64. i replace it and no more bus error.

By the way, yesterday when i compile scanmem again, i saw error messages too. But it will be easy to fix. It was: 
gcc don't know functions: strdupa and strndupa (i just replaced it to strdup and strndup)
gcc don't know function: getline (i just inserted it in source code from here:
https://code.google.com/p/android-source-browsing/source/browse/host-darwin-fixup/getline.c?repo=platform--external--elfutils&name=master&r=fd9379427bd93f38adb15876bb25297dbe04ecc4
)
And i remove all readline & history functions.

**Comment by ChD1** [comment]
I downloaded the kernel source, looked module yama
The documentation says that he has control through sysctrl
In my phone settings, sysctrl no configuration module yama! we can assume that it is not used? Especially because sсanmem normally starts and finds values. It just can not change them. and no error or message is not displayed.

I realized from source scanmem, recording values occurs in ptrace.c system call ptrace (PTRACE_POKEDATA ..... Then indeed, for the recording of these values must comply with the core of the android, not scanmem.

Now flash last custom kernel, power off selinux completely, but i still can't modify values in sm(
This is similar to Google. Their programs have bugs very often lately(

**Comment by sriemer** [comment]
Okay, then even the Yama module is not used. Man, I knew that Android is crap but that broken? Unbelievable! Should be a kernel bug. Thanks for the info. On my real Linux phone everything works like a charme. You shouldn't let Java devs do kernel development. ;-)

**Comment by sriemer** [comment]
Closing as there is no issue in scanmem - works on MeeGo 1.2 Harmattan on ARM.

**Comment by Funmungus** [comment]
Ref #95 Workaround found to set values...
1) As root run the command, `setenforce 0`
2) Run scanmem and set values.
