### ISSUE TITLE
Commit 944a54a0 ("Configurable endianness of data") breaks the build

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#88]
Commit 944a54a0 ("Configurable endianness of data") breaks the build even on Debian Wheezy on powerpc. I've tested the standard Debian Wheezy QEMU VM from https://people.debian.org/~aurel32/qemu/powerpc/. People should test their stuff properly before sending out pull requests,...

````
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -O2 -g -Wall -g -O2 -c endianness.c  -fPIC -DPIC -o .libs/endianness.o
In file included from endianness.c:28:0:
endianness.h:30:1: error: initializer element is not constant
````

AC_C_BIGENDIAN is a much better detection. I'm implementing this at the moment to fix this mess.

**Comment by coolwanglu** [comment]
Closed via #89.
