### ISSUE TITLE
Request for Release 0.15

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#90]
It's been 2 years ago that 0.14 has been released. The current code isn't compatible with the original 0.14 any more (e.g. due to region type and load address support). All pending stability bugs are fixed now. It took quite some efforts. So let's further focus on stability and don't develop/accept new features until 0.15 is released. I'll intensify testing the current code. Further testers/testing welcome! What about releasing in one month May 1?

**Comment by coolwanglu** [comment]
OK. I think I will go through the code and clean a little bit.

**Comment by coolwanglu** [comment]
I've made a few minor changes. I think we are ready for 0.15 :)

**Comment by sriemer** [comment]
I also think so. :-) Thanks! What about the Debian changelog? How do we get this release into distributions next?

**Comment by coolwanglu** [comment]
This debian folder was for the Ubuntu PPA, and I'm considering whether to continue it. 

A separate changelog is used for Debian, I will contact the other maintainer once we release the next version.

**Comment by sriemer** [comment]
With version 0.15 scanmem works fine on the ARMv7 MeeGo 1.2 Harmattan platform again. I've just updated my "harmattan" branch. I've only noticed an issue with the "watch" command. Ctrl+C ends scanmem instead of just watching. I'll open a new issue for that.

**Comment by coolwanglu** [comment]
Done :)
