### ISSUE TITLE
provide tags for release versions

### ISSUE THREAD

**Issue by anthraxx** [scanmem/scanmem#94]
Hey, it would be really awesome if you can push git tags for the release versions so github automatically creates source tarballs for download.
This is especially cool to easily build a concrete version from a tarball. Currently tarballs are only available at the "obsolete" googlecode page (also 0.13 is the newest there).
Also it would make it easier for package maintainers to track new releases.

PS: please don't forget the 0.15 tag once its ready :smiley:

**Comment by sriemer** [comment]
Makes sense. This is something for Lu. Testing of 0.15 shows that it is very good so far.

**Comment by coolwanglu** [comment]
OK, let's release 0.15 then

**Comment by sriemer** [comment]
Something went wrong here. So reopening. You did it on your tree. But not on scanmem/scanmem. master here still points to 009bedfb ("Merge pull request #91 from coolwanglu/master"). I'll fetch that from your tree and push it to this tree.

**Comment by sriemer** [comment]
Unfortunately your tree isn't rebased to the upstream tree here. So I have to extract the latest patch, reapply it and replace the tags here.

````
$ cd scanmem_upstream
$ git remote add wanglu https://github.com/coolwanglu/scanmem.git
$ git fetch wanglu
From https://github.com/coolwanglu/scanmem
 * [new branch]      master     -> wanglu/master
 * [new tag]         0.15       -> 0.15
 * [new tag]         v0.15      -> v0.15
$ git fetch
$ git reset --hard origin/master
$ git diff wanglu/master
$ git log wanglu/master
$ git format-patch wanglu/master^1..wanglu/master
0001-change-url-to-github.patch
$ git am 0001-change-url-to-github.patch
Applying: change url to github
$ git log
$ vim .git/refs/tags/0.15   # replace commit id with bfc180069dbc936b1a41d80eaf06bbb58efbd9ea
$ vim .git/refs/tags/v0.15  # replace commit id with bfc180069dbc936b1a41d80eaf06bbb58efbd9ea
$ git log 0.15
$ git log v0.15
$ git push origin master
$ git push origin 0.15
$ git push origin v0.15
````

**Comment by sriemer** [comment]
Feel free to remove one of the duplicate tags again.
This is how you fix your tree now:
````
$ cd scanmem
$ git push origin :0.15  # delete tag 0.15 remote on coolwanglu/scanmem
$ git tag -d 0.15  # delete tag 0.15 locally
$ git push origin :v0.15  # delete tag v0.15 remote on coolwanglu/scanmem
$ git tag -d v0.15  # delete tag v0.15 locally
$ git remote add upstream https://github.com/scanmem/scanmem.git
$ git fetch upstream  # get new tags and upstream/master
$ git diff upstream/master
$ git log upstream/master
$ git reset --hard upstream/master
$ git push -f origin master
$ git push origin 0.15
$ git push origin v0.15
````
Now everything should be identical with the upstream repo.

**Comment by sriemer** [comment]
@coolwanglu Btw.: For you and me it only makes sense to send PRs if we want others to review our code. Please apply trivial patches directly to scanmem/scanmem. Thanks!
Others can then follow upstream by "git fetch upstream" and "git rebase upstream/master". We should do that as well if our PR is merged as we have the merge commit then on our trees as well.

**Comment by coolwanglu** [comment]
Oops, sorry for the mistake. How about now?

**Comment by sriemer** [comment]
It got much worse. :-( I wrote the exact commands to fix your repo. But instead now scanmem/scanmem got messed up. A "git log" before pushing is always a good idea.
````
$ git log --oneline upstream/master
7f61dac Merge branch 'master' of github.com:scanmem/scanmem
bfc1800 change url to github
1315864 Merge branch 'master' of github.com:scanmem/scanmem
dfed570 change url to github
009bedf Merge pull request #91 from coolwanglu/master
````
We have here one commit twice now and two completely superfluous merge commits.

**Comment by sriemer** [comment]
My wish to fix this would be:
````
$ git diff HEAD~2
$ git reset --hard HEAD~2
$ git tag -d v0.15
$ git push origin :v0.15
$ git tag -a v0.15 -m ""
$ git diff origin/master
$ git log
$ git push -f origin/master
$ git push origin v0.15
````
This way the superfluous stuff is removed again. All it takes then is fixing your repo as well.

**Comment by anthraxx** [comment]
@sriemer i may agree it gets kind of messy... 
but just wanted to remind you (nothing more nothing less) that force pushing and re-creating tags is also not really the gentleman style of development. force pushing detaches the head for people using a master checkout which points to HEAD before ~2. And now it may be ok to delete and re-create tags because 0.15 is very very new, but in general this is also bad because package maintainers need to fix the tarball checksums over and over again. tags should be kind of static pointers :stuck_out_tongue:

**Comment by sriemer** [comment]
@anthraxx You're completely right. But as long as all developers know about the problem and the hard reset, it is feasible. I prefer this way instead of living with a messed up repo for long time. After fixing the problem once and for all, the tags shouldn't be touched again.
I volunteer for providing all required git commands to fix forked off and local repos. I hope that I can spread some git experience so that scanmem/scanmem won't be messed up in future again.

At work I maintain three custom Linux kernel trees. We have around 20 Linux kernel developers. Everything has to be applied again and again to new upstream versions. So I know quite well how to follow upstream and to keep the trees clean.

**Comment by anthraxx** [comment]
@sriemer yep as mentioned I totally agree here, just wanted to point that out :stuck_out_tongue:
Don't get me wrong I'm also one of those people who incredibly dislike all those (most of the time) useless merge commits and rebase all the things. Some trees start to look like the shanghai subway map so you get a :+1: from me for fighting for clean trees :smile:

**Comment by coolwanglu** [comment]
Oops. Then shall we go back to dfed570 or bfc1800?

**Comment by sriemer** [comment]
bfc180069d as like I've mentioned in dfed570 there is the merge commit 009bedfb0c ("Merge pull request #91 from coolwanglu/master") missing. If you don't rebase your tress and would merge again and again, then everytime you merge, a useless merge commit is created. Then people open the git log and only think "WTF?". This is why also maintainers have to rebase their trees after their pull request got merged.

I'll fix scanmem/scanmem. But then please rebase/reset your tree coolwanglu/scanmem to bfc180069d as well before merging again with scanmem/scanmem. I hope that we can finally fix this once and for all and know what's to do next time. If it would be somebody else, then we would see merge commits in the pull request and GitHub would refuse to merge that. ;-)

**Comment by sriemer** [comment]
Okay, scanmem/scanmem is fixed.
Now everybody who has a tree not based on or pointing to bfc1800 does the following in his forked off tree:
````
$ git remote add upstream https://github.com/scanmem/scanmem.git
$ git fetch upstream
$ git rebase upstream/master
$ git log
$ git diff origin/master
$ git push -f origin master
````
@coolwanglu After these commands your tree should point to bfc1800 as well.

**Comment by coolwanglu** [comment]
Well @sriemer thanks for the explanations. In fact I knew this, I just didn't care too much about the commit messages. I guess it's a bad habit for public repos.

Regarding duplicated messages, why not go back to dfed570 then?

**Comment by sriemer** [comment]
@coolwanglu Like I said: As this would make your merge of pull request #91 disappear which is publically available here and has been applied already here. You've merged it to scanmem/scanmem, so you have to import it to your tree as well. Simple as that.

**Comment by coolwanglu** [comment]
OK. I'll just sync with upstream. Thanks for your fix.

**Comment by sriemer** [comment]
Thanks! Closing this as soon as your tree points to bfc1800 as well
