### ISSUE TITLE
Feature Request: Android build script

### ISSUE THREAD

**Issue by Funmungus** [scanmem/scanmem#95]
I know this was not planned in the development, but it is something I wanted.  I got a slightly hacky command line scanmem to work on Android, both without PIE and with PIE (pre v5.0 and v5.0+).  I used the ndk, v10 (ndk-build.png attached).
While this feature is debated, I will be looking at a way to configure --enable-android without breaking the nicely-featured code already available.

The first picture attached is adb over usb with a correctly found match in PPSSPP emulator.
![scanmem-android](https://cloud.githubusercontent.com/assets/5796430/7109359/2d0b5388-e151-11e4-8a2f-a11132d706f4.png)

Example of the tail of ndk-build.
![ndk-build](https://cloud.githubusercontent.com/assets/5796430/7109373/7ae2c992-e151-11e4-9715-1384c8fad375.png)

**Comment by sriemer** [comment]
What's the problem with compiling twice? You could script that with a shell script or something. Adding too many --enable-FEATURE options can be problematic. Furthermore, "--enable-android" wouldn't explain on the first sight that a double compile is about to be done. IMHO that's something the general code base shouldn't do. That would be against the principles of the autotools. Imagine that then somebody else requests a triple or quad compile with all kinds of variations. It's getting a mess.

Btw.: There is also a problem in Android 5.1, see #87. Looks like they've messed up ptrace(PTRACE_POKEDATA, ...).

**Comment by Funmungus** [comment]
I am not sure how much you would like to know.  To build both -pie and non-pie executables, with all archs is about a dozen compiles.  Maybe I should provide instructions to make some choices in the Android makefiles?
Also the bionic I was building against did not have strdupa/strndupa.  Temporarily I added HAVE_STRDUPA in config.h, and thus considered --enable-android to deal with necessary config.h changes.  However, the scripting is probably a better idea.  I could provide a config.h for Android values, and simply use that for Android builds.  The script could even backup a pre-existing config.h.
Considering poking and modifying values, I also had that problem on both my Android devices 5.0.3 and 5.1.  I fixed this by the terminal command `setenforce 0`(requires root) before using scanmem.  I did not have a problem after that.  I also have not checked if Android has the execl functions to deal with this inside scanmem.

**Comment by Funmungus** [comment]
Update: I plan on a different plan besides HAVE_STRDUPA ifdef switches.

**Comment by sriemer** [comment]
Yes, put this stuff into external makefiles or scripts. E.g. at ProfitBricks we compile for multiple Debian distributions and that's also handled by the build scripts/triggers. It's the most universal way to do as you need it for a lot of packages.
I'm not sure how much you know about the autotools but config.h is auto-generated by autoconf. See "AC_CONFIG_HEADER([config.h])" in configure.ac. If you need a further detection for strdupa/strndupa, then configure.ac is the place where to do that. Look at "AC_CHECK_FUNCS()". Then HAVE_STRDUPA should be defined on your platform and on others not. Patches for this are welcome as long as changes don't break the other platforms. So better test at least one platform with the function and one without.
Thanks for providing the workaround for latest Android. I'm sure that others benefit from that. Would be even better if you could comment that in issue #87 as well.

**Comment by Funmungus** [comment]
To avoid #ifdef switches I would like to replace strdupa and strndupa with alloca and memcpy.  Would this be a problem?

**Comment by sriemer** [comment]
Would be okay. If these are not available, just define them. These are also only macros with glibc.
https://sourceware.org/git/gitweb.cgi?p=glibc.git;a=blob;f=string/string.h;hb=92f2897953ab6cd9e073718cfe36611700e174c6

**Comment by Funmungus** [comment]
Oh I see.  I think android builds based on GCC, so a macro like that should still work.  Thank you for the link.

**Comment by Funmungus** [comment]
strdupa will be solved with pull request #99 .
The other missing thing for Android is a getline replacement.  It works for Android to put this in libreplacement, but are there other platforms for which the following defined test would not be true?
`#if _POSIX_C_SOURCE >= 200809L || _XOPEN_SOURCE >= 700`

**Comment by sriemer** [comment]
Which Android versions are affected? The POSIX standard is from 2008. All platforms not complying should be unmaintained already. Otherwise on UNIX systems providing very old compilers like Solaris there is also always the possiblity to use the GNU stuff like GCC and glibc.

**Comment by Funmungus** [comment]
I believe all purely bionic builds lack POSIX compliance. There is a good chance no non-modded platform is lacking this function.
So shall I keep this in libless.c?  It is only loosely related to excluding libraries, but older systems are not likely to need a memory scanner anyways.

**Comment by Funmungus** [comment]
I have tested Android builds with this on 4.3, 5.0, and 5.1.

**Comment by sriemer** [comment]
Closing this for now until we have the time to include the `getline()` replacement as well.
